packages:
  - "."
  - "desktop"

allowBuilds:
  esbuild: true
  onnxruntime-node: false
  protobufjs: false
  sharp: true
  workerd: true

auditConfig:
  ignoreGhsas:
    - GHSA-w3rx-r6r6-pgpr
    - GHSA-5p2g-fcmc-qvqq

overrides:
  "exceljs@4.4.0>uuid": 11.1.1
  sharp: 0.35.4

patchedDependencies:
  image-size@2.0.2: patches/image-size@2.0.2.patch
