//! Local, bounded technical traces. This journal deliberately has no arbitrary
//! payload, exception message, document, address or account-token fields.
use std::{
    fs::{self, OpenOptions},
    io::{ErrorKind, Read, Write},
    path::{Path, PathBuf},
    sync::{Arc, Mutex, OnceLock},
};

use chrono::{DateTime, SecondsFormat, Utc};
use rusqlite::{Connection, OptionalExtension};
use serde::{Deserialize, Serialize};
use tauri::State;
use uuid::Uuid;

use crate::{
    database::LocalStore,
    error::{command_error, AppError, AppResult},
};

const MAX_FILE_BYTES: u64 = 2 * 1024 * 1024;
const MAX_FILES: usize = 3;
const MAX_BATCH_EVENTS: usize = 100;
const MAX_DURATION_MS: u64 = 86_400_000;
const MAX_SLUG_BYTES: usize = 80;
const ERROR_CODES: &[&str] = &[
    "NETWORK",
    "SESSION",
    "PERMISSION",
    "CONFLICT",
    "VALIDATION",
    "STORAGE",
    "NOT_FOUND",
    "INTERNAL",
    "UNHANDLED",
    "RENDER",
    "LOG_WRITE_FAILED",
    "storage.database",
    "storage.io",
    "input.json",
    "document.pdf",
    "import.archive",
    "input.validation",
    "service.remote",
    "record.not_found",
    "setup.required",
    "storage.unsafe_path",
    "platform.unsupported",
];
const FILE_NAMES: [&str; MAX_FILES] = ["events.jsonl", "events.1.jsonl", "events.2.jsonl"];
static ACTIVE_LOG: OnceLock<Mutex<Option<DiagnosticLog>>> = OnceLock::new();

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum DiagnosticArea {
    App,
    Command,
    Navigation,
    Sync,
    Draft,
    Error,
    Export,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum DiagnosticPhase {
    Start,
    Success,
    Failure,
    Info,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct DiagnosticEvent {
    id: String,
    session_id: String,
    timestamp: String,
    area: DiagnosticArea,
    operation: String,
    phase: DiagnosticPhase,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    duration_ms: Option<u64>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    error_code: Option<String>,
}

// Application metadata is generated by the native build, never accepted from
// an IPC payload. Explicit nesting also avoids flatten/deny_unknown_fields.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
struct DiagnosticRecord {
    event: DiagnosticEvent,
    app_version: String,
    platform: String,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DiagnosticsSummary {
    session_id: String,
    app_version: String,
    platform: String,
    event_count: usize,
    file_count: usize,
    size_bytes: u64,
    max_file_bytes: u64,
    max_files: usize,
    first_event_at: Option<String>,
    last_event_at: Option<String>,
    last_incident: Option<DiagnosticEvent>,
}

#[derive(Clone)]
pub struct DiagnosticLog(Arc<LogInner>);

/// Closed startup phases: callers cannot supply paths or exception text.
#[derive(Clone, Copy)]
pub(crate) enum StartupOperation {
    Updater,
    LocalStore,
}

struct LogInner {
    data_dir: PathBuf,
    directory: PathBuf,
    exports_dir: PathBuf,
    session_id: String,
    app_version: String,
    platform: String,
    max_file_bytes: u64,
    operation_lock: Mutex<()>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
enum DiagnosticError {
    #[error("Les informations du journal technique sont invalides.")]
    InvalidEvent,
    #[error("Le journal technique accepte au maximum 100 évènements à la fois.")]
    BatchTooLarge,
    #[error("Le journal technique est momentanément indisponible.")]
    StorageUnavailable,
}

fn storage_error<T>(_: T) -> DiagnosticError {
    DiagnosticError::StorageUnavailable
}

fn valid_slug(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= MAX_SLUG_BYTES
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'.' | b'-'))
}

impl DiagnosticEvent {
    fn validate(&self) -> Result<(), DiagnosticError> {
        if self.id.len() != 36
            || self.session_id.len() != 36
            || Uuid::parse_str(&self.id).is_err()
            || Uuid::parse_str(&self.session_id).is_err()
            || self.timestamp.len() > 40
            || DateTime::parse_from_rfc3339(&self.timestamp).is_err()
            || !valid_slug(&self.operation)
            || self
                .duration_ms
                .is_some_and(|value| value > MAX_DURATION_MS)
            || self
                .error_code
                .as_deref()
                .is_some_and(|code| !ERROR_CODES.contains(&code))
        {
            return Err(DiagnosticError::InvalidEvent);
        }
        Ok(())
    }

    fn native(
        session_id: &str,
        operation: &str,
        phase: DiagnosticPhase,
        code: Option<&str>,
    ) -> Self {
        Self {
            id: Uuid::new_v4().to_string(),
            session_id: session_id.into(),
            timestamp: Utc::now().to_rfc3339_opts(SecondsFormat::Millis, true),
            area: if code.is_some() {
                DiagnosticArea::Command
            } else {
                DiagnosticArea::App
            },
            operation: operation.into(),
            phase,
            duration_ms: None,
            error_code: code.map(str::to_owned),
        }
    }
}

/// Initialization is deliberately best effort: an unwritable diagnostic folder
/// must never stop a company from opening. Commands report a fixed error later.
pub fn initialize(data_dir: &Path) -> DiagnosticLog {
    let log = DiagnosticLog::new(data_dir, MAX_FILE_BYTES);
    if let Ok(mut active) = ACTIVE_LOG.get_or_init(|| Mutex::new(None)).lock() {
        *active = Some(log.clone());
    }
    let _ = log.append(&[DiagnosticEvent::native(
        &log.0.session_id,
        "app.start",
        DiagnosticPhase::Info,
        None,
    )]);
    log
}

impl DiagnosticLog {
    fn new(data_dir: &Path, max_file_bytes: u64) -> Self {
        Self(Arc::new(LogInner {
            data_dir: data_dir.to_owned(),
            directory: data_dir.join("diagnostics"),
            exports_dir: data_dir.join("exports"),
            session_id: Uuid::new_v4().to_string(),
            app_version: env!("CARGO_PKG_VERSION").into(),
            platform: std::env::consts::OS.into(),
            max_file_bytes,
            operation_lock: Mutex::new(()),
        }))
    }

    fn ensure_directory(&self, directory: &Path) -> Result<(), DiagnosticError> {
        // The chosen profile root has already been created. A fixed child path
        // must not be redirected by a symbolic link into another directory.
        match fs::symlink_metadata(directory) {
            Ok(metadata) if metadata.file_type().is_symlink() || !metadata.is_dir() => {
                return Err(DiagnosticError::StorageUnavailable);
            }
            Ok(_) => {}
            Err(error) if error.kind() == ErrorKind::NotFound => {
                fs::create_dir_all(directory).map_err(storage_error)?;
            }
            Err(error) => return Err(storage_error(error)),
        }
        let root = self.0.data_dir.canonicalize().map_err(storage_error)?;
        let canonical = directory.canonicalize().map_err(storage_error)?;
        if canonical == root || !canonical.starts_with(&root) {
            return Err(DiagnosticError::StorageUnavailable);
        }
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(directory, fs::Permissions::from_mode(0o700))
                .map_err(storage_error)?;
        }
        Ok(())
    }

    fn file_size(&self, path: &Path) -> Result<Option<u64>, DiagnosticError> {
        match fs::symlink_metadata(path) {
            Ok(metadata) if metadata.file_type().is_symlink() || !metadata.is_file() => {
                Err(DiagnosticError::StorageUnavailable)
            }
            Ok(metadata) if metadata.len() > self.0.max_file_bytes => {
                Err(DiagnosticError::StorageUnavailable)
            }
            Ok(metadata) => Ok(Some(metadata.len())),
            Err(error) if error.kind() == ErrorKind::NotFound => Ok(None),
            Err(error) => Err(storage_error(error)),
        }
    }

    fn rotate(&self) -> Result<(), DiagnosticError> {
        let oldest = self.0.directory.join(FILE_NAMES[2]);
        if self.file_size(&oldest)?.is_some() {
            fs::remove_file(&oldest).map_err(storage_error)?;
        }
        for index in (0..MAX_FILES - 1).rev() {
            let source = self.0.directory.join(FILE_NAMES[index]);
            if self.file_size(&source)?.is_some() {
                fs::rename(source, self.0.directory.join(FILE_NAMES[index + 1]))
                    .map_err(storage_error)?;
            }
        }
        Ok(())
    }

    fn append(&self, events: &[DiagnosticEvent]) -> Result<(), DiagnosticError> {
        if events.len() > MAX_BATCH_EVENTS {
            return Err(DiagnosticError::BatchTooLarge);
        }
        // Validate the complete batch before any event can reach the journal.
        for event in events {
            event.validate()?;
        }
        if events.is_empty() {
            return Ok(());
        }
        let lines = events
            .iter()
            .map(|event| {
                let record = DiagnosticRecord {
                    event: event.clone(),
                    app_version: self.0.app_version.clone(),
                    platform: self.0.platform.clone(),
                };
                let mut line = serde_json::to_vec(&record).map_err(storage_error)?;
                line.push(b'\n');
                if line.len() as u64 > self.0.max_file_bytes {
                    return Err(DiagnosticError::InvalidEvent);
                }
                Ok(line)
            })
            .collect::<Result<Vec<_>, DiagnosticError>>()?;
        let _guard = self.0.operation_lock.lock().map_err(storage_error)?;
        self.ensure_directory(&self.0.directory)?;
        let current = self.0.directory.join(FILE_NAMES[0]);
        let mut size = self.file_size(&current)?.unwrap_or(0);
        let mut open_file: Option<fs::File> = None;
        for line in lines {
            if size + line.len() as u64 > self.0.max_file_bytes {
                // Windows cannot rename an open file. Close before rotation,
                // otherwise reuse the same handle for the complete batch.
                if let Some(mut file) = open_file.take() {
                    file.flush().map_err(storage_error)?;
                }
                self.rotate()?;
                size = 0;
            }
            if open_file.is_none() {
                let mut options = OpenOptions::new();
                options.create(true).append(true);
                #[cfg(unix)]
                {
                    use std::os::unix::fs::OpenOptionsExt;
                    options.mode(0o600);
                }
                open_file = Some(options.open(&current).map_err(storage_error)?);
            }
            open_file
                .as_mut()
                .ok_or(DiagnosticError::StorageUnavailable)?
                .write_all(&line)
                .map_err(storage_error)?;
            size += line.len() as u64;
        }
        if let Some(mut file) = open_file {
            file.flush().map_err(storage_error)?;
        }
        Ok(())
    }

    fn records(&self) -> Result<(Vec<DiagnosticRecord>, usize, u64), DiagnosticError> {
        self.ensure_directory(&self.0.directory)?;
        let mut records = Vec::new();
        let mut files = 0;
        let mut bytes = 0;
        for name in FILE_NAMES.iter().rev() {
            let path = self.0.directory.join(name);
            if let Some(size) = self.file_size(&path)? {
                files += 1;
                bytes += size;
                let mut text = String::new();
                fs::File::open(path)
                    .map_err(storage_error)?
                    .take(self.0.max_file_bytes + 1)
                    .read_to_string(&mut text)
                    .map_err(storage_error)?;
                if text.len() as u64 > self.0.max_file_bytes {
                    return Err(DiagnosticError::StorageUnavailable);
                }
                for line in text.lines() {
                    // Partial writes or manually altered files never turn
                    // into arbitrary data in an export or an error message.
                    if let Ok(record) = serde_json::from_str::<DiagnosticRecord>(line) {
                        if record.event.validate().is_ok()
                            && !record.app_version.is_empty()
                            && record.app_version.len() <= 30
                            && record
                                .app_version
                                .bytes()
                                .all(|byte| byte.is_ascii_digit() || byte == b'.')
                            && ["windows", "macos", "linux", "android", "ios"]
                                .contains(&record.platform.as_str())
                        {
                            records.push(record);
                        }
                    }
                }
            }
        }
        Ok((records, files, bytes))
    }

    fn summary(&self) -> Result<DiagnosticsSummary, DiagnosticError> {
        let _guard = self.0.operation_lock.lock().map_err(storage_error)?;
        let (records, file_count, size_bytes) = self.records()?;
        let mut first_event: Option<(DateTime<chrono::FixedOffset>, usize)> = None;
        let mut last_event: Option<(DateTime<chrono::FixedOffset>, usize)> = None;
        let mut last_failure: Option<(DateTime<chrono::FixedOffset>, usize)> = None;
        for (index, record) in records.iter().enumerate() {
            // A frontend batch can arrive after a newer native event. Compare
            // real instants, retaining the original timestamp/reference. For
            // equal instants the first/last physical record is deterministic.
            let timestamp = DateTime::parse_from_rfc3339(&record.event.timestamp)
                .map_err(|_| DiagnosticError::InvalidEvent)?;
            let key = (timestamp, index);
            if first_event.as_ref().is_none_or(|current| &key < current) {
                first_event = Some(key.clone());
            }
            if last_event.as_ref().is_none_or(|current| &key > current) {
                last_event = Some(key.clone());
            }
            if record.event.phase == DiagnosticPhase::Failure
                && last_failure.as_ref().is_none_or(|current| &key > current)
            {
                last_failure = Some(key);
            }
        }
        let first_event_at = first_event.map(|(_, index)| records[index].event.timestamp.clone());
        let last_event_at = last_event.map(|(_, index)| records[index].event.timestamp.clone());
        let last_incident = last_failure.map(|(_, index)| records[index].event.clone());
        Ok(DiagnosticsSummary {
            session_id: self.0.session_id.clone(),
            app_version: self.0.app_version.clone(),
            platform: self.0.platform.clone(),
            event_count: records.len(),
            file_count,
            size_bytes,
            max_file_bytes: self.0.max_file_bytes,
            max_files: MAX_FILES,
            first_event_at,
            last_event_at,
            last_incident,
        })
    }

    fn export(&self) -> Result<PathBuf, DiagnosticError> {
        let _guard = self.0.operation_lock.lock().map_err(storage_error)?;
        let (records, _, _) = self.records()?;
        self.ensure_directory(&self.0.exports_dir)?;
        let directory = self
            .0
            .exports_dir
            .join(format!("diagnostics-{}", Uuid::new_v4()));
        self.ensure_directory(&directory)?;
        let path = directory.join("Zentra-diagnostics.jsonl");
        let mut options = OpenOptions::new();
        options.create_new(true).write(true);
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt;
            options.mode(0o600);
        }
        let mut file = options.open(&path).map_err(storage_error)?;
        for record in records {
            serde_json::to_writer(&mut file, &record).map_err(storage_error)?;
            file.write_all(b"\n").map_err(storage_error)?;
        }
        file.flush().map_err(storage_error)?;
        Ok(path)
    }

    fn clear(&self) -> Result<(), DiagnosticError> {
        let _guard = self.0.operation_lock.lock().map_err(storage_error)?;
        self.ensure_directory(&self.0.directory)?;
        for name in FILE_NAMES {
            let path = self.0.directory.join(name);
            // Clearing must also recover a journal altered beyond its byte
            // limit. Fixed regular files may be removed without reading them.
            match fs::symlink_metadata(&path) {
                Ok(metadata) if metadata.file_type().is_symlink() || !metadata.is_file() => {
                    return Err(DiagnosticError::StorageUnavailable);
                }
                Ok(_) => fs::remove_file(path).map_err(storage_error)?,
                Err(error) if error.kind() == ErrorKind::NotFound => {}
                Err(error) => return Err(storage_error(error)),
            }
        }
        Ok(())
    }

    fn append_native_error(&self, error: &AppError) {
        self.append_native_failure(DiagnosticArea::Command, "command.native", error);
    }

    pub(crate) fn record_startup_failure(&self, operation: StartupOperation) {
        let (operation, code) = match operation {
            StartupOperation::Updater => ("app.updater.initialize", "INTERNAL"),
            StartupOperation::LocalStore => ("app.local_store.initialize", "STORAGE"),
        };
        let mut event = DiagnosticEvent::native(
            &self.0.session_id,
            operation,
            DiagnosticPhase::Failure,
            Some(code),
        );
        event.area = DiagnosticArea::App;
        // The original startup error is never replaced by a journal failure.
        let _ = self.append(&[event]);
    }

    fn append_project_exchange_failure(&self, error: &AppError) {
        self.append_native_failure(DiagnosticArea::Sync, "project.exchange", error);
    }

    fn append_attachment_cleanup_failure(&self, error: &AppError) {
        self.append_native_failure(DiagnosticArea::Command, "attachment.cleanup_failure", error);
    }

    fn append_native_failure(&self, area: DiagnosticArea, operation: &'static str, error: &AppError) {
        let mut event = DiagnosticEvent::native(
            &self.0.session_id,
            operation,
            DiagnosticPhase::Failure,
            Some(native_error_code(error)),
        );
        event.area = area;
        let _ = self.append(&[event]);
    }
}

fn native_error_code(error: &AppError) -> &'static str {
    match error {
        AppError::Database(_) => "storage.database",
        AppError::Io(_) => "storage.io",
        AppError::Json(_) => "input.json",
        AppError::Pdf(_) => "document.pdf",
        AppError::Archive(_) => "import.archive",
        AppError::Validation(_) => "input.validation",
        AppError::Remote(_) => "service.remote",
        AppError::NotFound(_) => "record.not_found",
        AppError::OnboardingRequired => "setup.required",
        AppError::UnsafePath(_) => "storage.unsafe_path",
        AppError::UnsupportedPlatform => "platform.unsupported",
    }
}

/// Called before formatting a native command error. Formatting remains unchanged
/// for users; only the static category above is permitted in the technical log.
pub(crate) fn record_native_error(error: &AppError) {
    let active = ACTIVE_LOG.get().and_then(|slot| slot.lock().ok()?.clone());
    if let Some(log) = active {
        log.append_native_error(error);
    }
}

pub(crate) struct PreparedNativeError {
    log: DiagnosticLog,
    event: DiagnosticEvent,
}

/// Capture the failure instant and a closed category before waiting for I/O.
/// This owned receipt deliberately retains no exception or business payload.
pub(crate) fn prepare_native_error(error: &AppError) -> Option<PreparedNativeError> {
    let log = ACTIVE_LOG.get().and_then(|slot| slot.lock().ok()?.clone())?;
    let event = DiagnosticEvent::native(
        &log.0.session_id,
        "command.native",
        DiagnosticPhase::Failure,
        Some(native_error_code(error)),
    );
    Some(PreparedNativeError { log, event })
}

pub(crate) async fn record_prepared_native_error(prepared: Option<PreparedNativeError>) {
    if let Some(PreparedNativeError { log, event }) = prepared {
        // Await the best-effort journal receipt, without detaching a task or
        // keeping the account lock while the log/export mutex is occupied.
        let _ = tauri::async_runtime::spawn_blocking(move || log.append(&[event])).await;
    }
}

/// A failed exchange remains an Ok status for the scheduler. Record only its
/// static technical category, never the status message or document metadata.
pub(crate) fn record_project_exchange_failure(error: &AppError) {
    let active = ACTIVE_LOG.get().and_then(|slot| slot.lock().ok()?.clone());
    if let Some(log) = active {
        log.append_project_exchange_failure(error);
    }
}

/// The document deletion is committed. Report physical cleanup separately,
/// without storing a path, attachment identity, file hash or raw error text.
pub(crate) fn record_attachment_cleanup_failure(error: &AppError) {
    let active = ACTIVE_LOG.get().and_then(|slot| slot.lock().ok()?.clone());
    if let Some(log) = active {
        log.append_attachment_cleanup_failure(error);
    }
}

#[tauri::command]
pub async fn append_diagnostic_events(
    state: State<'_, DiagnosticLog>,
    events: Vec<DiagnosticEvent>,
) -> Result<(), String> {
    let log = state.inner().clone();
    tauri::async_runtime::spawn_blocking(move || log.append(&events))
        .await
        .map_err(|_| DiagnosticError::StorageUnavailable.to_string())?
        .map_err(|error| error.to_string())
}

#[tauri::command]
pub async fn get_diagnostics_summary(
    state: State<'_, DiagnosticLog>,
) -> Result<DiagnosticsSummary, String> {
    let log = state.inner().clone();
    tauri::async_runtime::spawn_blocking(move || log.summary())
        .await
        .map_err(|_| DiagnosticError::StorageUnavailable.to_string())?
        .map_err(|error| error.to_string())
}

#[tauri::command]
pub async fn export_diagnostics(state: State<'_, DiagnosticLog>) -> Result<String, String> {
    let log = state.inner().clone();
    tauri::async_runtime::spawn_blocking(move || log.export())
        .await
        .map_err(|_| DiagnosticError::StorageUnavailable.to_string())?
        .map(|path| path.to_string_lossy().into_owned())
        .map_err(|error| error.to_string())
}

#[tauri::command]
pub async fn clear_diagnostics(state: State<'_, DiagnosticLog>) -> Result<(), String> {
    let log = state.inner().clone();
    tauri::async_runtime::spawn_blocking(move || log.clear())
        .await
        .map_err(|_| DiagnosticError::StorageUnavailable.to_string())?
        .map_err(|error| error.to_string())
}

#[derive(Debug, PartialEq, Eq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct FormDraftIdentity {
    member_id: Option<String>,
}

fn draft_identity(
    connection: &Connection,
    organization: Option<&str>,
    role: Option<&str>,
) -> AppResult<FormDraftIdentity> {
    let none = || FormDraftIdentity { member_id: None };
    let Some(organization) = organization else {
        return Ok(none());
    };
    let has_identity: bool = connection.query_row(
        "SELECT EXISTS(SELECT 1 FROM sqlite_master WHERE type='table' AND name='company_local_identity')", [], |row| row.get(0),
    )?;
    if !has_identity {
        return Ok(none());
    }
    let identity: Option<(String, String, String)> = connection
        .query_row(
            "SELECT organization_id,user_id,role FROM company_local_identity WHERE id=1",
            [],
            |row| Ok((row.get(0)?, row.get(1)?, row.get(2)?)),
        )
        .optional()?;
    let Some((current_organization, user_id, current_role)) = identity else {
        return Ok(none());
    };
    if current_organization != organization || role != Some(current_role.as_str()) {
        return Ok(none());
    }
    Ok(FormDraftIdentity {
        member_id: Uuid::parse_str(&user_id).ok().map(|id| id.to_string()),
    })
}

/// A local account/workspace identity, never a name, email or session token.
/// Reading the protected session is local; no extra membership HTTP round-trip.
#[tauri::command]
pub async fn get_form_draft_identity(
    state: State<'_, LocalStore>,
) -> Result<FormDraftIdentity, String> {
    let store = state.inner().clone();
    let _account_guard = store.account_protected_cache.operation_lock.lock().await;
    let session = crate::account_cloud::project_sync_session(&store)
        .await
        .map_err(command_error)?;
    let _guard = store.lock().map_err(command_error)?;
    let connection = store.connect().map_err(command_error)?;
    draft_identity(
        &connection,
        session.as_ref().map(|value| value.organization_id.as_str()),
        session.as_ref().map(|value| value.role.as_str()),
    )
    .map_err(command_error)
}

#[cfg(test)]
#[path = "startup_diagnostics_tests.rs"]
mod startup_diagnostics_tests;

#[cfg(test)]
#[path = "diagnostics_async_error_tests.rs"]
mod async_error_tests;

#[cfg(test)]
#[path = "diagnostics_summary_tests.rs"]
mod summary_tests;

#[cfg(test)]
mod tests {
    use super::*;
    use std::{collections::HashSet, thread};

    fn fixture(limit: u64) -> (tempfile::TempDir, DiagnosticLog) {
        let temporary = tempfile::tempdir().unwrap();
        let log = DiagnosticLog::new(temporary.path(), limit);
        (temporary, log)
    }

    fn event(operation: &str) -> DiagnosticEvent {
        DiagnosticEvent::native(
            &Uuid::new_v4().to_string(),
            operation,
            DiagnosticPhase::Success,
            None,
        )
    }

    #[test]
    fn input_has_only_known_fields_and_enum_values() {
        let value = serde_json::to_value(event("save.invoice")).unwrap();
        for (field, secret) in [
            ("message", "raw exception"),
            ("payload", "document contents"),
            ("password", "private password"),
            ("email", "private@example.ch"),
        ] {
            let mut invalid = value.clone();
            invalid[field] = secret.into();
            assert!(serde_json::from_value::<DiagnosticEvent>(invalid).is_err());
        }
        for field in ["area", "phase"] {
            let mut invalid = value.clone();
            invalid[field] = "unknown".into();
            assert!(serde_json::from_value::<DiagnosticEvent>(invalid).is_err());
        }
    }

    #[test]
    fn validates_ids_dates_slug_and_duration_boundaries() {
        let valid = event("invoice.save_2-1");
        assert!(valid.validate().is_ok());
        let invalid_cases: [fn(&mut DiagnosticEvent); 8] = [
            |value: &mut DiagnosticEvent| value.id = "not-a-uuid".into(),
            |value: &mut DiagnosticEvent| value.session_id = "private@example.ch".into(),
            |value: &mut DiagnosticEvent| value.timestamp = "2026-02-30T12:00:00Z".into(),
            |value: &mut DiagnosticEvent| value.operation = "mail@example.ch".into(),
            |value: &mut DiagnosticEvent| value.operation = "invoice text\nsecret".into(),
            |value: &mut DiagnosticEvent| value.operation = "a".repeat(81),
            |value: &mut DiagnosticEvent| value.error_code = Some("error: private text".into()),
            |value: &mut DiagnosticEvent| value.duration_ms = Some(MAX_DURATION_MS + 1),
        ];
        for mutate in invalid_cases {
            let mut invalid = valid.clone();
            mutate(&mut invalid);
            assert_eq!(invalid.validate(), Err(DiagnosticError::InvalidEvent));
        }
        let mut boundaries = valid;
        boundaries.duration_ms = Some(MAX_DURATION_MS);
        boundaries.operation = "a".repeat(80);
        boundaries.error_code = Some("service.remote".into());
        assert!(boundaries.validate().is_ok());
    }

    #[test]
    fn error_codes_are_a_closed_allowlist_not_arbitrary_secret_slugs() {
        for code in ERROR_CODES {
            let mut value = event("command.execute");
            value.error_code = Some((*code).into());
            assert!(value.validate().is_ok());
        }
        let (_temporary, log) = fixture(MAX_FILE_BYTES);
        for code in ["sk_live_private_key", "private-secret-token", "unknown"] {
            let mut value = event("command.execute");
            value.error_code = Some(code.into());
            assert_eq!(log.append(&[value]), Err(DiagnosticError::InvalidEvent));
        }
        assert_eq!(log.summary().unwrap().event_count, 0);
    }

    #[test]
    fn invalid_batches_never_partially_append() {
        let (_temporary, log) = fixture(MAX_FILE_BYTES);
        let valid = event("invoice.save");
        let mut invalid = event("invoice.save");
        invalid.operation = "private body text".into();
        assert_eq!(
            log.append(&[valid.clone(), invalid]),
            Err(DiagnosticError::InvalidEvent)
        );
        assert_eq!(log.summary().unwrap().event_count, 0);
        assert_eq!(
            log.append(&vec![valid; MAX_BATCH_EVENTS + 1]),
            Err(DiagnosticError::BatchTooLarge)
        );
        assert_eq!(log.summary().unwrap().event_count, 0);
    }

    #[test]
    fn rotates_with_three_bounded_files_and_keeps_latest_events() {
        let (_temporary, log) = fixture(700);
        let mut ids = Vec::new();
        for _ in 0..20 {
            let value = event("invoice.save");
            ids.push(value.id.clone());
            log.append(&[value]).unwrap();
        }
        let summary = log.summary().unwrap();
        assert_eq!(summary.file_count, MAX_FILES);
        assert!(summary.size_bytes <= 700 * MAX_FILES as u64);
        assert!(summary.event_count < ids.len());
        let (records, _, _) = log.records().unwrap();
        assert_eq!(records.last().unwrap().event.id, *ids.last().unwrap());
        for name in FILE_NAMES {
            assert!(fs::metadata(log.0.directory.join(name)).unwrap().len() <= 700);
        }
    }

    #[test]
    fn a_single_batch_can_rotate_without_retaining_an_open_windows_handle() {
        let (_temporary, log) = fixture(700);
        let values: Vec<_> = (0..20).map(|_| event("sync.apply")).collect();
        let last = values.last().unwrap().id.clone();
        log.append(&values).unwrap();
        let (records, files, bytes) = log.records().unwrap();
        assert_eq!(files, MAX_FILES);
        assert!(bytes <= 700 * MAX_FILES as u64);
        assert_eq!(records.last().unwrap().event.id, last);
    }

    #[test]
    fn startup_record_uses_native_build_metadata_and_a_random_session() {
        let (_temporary, log) = fixture(MAX_FILE_BYTES);
        log.append(&[DiagnosticEvent::native(
            &log.0.session_id,
            "app.start",
            DiagnosticPhase::Info,
            None,
        )])
        .unwrap();
        let (records, _, _) = log.records().unwrap();
        assert_eq!(records[0].event.area, DiagnosticArea::App);
        assert_eq!(records[0].app_version, env!("CARGO_PKG_VERSION"));
        assert_eq!(records[0].platform, std::env::consts::OS);
        assert_eq!(records[0].event.session_id, log.0.session_id);
        assert!(Uuid::parse_str(&log.0.session_id).is_ok());
        assert!(log.summary().unwrap().last_incident.is_none());
    }

    #[test]
    fn concurrent_writes_produce_complete_unique_records() {
        let (_temporary, log) = fixture(MAX_FILE_BYTES);
        let threads: Vec<_> = (0..8)
            .map(|_| {
                let log = log.clone();
                thread::spawn(move || {
                    for _ in 0..40 {
                        log.append(&[event("sync.apply")]).unwrap();
                    }
                })
            })
            .collect();
        for thread in threads {
            thread.join().unwrap();
        }
        let (records, _, _) = log.records().unwrap();
        assert_eq!(records.len(), 320);
        assert_eq!(
            records
                .iter()
                .map(|record| &record.event.id)
                .collect::<HashSet<_>>()
                .len(),
            320
        );
    }

    #[test]
    fn exports_only_sanitized_records_in_app_exports() {
        let (_temporary, log) = fixture(MAX_FILE_BYTES);
        log.append(&[event("invoice.save")]).unwrap();
        let mut file = OpenOptions::new()
            .append(true)
            .open(log.0.directory.join(FILE_NAMES[0]))
            .unwrap();
        writeln!(
            file,
            "{{\"password\":\"private-secret\",\"message\":\"private invoice\"}}"
        )
        .unwrap();
        let exported = log.export().unwrap();
        assert!(exported.starts_with(&log.0.exports_dir));
        assert_eq!(exported.extension().unwrap(), "jsonl");
        let text = fs::read_to_string(exported).unwrap();
        assert_eq!(text.lines().count(), 1);
        assert!(!text.contains("private-secret"));
        assert!(!text.contains("private invoice"));
        assert!(serde_json::from_str::<DiagnosticRecord>(text.trim()).is_ok());
    }

    #[test]
    fn native_errors_never_log_exception_text_or_paths() {
        let (_temporary, log) = fixture(MAX_FILE_BYTES);
        let errors = [
            AppError::Remote("Bearer private-secret-token mail@example.ch".into()),
            AppError::Validation("Invoice body and private password".into()),
            AppError::UnsafePath(PathBuf::from("/private/company-document.pdf")),
        ];
        for error in &errors {
            log.append_native_error(error);
        }
        let text = fs::read_to_string(log.export().unwrap()).unwrap();
        for secret in [
            "Bearer",
            "private-secret-token",
            "mail@example.ch",
            "Invoice body",
            "private password",
            "company-document.pdf",
        ] {
            assert!(!text.contains(secret));
        }
        let summary = log.summary().unwrap();
        assert_eq!(summary.event_count, 3);
        assert_eq!(
            summary.last_incident.unwrap().error_code.as_deref(),
            Some("storage.unsafe_path")
        );
    }

    #[test]
    fn committed_attachment_cleanup_failure_logs_only_static_operation_and_category() {
        let (_temporary, log) = fixture(MAX_FILE_BYTES);
        let error = AppError::Io(std::io::Error::new(
            std::io::ErrorKind::PermissionDenied,
            "private/company-invoice.pdf sha256=private-hash id=private-attachment",
        ));
        log.append_attachment_cleanup_failure(&error);
        let (records, _, _) = log.records().unwrap();
        assert_eq!(records.len(), 1);
        assert_eq!(records[0].event.operation, "attachment.cleanup_failure");
        assert_eq!(records[0].event.phase, DiagnosticPhase::Failure);
        assert_eq!(records[0].event.error_code.as_deref(), Some("storage.io"));
        let text = fs::read_to_string(log.export().unwrap()).unwrap();
        for secret in [
            "company-invoice.pdf",
            "private-hash",
            "private-attachment",
            &error.to_string(),
        ] {
            assert!(!text.contains(secret));
        }
        // An unwritable diagnostic path remains best effort and cannot turn
        // this already-committed business outcome into a new command failure.
        log.clear().unwrap();
        fs::remove_dir(&log.0.directory).unwrap();
        fs::write(&log.0.directory, b"synthetic blocked journal").unwrap();
        log.append_attachment_cleanup_failure(&error);
    }

    #[test]
    fn failed_project_exchange_keeps_status_contract_and_logs_only_its_category() {
        let (_temporary, log) = fixture(MAX_FILE_BYTES);
        let connection = Connection::open_in_memory().unwrap();
        let database_error = connection
            .query_row("SELECT * FROM \"private-secret-token\"", [], |_| Ok(()))
            .unwrap_err();
        let error = AppError::Database(database_error);
        let expected_message = error.to_string();
        let status = crate::project_sync::project_exchange_status(
            serde_json::json!({"pending":2,"documents":[],"syncing":true}),
            Err(error),
            |error| log.append_project_exchange_failure(error),
        );
        assert_eq!(status["error"], expected_message);
        assert_eq!(status["changed"], true);
        assert_eq!(status["syncing"], false);
        assert_eq!(status["pending"], 2);
        let (records, _, _) = log.records().unwrap();
        assert_eq!(records.len(), 1);
        let event = &records[0].event;
        assert_eq!(event.area, DiagnosticArea::Sync);
        assert_eq!(event.operation, "project.exchange");
        assert_eq!(event.phase, DiagnosticPhase::Failure);
        assert_eq!(event.error_code.as_deref(), Some("storage.database"));
        let text = fs::read_to_string(log.export().unwrap()).unwrap();
        assert!(!text.contains("private-secret-token"));
        assert!(!text.contains(&expected_message));
    }

    #[test]
    fn successful_project_exchange_does_not_report_a_failure() {
        let (_temporary, log) = fixture(MAX_FILE_BYTES);
        let status = crate::project_sync::project_exchange_status(
            serde_json::json!({"pending":0,"documents":[],"syncing":true}),
            Ok((true, false)),
            |error| log.append_project_exchange_failure(error),
        );
        assert_eq!(status["connected"], true);
        assert_eq!(status["changed"], false);
        assert_eq!(status["syncing"], false);
        assert!(status.get("error").is_none());
        assert_eq!(log.summary().unwrap().event_count, 0);
    }

    #[test]
    fn clear_removes_only_the_three_log_files() {
        let (_temporary, log) = fixture(700);
        for _ in 0..8 {
            log.append(&[event("invoice.save")]).unwrap();
        }
        let unrelated = log.0.data_dir.join("company-document.txt");
        fs::write(&unrelated, "preserve").unwrap();
        let exported = log.export().unwrap();
        log.clear().unwrap();
        assert_eq!(log.summary().unwrap().event_count, 0);
        assert_eq!(log.summary().unwrap().file_count, 0);
        assert!(exported.is_file());
        assert_eq!(fs::read_to_string(unrelated).unwrap(), "preserve");
    }

    #[test]
    fn oversize_or_nonregular_files_are_rejected_without_leaking_paths() {
        let (_temporary, log) = fixture(700);
        log.ensure_directory(&log.0.directory).unwrap();
        let path = log.0.directory.join(FILE_NAMES[0]);
        fs::write(&path, vec![b'x'; 701]).unwrap();
        let error = log.summary().unwrap_err();
        assert_eq!(error, DiagnosticError::StorageUnavailable);
        assert!(!error
            .to_string()
            .contains(log.0.directory.to_str().unwrap()));
        log.clear().unwrap();
        assert_eq!(log.summary().unwrap().event_count, 0);
        fs::create_dir(&path).unwrap();
        assert_eq!(
            log.append(&[event("app.open")]),
            Err(DiagnosticError::StorageUnavailable)
        );
    }

    #[cfg(unix)]
    #[test]
    fn symbolic_links_are_rejected_and_files_are_private() {
        use std::os::unix::fs::{symlink, PermissionsExt};
        let (_temporary, log) = fixture(MAX_FILE_BYTES);
        log.append(&[event("app.open")]).unwrap();
        assert_eq!(
            fs::metadata(&log.0.directory).unwrap().permissions().mode() & 0o777,
            0o700
        );
        let current = log.0.directory.join(FILE_NAMES[0]);
        assert_eq!(
            fs::metadata(&current).unwrap().permissions().mode() & 0o777,
            0o600
        );
        let outside = tempfile::tempdir().unwrap();
        let protected = outside.path().join("protected.txt");
        fs::write(&protected, "preserve").unwrap();
        fs::remove_file(&current).unwrap();
        symlink(&protected, &current).unwrap();
        assert_eq!(
            log.append(&[event("app.open")]),
            Err(DiagnosticError::StorageUnavailable)
        );
        assert_eq!(fs::read_to_string(protected).unwrap(), "preserve");
    }

    fn identity_fixture() -> Connection {
        let connection = Connection::open_in_memory().unwrap();
        connection.execute_batch("CREATE TABLE company_local_identity(id INTEGER PRIMARY KEY,organization_id TEXT NOT NULL,user_id TEXT NOT NULL,display_name TEXT NOT NULL,role TEXT NOT NULL);").unwrap();
        connection
    }

    #[test]
    fn draft_identity_requires_current_org_role_and_valid_member_uuid() {
        let connection = identity_fixture();
        let member = Uuid::new_v4().to_string();
        connection
            .execute(
                "INSERT INTO company_local_identity VALUES(1,'org-a',?,'Private User','owner')",
                [&member],
            )
            .unwrap();
        assert_eq!(
            draft_identity(&connection, Some("org-a"), Some("owner"))
                .unwrap()
                .member_id,
            Some(member)
        );
        for (organization, role) in [
            (Some("org-b"), Some("owner")),
            (None, None),
            (Some("org-a"), Some("viewer")),
        ] {
            assert_eq!(
                draft_identity(&connection, organization, role)
                    .unwrap()
                    .member_id,
                None
            );
        }
        connection
            .execute(
                "UPDATE company_local_identity SET user_id='private@example.ch'",
                [],
            )
            .unwrap();
        assert_eq!(
            draft_identity(&connection, Some("org-a"), Some("owner"))
                .unwrap()
                .member_id,
            None
        );
    }

    #[test]
    fn draft_identity_missing_or_cleared_table_is_empty_and_has_no_personal_fields() {
        let connection = Connection::open_in_memory().unwrap();
        assert_eq!(
            draft_identity(&connection, Some("org-a"), Some("owner"))
                .unwrap()
                .member_id,
            None
        );
        let connection = identity_fixture();
        assert_eq!(
            draft_identity(&connection, Some("org-a"), Some("owner"))
                .unwrap()
                .member_id,
            None
        );
        let serialized = serde_json::to_value(FormDraftIdentity {
            member_id: Some(Uuid::new_v4().to_string()),
        })
        .unwrap();
        assert_eq!(serialized.as_object().unwrap().len(), 1);
        assert!(serialized.get("memberId").is_some());
    }
}
