import { LegalPage, OperatorContact } from '@/components/legal-page';
export const metadata = {title:'Annexe de traitement des données',alternates:{canonical:'/sous-traitance'}};
export default function Page() {
  return <LegalPage title="Traitement des données d’entreprise" intro="Annexe aux conditions Zentra pour les informations confiées aux fonctions distantes." sections={[
    {id:'roles',title:'Parties et instructions',content:<><OperatorContact /><p>L’entreprise cliente reste responsable des données de ses clients, fournisseurs et salariés. Pour les opérations distantes demandées par cette entreprise, Zentra intervient comme sous-traitant. Les données du propre compte commercial Zentra relèvent de la politique de confidentialité.</p><p>Les instructions sont les fonctions choisies par une personne autorisée, les réglages de l’entreprise et les demandes écrites acceptées par le support. Zentra utilise les données confiées pour ces fonctions, sans les réutiliser pour la publicité ou l’entraînement d’un modèle distant. Une instruction paraissant contraire à la protection des données est signalée au client.</p></>},
    {id:'perimetre',title:'Données et opérations',content:<p>Selon les fonctions activées : coordonnées, identifiants de projet, photos, plans, documents commerciaux, informations salariales et pièces jointes. Les personnes concernées sont notamment les clients, fournisseurs et salariés. Les opérations comprennent réception, stockage, organisation, accès autorisé, synchronisation, sauvegarde, restitution et suppression. Le traitement dure pendant l’utilisation du service puis selon les instructions de restitution et les obligations applicables. N’importez pas de données sensibles inutiles à la fonction.</p>},
    {id:'mesures',title:'Confidentialité et protection',content:<p>Zentra limite les accès aux personnes et services qui en ont besoin et leur impose une confidentialité appropriée. Les protections comprennent les échanges HTTPS, les comptes individuels, les rôles, la séparation logique des entreprises, la révocation des appareils et les contrôles d’intégrité décrits sur la <a href="/security">page sécurité</a>. Le client protège ses terminaux et conserve des sauvegardes indépendantes. Aucun chiffrement de bout en bout, hébergement exclusivement suisse ou certification n’est promis par cette annexe.</p>},
    {id:'prestataires',title:'Prestataires et transferts',content:<><p>Le client autorise le recours aux prestataires nécessaires indiqués dans la <a href="/confidentialite#prestataires">liste des prestataires</a>, selon leur périmètre. Les obligations de protection doivent être répercutées dans les engagements applicables aux sous-traitants. Zentra reste responsable de ses propres obligations.</p><p>Avant l’ajout ou le remplacement matériel d’un sous-traitant, Zentra informe le client et permet une objection motivée par la protection des données. Les parties recherchent une solution ; à défaut, le client peut arrêter la fonction concernée et demander la restitution de ses données.</p><p>Un transfert à l’étranger nécessite un pays reconnu adéquat ou un autre mécanisme légal applicable, notamment des garanties contractuelles appropriées. L’inscription d’un fournisseur dans cette liste ne prouve pas à elle seule la conclusion de tels engagements. Les lieux, garanties et documents doivent être confirmés pour toute exigence particulière avant le transfert concerné.</p></>},
    {id:'assistance',title:'Droits et incidents',content:<p>Zentra aide le client, dans le périmètre des données accessibles au service, à répondre aux demandes d’accès, correction, restitution et suppression et aux évaluations nécessaires. En cas de violation constatée concernant les données confiées, Zentra informe le client sans retard indu, communique les éléments disponibles et coopère aux mesures correctives. Le client évalue les annonces requises aux personnes et autorités.</p>},
    {id:'fin',title:'Restitution et fin du service',content:<p>Le client exporte ses données et sauvegardes avant la fin du service. Il peut demander au support la restitution ou la suppression des copies hébergées. Zentra vérifie son habilitation et précise les données supprimées, les traces ou copies restantes et les motifs de conservation. Les archives soumises à une durée obligatoire ne sont pas supprimées avant son terme. Le client gère les copies présentes sur ses appareils et celles transmises à des tiers.</p>},
    {id:'controle',title:'Informations de contrôle',content:<p>Le client peut demander à info@zentraapp.ch les informations nécessaires à la vérification de cette annexe. Un contrôle complémentaire est organisé de manière proportionnée, en protégeant les autres clients et la sécurité des services. Les contraintes particulières de l’activité du client nécessitent une validation distincte.</p>},
  ]}/>;
}
