import assert from 'node:assert/strict';import {createRequire} from 'node:module';import {mkdir,writeFile} from 'node:fs/promises';
const {chromium}=createRequire(import.meta.url)(process.env.ZENTRA_PLAYWRIGHT_MODULE||'playwright');const browser=await chromium.launch({channel:'msedge',headless:true});const out='.qa/appearance164';await mkdir(out,{recursive:true});let page;const report=[];
try{for(const viewport of [{width:390,height:844},{width:1440,height:900}]){
page=await browser.newPage({viewport,hasTouch:viewport.width<900,colorScheme:'light'});page.setDefaultTimeout(10000);const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:5271/tests/touch-team-harness.html?view=appearance');await page.getByRole('button',{name:'Sombre',exact:true}).click();assert.equal(await page.locator('html').getAttribute('data-app-theme'),'dark');await page.reload();assert.equal(await page.locator('html').getAttribute('data-app-theme'),'dark');
await page.getByRole('button',{name:'Clair',exact:true}).click();assert.equal(await page.locator('html').getAttribute('data-app-theme'),'light');await page.getByRole('button',{name:'Automatique',exact:true}).click();await page.emulateMedia({colorScheme:'dark'});await page.waitForFunction(()=>document.documentElement.dataset.appTheme==='dark');assert.equal(await page.locator('html').getAttribute('data-app-theme'),'dark');await page.emulateMedia({colorScheme:'light'});await page.waitForFunction(()=>document.documentElement.dataset.appTheme==='light');await page.getByRole('button',{name:'Sombre',exact:true}).click();
await page.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));await page.screenshot({path:`${out}/${viewport.width}-appearance.png`});
await page.goto('http://127.0.0.1:5271/tests/mobile-harness.html?browsing=1&design=1&payroll=1');await page.getByRole('button',{name:'Fermer le guide automatique',exact:true}).click();
const nav=async name=>{await page.getByRole('button',{name:'Aller à un écran',exact:true}).click();await page.getByRole('searchbox',{name:'Rechercher un écran'}).fill(name);await page.locator('.navigation-palette__results button').filter({has:page.getByText(name,{exact:true})}).click();};
for(const name of ['Tableau de bord','Devis','Factures','Comptabilité','Équipe & salaires','Paramètres']){if(name!=='Tableau de bord')await nav(name);await page.waitForTimeout(500);await page.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));assert.equal(await page.locator('html').getAttribute('data-app-theme'),'dark');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));await page.screenshot({path:`${out}/${viewport.width}-${name}.png`});}
await page.goto('http://127.0.0.1:5271/tests/touch-team-harness.html?view=document');await page.locator('.document-preview__paper').waitFor();const paper=await page.locator('.document-preview__paper').evaluate(el=>({bg:getComputedStyle(el).backgroundColor,color:getComputedStyle(el).color}));assert.equal(paper.bg,'rgb(255, 255, 255)');assert.equal(paper.color,'rgb(21, 36, 28)');assert.equal(await page.locator('.document-preview__header').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(32, 37, 42)');await page.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));await page.screenshot({path:`${out}/${viewport.width}-document.png`});
await page.emulateMedia({media:'print'});assert.notEqual(await page.locator('.document-preview__header').evaluate(el=>getComputedStyle(el).backgroundColor),'rgb(32, 37, 42)','dark overrides screen-only');assert.deepEqual(errors,[]);report.push({viewport,persisted:true,systemChanges:true,printUnchanged:true,errors});await page.close();}
}catch(error){if(page){await page.evaluate(()=>Promise.all(document.getAnimations().filter(a=>a.effect?.getTiming().iterations!==Infinity).map(a=>a.finished.catch(()=>{}))));await page.screenshot({path:out+'/failure.png'});await writeFile(out+'/failure.json',JSON.stringify({error:String(error),text:await page.locator('body').innerText()}));}throw error;}finally{await writeFile(out+'/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();}
