import { createRequire } from 'node:module';
import { mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.ZENTRA_PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true, ...(process.platform === 'win32' ? { channel: 'msedge' } : {}) });
const report = [];
await mkdir('.qa/bank', { recursive: true });
try {
  for (const width of [320, 390, 768, 1024, 1440]) {
    const page = await browser.newPage({ viewport: { width, height: 900 } });
    page.on('pageerror', (error) => report.push({ width, error: error.message }));
    await page.emulateMedia({ reducedMotion: 'reduce' });
    await page.goto('http://127.0.0.1:5175/tests/mobile-harness.html?finance=1&bank=1', { waitUntil: 'domcontentloaded' });
    const tour = page.getByRole('button', { name: 'Ne plus afficher automatiquement', exact: true });
    if (await tour.isVisible()) await tour.click();
    await page.getByRole('button', { name: 'Aller à un écran', exact: true }).click();
    await page.getByRole('searchbox', { name: 'Rechercher un écran' }).fill('Banque');
    await page.locator('.navigation-palette__results button').filter({ has: page.getByText('Banque', { exact: true }) }).click();
    await page.locator('.navigation-palette').waitFor({ state: 'detached' });
    await page.evaluate(() => sessionStorage.setItem('qa-bank-fail-import-refresh','1'));
    await page.locator('.bank-hero').getByRole('button', { name: 'Importer un relevé XML', exact: true }).click();
    await page.getByText('Relevé importé localement', { exact: true }).waitFor();
    assert.equal(await page.evaluate(() => sessionStorage.getItem('qa-bank-import-automatic')), 'true');
    assert.match(await page.locator('.bank-feedback').textContent(), /1 facture\(s\) soldée\(s\).*1 paiement\(s\) partiel/);
    assert.match(await page.locator('.bank-feedback').textContent(), /Import enregistré ; actualisation incomplète/);
    assert.ok(await page.locator('.bank-hero button').isDisabled());
    await page.evaluate(() => ['qa-bank-fail-import-refresh','qa-bank-workspace-refresh-fail','qa-bank-refresh-fail'].forEach((key) => sessionStorage.removeItem(key)));
    await page.getByRole('button', { name: 'Actualiser les données', exact: true }).click();
    await page.getByText('Données actualisées', { exact: true }).waitFor();
    assert.equal(await page.evaluate(() => sessionStorage.getItem('qa-bank-import-attempts')), '1');
    assert.equal(await page.locator('.bank-movement').count(), 25);
    await page.getByRole('button', { name: /^Afficher les mouvements suivants/ }).click();
    assert.equal(await page.locator('.bank-movement').count(), 29);
    const search = page.getByRole('searchbox', { name: 'Rechercher un mouvement', exact: true });
    await search.fill('electricite du leman');
    assert.equal(await page.locator('.bank-movement').count(), 1);
    await search.fill('RF18 5390 0754 7034');
    assert.equal(await page.locator('.bank-movement').count(), 1);
    await search.fill('54,05');
    assert.equal(await page.locator('.bank-movement').count(), 1);
    await search.fill('référence introuvable');
    await page.getByText('Aucun résultat', { exact: true }).waitFor();
    await page.getByRole('button', { name: 'Effacer la recherche', exact: true }).click();
    assert.equal(await page.locator('.bank-movement').count(), 25);
    const client = page.locator('.bank-movement').filter({ hasText: 'Électricité du Léman' });
    const confirm = client.getByRole('button', { name: 'Confirmer l’encaissement', exact: true });
    assert.ok(await confirm.isDisabled());
    await client.locator('.bank-candidate-option').filter({ hasText: 'F-2026-3' }).click();
    assert.ok(await confirm.isEnabled());
    await client.getByRole('searchbox').fill('F-2026-4');
    assert.ok(await confirm.isDisabled(), 'a hidden candidate must not remain selected');
    await client.getByRole('searchbox').fill('');
    await client.locator('.bank-candidate-option').filter({ hasText: 'F-2026-3' }).click();
    await client.evaluate((element) => window.scrollTo(0, window.scrollY+element.getBoundingClientRect().top-95));
    await page.screenshot({ path: `.qa/bank/${width}-candidate.png` });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth<=innerWidth), `bank overflow ${width}`);
    assert.ok(await client.locator('.bank-movement__identity strong').evaluate((element) => parseFloat(getComputedStyle(element).fontSize)>=14), 'counterparty text must be readable');
    assert.ok(await client.locator('.bank-candidate-option__identity strong').first().evaluate((element) => parseFloat(getComputedStyle(element).fontSize)>=14), 'invoice references must be readable');
    page.once('dialog', (dialog) => dialog.dismiss());
    await confirm.click();
    assert.equal(await page.evaluate(() => sessionStorage.getItem('qa-bank-customer-attempts')), null);
    await page.evaluate(() => sessionStorage.setItem('qa-bank-reject','1'));
    page.once('dialog', (dialog) => dialog.accept());
    await confirm.click();
    await page.getByText('Période clôturée, paiement refusé.', { exact: true }).waitFor();
    await page.evaluate(() => { sessionStorage.removeItem('qa-bank-reject'); sessionStorage.setItem('qa-bank-fail-after-save','1'); });
    page.once('dialog', (dialog) => dialog.accept());
    await confirm.click();
    await page.getByText('Rapprochement confirmé', { exact: true }).waitFor();
    await page.getByText(/enregistré.*actualisation/i).waitFor();
    await page.screenshot({ path: `.qa/bank/${width}-saved-refresh-failed.png` });
    assert.ok(await confirm.isDisabled(), 'a committed payment must not be submitted again while the screen is stale');
    await page.evaluate(() => { sessionStorage.removeItem('qa-bank-refresh-fail'); sessionStorage.removeItem('qa-bank-fail-after-save'); });
    await page.getByRole('button', { name: 'Actualiser les données', exact: true }).click();
    await client.waitFor({ state: 'detached' });
    assert.equal(await page.evaluate(() => sessionStorage.getItem('qa-bank-customer-attempts')), '2');
    const supplier = page.locator('.bank-movement').filter({ hasText: 'Fournitures du Léman' });
    page.once('dialog', (dialog) => dialog.accept());
    await supplier.getByRole('button', { name: 'Confirmer le règlement', exact: true }).click();
    await page.getByText('Règlement fournisseur confirmé', { exact: true }).waitFor();
    assert.equal(await page.evaluate(() => sessionStorage.getItem('qa-bank-supplier-attempts')), '1');
    await page.getByRole('tab', { name: /^Rapprochés/ }).click();
    assert.equal(await page.locator('.bank-movement').count(), 4);
    await page.getByRole('tab', { name: /^En attente/ }).click();
    assert.equal(await page.locator('.bank-movement').count(), 1);
    assert.equal(await page.locator('.bank-movement button').count(), 0);
    await page.locator('.bank-hero').getByRole('button', { name: 'Importer un relevé XML', exact: true }).click();
    await page.getByText('Relevé déjà connu', { exact: true }).waitFor();
    await page.getByRole('tab', { name: /^Rapprochés/ }).click();
    assert.equal(await page.locator('.bank-movement').count(), 4);
    report.push({ width, journey: 'PASS automatic full and partial import, manual choice, cancel, refusal, committed payment with failed refresh and retry, supplier payment, pending and duplicate import' });
    await page.close();
  }
  assert.deepEqual(report.filter((item) => item.error), []);
} catch (error) {
  report.push({ fatal: error.stack }); process.exitCode = 1;
  const page = browser.contexts().flatMap((context) => context.pages()).at(-1);
  if (page) { await page.screenshot({ path: '.qa/bank/failure.png' }); await writeFile('.qa/bank/failure.html', await page.content()); await writeFile('.qa/bank/overflow.json', JSON.stringify(await page.evaluate(() => [...document.querySelectorAll('body *')].filter((element) => element.getBoundingClientRect().right > innerWidth+1).map((element) => ({ tag: element.tagName, class: element.className, text: element.textContent?.slice(0,70), right: element.getBoundingClientRect().right, width: element.getBoundingClientRect().width })).slice(-30)), null, 2)); }
}
finally { await writeFile('.qa/bank/report.json', JSON.stringify(report, null, 2)); console.log(JSON.stringify(report, null, 2)); await browser.close(); }
