import {desktopApi,type CloudAccountState} from '../src/bridge';
import type {Workspace} from '../src/types';
import {companyReceiveAllowed} from '../src/companySync';
const realRead=desktopApi.loadWorkspace,realCreate=desktopApi.createEntity;
export function installMailSettingsAuditFixture(workspace:Workspace,installIdentity:(w:Workspace)=>void){
 installIdentity(workspace);const identity=(window as any).__qaAppDraftIdentity,native=(window as any).__TAURI_INTERNALS__,previousInvoke=native.invoke,baseResolve=desktopApi.resolveConnectedCompany;
 let mode='current',holdNext=false,nextId=0,mailReads=0,foreignNext=false;let originSnapshot:Workspace|undefined;let releaseAck:(()=>void)|undefined;
 const held=new Map<number,{resolve:(v:any)=>void;reject:(e:Error)=>void;snapshot:any}>();
 const proof={saveCalls:0,accepted:0,clientWrites:0,saveAckPending:false,saveScopes:[] as string[],reads:[] as any[],choices:[] as string[],commands:[] as string[]};
 workspace.settings!.mailTemplates={quotes:{subject:'SYNTHETIC QUOTE A',body:'Bonjour {client}'},invoices:{subject:'SYNTHETIC INVOICE A',body:'Bonjour {client}'}};
 function raw(){const s=workspace.settings!,o=s.organization,b=s.billing;return {schema_version:43,work_notes_scope:workspace.workNotesScope,settings:{
 company_name:o.legalName,legal_form:o.legalForm,owner_name:o.contactName,email:o.email,phone:o.phone,address_line1:o.address.street,address_line2:'',postal_code:o.address.postalCode,city:o.address.city,canton:o.address.canton,country:o.address.country,uid_number:o.uidNumber,vat_number:o.vatNumber,vat_registered:o.vatRegistered,default_vat_bp:b.vatRatesBp[0]??0,iban:b.iban,bank_name:b.accountHolder,currency:'CHF',quote_prefix:b.quotePrefix,invoice_prefix:b.invoicePrefix,credit_note_prefix:b.creditNotePrefix,quote_start_number:b.nextQuoteNumber,invoice_start_number:b.nextInvoiceNumber,credit_note_start_number:b.nextCreditNoteNumber,payment_terms_days:b.paymentTermsDays,quote_validity_days:b.quoteValidityDays,default_hourly_rate_cents:0,logo_path:'',noga_section:s.business.nogaSection,noga_division:s.business.nogaDivision,activity_description:s.business.activityDescription,noga_detailed_code:s.business.nogaDetailedCode,
 extra_settings_json:JSON.stringify({mailTemplates:s.mailTemplates,mailSignature:{includeCompanyLogo:false},organization:{website:o.website,address:{buildingNumber:o.address.buildingNumber}},billing:b,work:s.work,payroll:s.payroll,backup:s.backup,setupDeferred:s.setupDeferred})},
 clients:workspace.clients.map(c=>({id:c.id,name:c.name,company:c.company,contact_person:c.contactPerson,email:c.email,phone:c.phone,address_line1:c.addressLine1??'Rue fictive',address_line2:'',postal_code:c.postalCode??'1000',city:c.city??'Lausanne',country:c.country??'CH',archived_at:null}))};}
 desktopApi.loadWorkspace=realRead;desktopApi.createEntity=realCreate;
 desktopApi.resolveConnectedCompany=async(org,choice)=>{proof.choices.push(org+':'+(choice||'auto'));if((!choice||choice==='auto')&&((org==='synthetic-organization-b'&&workspace.workNotesScope==='synthetic-company-a')||(mode==='foreign'&&org==='automation-qa'&&workspace.workNotesScope==='synthetic-company-b')))return {status:'choose_remote',organizationId:org,changed:false};return baseResolve(org,choice);};
 native.invoke=async(command:string,args?:any,options?:unknown)=>{
 proof.commands.push(command);
 if(command==='outgoing_mail_state')return {scope:workspace.workNotesScope==='synthetic-company-a'?'mail-a':'mail-b',connection:{connected:false},templates:structuredClone(workspace.settings!.mailTemplates),signature:{includeCompanyLogo:false},canConfigure:true};
 if(command==='save_outgoing_mail_templates'){proof.saveCalls++;proof.saveScopes.push(args.scope);if(mode==='permission-refused')throw Error('Accès refusé : votre rôle permet la consultation uniquement.');if(args.scope!=='mail-a')throw Error('Closed fixture wrong mail origin');proof.accepted++;workspace.settings!.mailTemplates=structuredClone(args.templates);originSnapshot=structuredClone(workspace);holdNext=mode!=='current'&&!mode.startsWith('late-ack-');if(mode.startsWith('late-ack-')){proof.saveAckPending=true;return new Promise<void>(resolve=>{releaseAck=()=>{proof.saveAckPending=false;holdNext=true;resolve();};});}return;}
 if(command==='create_record'){if(args.entity!=='clients')throw Error('Only synthetic client creation allowed');proof.clientWrites++;workspace.clients.push({id:args.data.id,name:args.data.name,company:args.data.company,contactPerson:args.data.contact_person,email:'',phone:'',addressLine1:'Rue fictive',postalCode:'1000',city:'Lausanne',country:'CH',archivedAt:null} as any);return {id:args.data.id};}
 if(command==='get_app_state')return {onboarding_completed:true,activity_profile_required:false,data_dir:'',app_version:'synthetic'};
 if(command==='get_workspace'){const id=++nextId;if(proof.accepted>0)mailReads++;if((holdNext&&mode==='foreign')||(mode==='recovery-foreign-fallback'&&mailReads===2)||foreignNext){foreignNext=false;workspace.workNotesScope='synthetic-company-b';workspace.settings!.organization.legalName='FOREIGN MAIL COMPANY B';workspace.clients=[{...workspace.clients[0],id:'synthetic-client-b',name:'Client fictif B',company:'Client fictif B'}];}const snapshot=structuredClone(raw()),pending=holdNext||(mode.startsWith('recovery-')&&proof.accepted>0);holdNext=false;proof.reads.push({id,scope:snapshot.work_notes_scope,pending,afterMailSave:proof.accepted>0});if(pending)return new Promise((resolve,reject)=>held.set(id,{resolve,reject,snapshot}));return snapshot;}
 if(['send_outgoing_mail','send_shared_mail','connect_outgoing_mail','connect_shared_mail','disconnect_outgoing_mail','disconnect_shared_mail'].includes(command))throw Error('No email/SMTP action allowed');
 return previousInvoke(command,args,options);};
 Object.assign(window,{__qaMailSettings:{proof,begin(next:string){mode=next;},releaseAck(){if(!releaseAck)throw Error('No held ACK');releaseAck();releaseAck=undefined;},nextForeignRead(){foreignNext=true;},restoreOrigin(){if(!originSnapshot)throw Error('No acknowledged origin');Object.assign(workspace,structuredClone(originSnapshot));},
 settle(id:number,failure=false){const r=held.get(id);if(!r)throw Error('No held mail parent read');held.delete(id);proof.reads.find(r=>r.id===id).pending=false;failure?r.reject(Error('Synthetic parent mail refresh unavailable')):r.resolve(r.snapshot);},
 switchVerifiedAccount(){const next:CloudAccountState={status:'connected',organizationId:'synthetic-organization-b',organizationName:'SYNTHETIC COMPANY B',role:'owner'};identity.link(next,'synthetic-member-b','synthetic-company-b');identity.setAccount(next,'synthetic-member-b');identity.identityMode('ready');identity.releaseAccount(1);},
 makeReadOnly(){identity.setAccount({status:'connected',organizationId:'automation-qa',organizationName:'Entreprise fictive A',role:'read_only'});identity.releaseAccount(1);},
 state(){return {proof:structuredClone(proof),database:{scope:workspace.workNotesScope,company:workspace.settings!.organization.legalName,clients:workspace.clients.map(c=>({id:c.id,company:c.company})),templates:structuredClone(workspace.settings!.mailTemplates)},receiveAllowed:companyReceiveAllowed()};}}});
}
