// Isolated browser acceptance data; the accounting engine is exercised by SQLite tests.
import type { Expense, SupplierCreditNote, SupplierInvoice, Workspace } from '../src/types';

export function installProjectCostFixture(workspace: Workspace) {
  workspace.projects = ['Rénovation des espaces de travail et de la salle de réunion', 'Projet avec TVA à contrôler', 'Projet intégralement crédité'].map((name, index) => ({
    id: `cost-project-${index}`, clientId: workspace.clients[0].id, name, address: '', status: 'in_progress', plannedStart: '', plannedEnd: '', actualStart: '', actualEnd: '', budgetCents: 0, plannedMinutes: 0, notes: '',
  }));
  const [main, review, zero] = workspace.projects;
  const expense: Expense = { id: 'cost-expense', projectId: main.id, date: '2026-02-10', dueDate: '2026-03-10', supplier: 'Marchandises', category: 'Matériaux', reference: 'EXP-001', netCents: 10000, vatCents: 810, totalCents: 10810, paymentStatus: 'paid', paidAt: '2026-02-10', reimbursable: false, note: '', costCents: 10810, costReviewRequired: false, costBasis: 'accounted' };
  workspace.expenses = [expense, { ...expense, id: 'review-expense', projectId: review.id, costCents: 10000, costReviewRequired: true, costBasis: 'review' }, { ...expense, id: 'zero-expense', projectId: zero.id, netCents: 10000, vatCents: 0, totalCents: 10000, costCents: 10000 }];
  const invoice: SupplierInvoice = {
    id: 'cost-invoice', supplierId: 'supplier-qa', projectId: main.id, documentDate: '2026-02-10', dueDate: '2026-03-10', supplierName: 'Fournisseur projet', reference: 'FF-001', currency: 'CHF', documentStatus: 'validated', paymentStatus: 'partial', netCents: 20000, vatCents: 1620, totalCents: 21620, paidCents: 0, creditedCents: 5405, balanceCents: 16215, matchStatus: 'unmatched', validatedAt: '2026-02-10', validationJournalEntryId: 'journal-qa', note: '', payments: [], attachments: [], createdAt: '2026-02-10', updatedAt: '2026-02-10',
    lines: [{ id: 'cost-line', supplierInvoiceId: 'cost-invoice', position: 0, description: 'Matériel', quantityMilli: 2000, unit: 'pièces', unitPriceCents: 10000, discountBp: 0, vatBp: 810, netCents: 20000, vatCents: 1620, totalCents: 21620, category: 'Matériaux', expenseAccountId: null, postedExpenseAccountId: 'expense', projectId: null, costCents: 21620, costReviewRequired: false, costBasis: 'accounted' }],
  };
  workspace.supplierInvoices = [invoice, { ...invoice, id: 'draft-excluded', documentStatus: 'draft' }];
  const credit: SupplierCreditNote = { id: 'cost-credit', supplierId: 'supplier-qa', number: 'AF-001', supplierName: invoice.supplierName, currency: 'CHF', validatedAt: '2026-03-10', validationJournalEntryId: 'credit-journal', createdAt: '2026-03-10', updatedAt: '2026-03-10', documentDate: '2026-03-10', reference: 'AF-001', note: '', status: 'validated', netCents: 5000, vatCents: 405, totalCents: 5405, allocatedCents: 5405, allocations: [], items: [{ ...invoice.lines[0], id: 'credit-line', supplierCreditNoteId: 'cost-credit', projectId: main.id, netCents: 5000, vatCents: 405, totalCents: 5405, costCents: 5405, quantityMilli: 500 }] };
  workspace.supplierCreditNotes = [credit, { ...credit, id: 'zero-credit', totalCents: 10000, netCents: 10000, vatCents: 0, allocatedCents: 0, items: [{ ...credit.items[0], id: 'zero-credit-line', supplierCreditNoteId: 'zero-credit', projectId: zero.id, netCents: 10000, vatCents: 0, totalCents: 10000, costCents: 10000 }] }];
  workspace.invoices = [{ id: 'cost-sale', projectId: main.id, clientId: workspace.clients[0].id, quoteId: null, originalInvoiceId: null, type: 'standard', status: 'issued', number: 'F-001', currency: 'CHF', issueDate: '2026-03-10', dueDate: '2026-04-10', serviceDateFrom: '2026-03-01', serviceDateTo: '2026-03-10', title: 'Prestation', notes: '', terms: '', depositPercentageBp: null, depositBasisLines: null, createdAt: '2026-03-10', lines: [{ id: 'sale-line', description: 'Prestation', quantity: 1, unit: 'forfait', unitPriceCents: 100000, vatRateBp: 0 }] }];
}
