import { createRequire } from 'node:module';
import { mkdir, writeFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.ZENTRA_PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true, ...(process.platform === 'win32' ? { channel: 'msedge' } : {}) });
const report = [];
await mkdir('.qa/recurrence', { recursive: true });
try {
  for (const width of [320, 390, 768, 1024, 1440]) {
    for (const automatic of [false, true]) {
      const page = await browser.newPage({ viewport: { width, height: 900 } });
      const errors = [];
      page.on('pageerror', (error) => errors.push(error.message));
      page.on('dialog', (dialog) => dialog.accept());
      await page.emulateMedia({ reducedMotion: 'reduce' });
      await page.goto(`http://127.0.0.1:5175/tests/mobile-harness.html?recurrence=1${automatic ? '&automatic=1' : ''}`, { waitUntil: 'domcontentloaded' });
      const persisted = () => page.evaluate(() => JSON.parse(sessionStorage.getItem('qa-recurrence-persisted')));
      const attempts = (operation) => page.evaluate((operation) => JSON.parse(sessionStorage.getItem(`qa-recurrence-${operation}-attempts`) || '[]'), operation);
      const mode = (operation, value) => page.evaluate(({ operation, value }) => sessionStorage.setItem(`qa-recurrence-${operation}-failure`, value), { operation, value });
      const navigate = async (name) => {
        await page.getByRole('button', { name: 'Aller à un écran', exact: true }).click();
        await page.getByRole('searchbox', { name: 'Rechercher un écran' }).fill(name);
        await page.locator('.navigation-palette__results button').filter({ has: page.getByText(name, { exact: true }) }).click();
        await page.locator('.navigation-palette').waitFor({ state: 'detached' });
      };
      const tour = page.getByRole('button', { name: 'Ne plus afficher automatiquement', exact: true });
      if (await tour.isVisible()) await tour.click();
      const capture = async (name) => {
        assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `${width}-${name}: horizontal overflow`);
        const clipped = await page.locator('.recurring-documents button, .recurring-documents time, .recurring-documents summary').evaluateAll((nodes) => nodes.filter((node) => node.getClientRects().length && node.getBoundingClientRect().right > node.closest('.recurring-documents').getBoundingClientRect().right + 1).map((node) => node.textContent));
        assert.deepEqual(clipped, [], `${width}-${name}: content clipped inside panel`);
        await page.screenshot({ path: `.qa/recurrence/${width}-${automatic ? 'automatic' : 'lifecycle'}-${name}.png` });
      };
      if (automatic) {
        await page.waitForFunction(() => sessionStorage.getItem('qa-recurrence-read-count') === '1');
        await navigate('Commandes & livraisons');
        await page.locator('.sales-order-card').first().click();
        assert.ok(await page.getByRole('button', { name: 'Mettre en pause', exact: true }).isDisabled(), 'manual mutations wait for the ongoing automatic batch');
        await page.evaluate(() => window.dispatchEvent(new Event('qa-release-recurrence-read')));
        await page.getByRole('dialog', { name: 'Enregistrement effectué', exact: true }).waitFor();
        assert.equal((await persisted()).invoices.length, 1);
        assert.equal((await attempts('generate')).length, 1, 'second schedule must wait for recovery of the first');
        await page.evaluate(() => { window.dispatchEvent(new Event('focus')); document.dispatchEvent(new Event('visibilitychange')); });
        await page.getByRole('button', { name: 'Actualiser les données', exact: true }).click();
        await page.getByText('Actualisation impossible', { exact: true }).waitFor();
        assert.equal((await attempts('generate')).length, 1, 'failed read-only recovery must never regenerate');
        await capture('read-refused');
        await page.evaluate(() => sessionStorage.removeItem('qa-recurrence-block-reads'));
        await page.getByRole('button', { name: 'Actualiser les données', exact: true }).click();
        await page.getByRole('dialog', { name: 'Enregistrement effectué', exact: true }).waitFor({ state: 'detached' });
        await page.waitForFunction(() => JSON.parse(sessionStorage.getItem('qa-recurrence-persisted')).invoices.length === 2);
        assert.equal((await attempts('generate')).length, 2, 'each of two schedules must be generated exactly once');
        assert.deepEqual((await persisted()).invoices.map((item) => item.status), ['draft', 'draft']);
        await navigate('Clients');
      }
      await navigate('Commandes & livraisons');
      await page.locator('.sales-order-card').first().click();
      const panel = page.locator('.recurring-documents');
      if (!automatic) {
        await panel.getByRole('button', { name: 'Planifier cette commande', exact: true }).click();
        const start = panel.getByLabel('Première échéance', { exact: false });
        const terms = panel.getByLabel('Délai de paiement', { exact: false });
        await start.fill('2025-01-31');
        await terms.fill('');
        await panel.getByRole('button', { name: 'Créer la planification', exact: true }).click();
        await panel.getByText('Le délai doit être compris entre 0 et 365 jours.', { exact: true }).waitFor();
        assert.equal((await attempts('create')).length, 0, 'blank terms must require correction, not become zero');
        assert.equal(await terms.inputValue(), '');
        const validationBounds = await panel.locator('.recurring-documents__error-summary').boundingBox();
        assert.ok(validationBounds.y >= 130 && validationBounds.y + validationBounds.height < 830, 'validation summary must be visible between the mobile header and navigation');
        await capture('terms-required');
        await terms.fill('15');
        await mode('create', 'reject');
        await panel.getByRole('button', { name: 'Créer la planification', exact: true }).click();
        await panel.getByText('La planification n’a pas été enregistrée : refus create simulé.', { exact: true }).waitFor();
        assert.equal(await terms.inputValue(), '15');
        assert.equal(await start.inputValue(), '2025-01-31');
        await panel.locator('.error-panel').waitFor();
        await capture('create-refused');
        await mode('create', 'refresh_twice');
        await panel.getByRole('button', { name: 'Créer la planification', exact: true }).evaluate((button) => { button.click(); button.click(); });
        await page.getByRole('dialog', { name: 'Enregistrement effectué', exact: true }).waitFor();
        assert.equal((await attempts('create')).length, 2);
        const createInputs = await attempts('create');
        assert.equal(new Set(createInputs.map((input) => input.requestId)).size, 1);
        await page.getByRole('button', { name: 'Actualiser les données', exact: true }).click();
        await page.getByRole('dialog', { name: 'Enregistrement effectué', exact: true }).waitFor({ state: 'detached' });
        await panel.getByText('Revue requise', { exact: true }).waitFor();
        assert.equal((await persisted()).invoices.length, 12);
        assert.equal((await attempts('generate')).length, 1);
        assert.ok((await persisted()).invoices.every((item) => item.status === 'draft' && !item.number));
        assert.equal((await persisted()).invoices[0].dueDate, '2025-02-15');
        await panel.locator('.recurring-documents__catch-up').scrollIntoViewIfNeeded();
        await capture('catch-up-review');
        await mode('update', 'reject');
        await panel.getByRole('button', { name: 'Reprendre et préparer au plus 12 brouillons', exact: true }).click();
        await panel.getByText('La planification n’a pas été enregistrée : refus update simulé.', { exact: true }).waitFor();
        assert.equal((await persisted()).invoices.length, 12);
        await capture('resume-refused');
        await mode('update', 'refresh_once');
        await panel.getByRole('button', { name: 'Reprendre et préparer au plus 12 brouillons', exact: true }).click();
        await panel.getByText('Planification active', { exact: true }).waitFor();
        const updated = await attempts('update');
        assert.equal(updated.length, 2);
        assert.equal(updated[0].requestId, updated[1].requestId);
        await page.waitForFunction(() => JSON.parse(sessionStorage.getItem('qa-recurrence-persisted')).invoices.length === 20);
        const state = await persisted();
        assert.equal(state.recurrenceSchedules[0].nextScheduledFor, '2026-09-30');
        assert.equal(new Set(state.recurrenceOccurrences.map((item) => item.scheduledFor)).size, 20);
        assert.equal(await panel.locator('.recurring-documents__history li').count(), 10);
        await panel.getByRole('button', { name: 'Afficher les échéances précédentes (10 sur 20)', exact: true }).click();
        assert.equal(await panel.locator('.recurring-documents__history li').count(), 20);
        const dates = await panel.locator('.recurring-documents__history li time').evaluateAll((nodes) => nodes.map((node) => node.dateTime));
        assert.deepEqual(dates, [...dates].sort().reverse());
        await panel.getByRole('button', { name: 'Mettre en pause', exact: true }).evaluate((button) => { button.click(); button.click(); });
        await panel.getByText('En pause', { exact: true }).waitFor();
        assert.equal((await attempts('update')).length, 3);
        await page.evaluate(() => window.dispatchEvent(new Event('focus')));
        assert.equal((await attempts('generate')).length, 2, 'pause must prevent a new scan');
        await panel.getByRole('button', { name: 'Reprendre la planification', exact: true }).click();
        await panel.getByText('Planification active', { exact: true }).waitFor();
        await panel.getByRole('button', { name: 'Terminer définitivement', exact: true }).click();
        await panel.getByText('Terminée', { exact: true }).waitFor();
        assert.equal((await persisted()).invoices.length, 20);
        assert.equal(await panel.getByRole('button', { name: 'Mettre en pause', exact: true }).count(), 0);
        await panel.getByRole('button', { name: 'Ouvrir la facture 2026-08-31', exact: true }).click();
        const dialog = page.getByRole('dialog');
        await dialog.waitFor();
        assert.equal(await dialog.getByRole('textbox', { name: 'Description', exact: true }).first().inputValue(), 'Maintenance et assistance');
        await capture('draft-open');
        await page.keyboard.press('Escape');
        await dialog.waitFor({ state: 'detached' });
      }
      await panel.locator('.recurring-documents__summary').scrollIntoViewIfNeeded();
      await capture('finished');
      const unreadable = await panel.locator('p, small, label, .recurring-documents__field-label, .recurring-documents__fact > span, time').evaluateAll((nodes) => nodes.filter((node) => node.getClientRects().length && parseFloat(getComputedStyle(node).fontSize) < 12).map((node) => node.textContent));
      assert.deepEqual(unreadable, []);
      assert.deepEqual(errors, []);
      report.push({ width, automatic, result: automatic ? 'PASS two automatic schedules wait for read-only recovery, one write each, no issued invoice' : 'PASS blank terms, stable retries, catch-up 12 then 8 drafts, reverse chronological history, pause/resume/complete, open draft' });
      console.log(JSON.stringify(report.at(-1)));
      await page.close();
    }
  }
  await writeFile('.qa/recurrence/report.json', JSON.stringify(report, null, 2));
} finally { await browser.close(); }
