import { LegalPage, OperatorContact } from '@/components/legal-page';
import { ZENTRA_PLANS as PLANS } from '@/lib/plans';

export const metadata = {title:'Conditions générales d’utilisation et d’abonnement', alternates:{canonical:'/conditions'}};

export default function Page() {
  return <LegalPage title="Conditions d’utilisation et d’abonnement" intro="Les règles applicables au compte Zentra, au logiciel et aux abonnements proposés aux entreprises." sections={[
    {id:'parties',title:'1. Prestataire et champ d’application',content:<><OperatorContact /><p>Ces conditions régissent le site Zentra, son compte et la licence du logiciel. L’offre vise les entreprises et les indépendants. La personne qui souscrit pour une entreprise doit être habilitée à l’engager. Les dispositions légales impératives et les accords particuliers écrits prévalent.</p></>},
    {id:'service',title:'2. Ce que comprend le service',content:<><p>Zentra Automation est une option facultative distincte, à 15 CHF par mois et par entreprise, soumise à ses conditions spécifiques et à une activation volontaire. Aucun supplément n’est déclenché par une mise à jour. Zentra réunit les fonctions de gestion décrites dans l’offre et dans la version effectivement disponible : devis, factures, projets, comptabilité, achats et salaires. Les fonctions dépendent de la plateforme et de la version installée. La page de téléchargement précise les versions disponibles et les modalités d’installation.</p><p>La base de travail est locale. Certains services nécessitent une connexion : compte, licence, invitations, synchronisation, archivage et sauvegarde distante. Le partage continu de la base complète est disponible à partir de la version 1.67 après activation explicite. Il inclut les salaires et pièces jointes. Les modifications concurrentes ne sont pas fusionnées automatiquement : une sauvegarde locale précède la réception choisie, puis les changements non envoyés doivent être repris manuellement. Une sauvegarde distante complète ne fusionne pas non plus deux bases. Les fonctions futures annoncées ne font pas partie d’une garantie de livraison à une date déterminée.</p></>},
    {id:'commande',title:'3. Compte, essai et commande',content:<><p>Créer un compte ne déclenche aucun paiement. Lorsqu’un essai de 14 jours est accordé, il est sans engagement et sans carte bancaire ; il ne se transforme pas automatiquement en abonnement payant.</p><p>Pour souscrire : choisissez une formule, consultez et acceptez ces conditions, puis vérifiez le prix, la périodicité et vos coordonnées sur la page de paiement. Vous pouvez corriger vos informations ou revenir au site avant de confirmer. Le contrat payant est conclu lors de la confirmation du paiement et de l’acceptation de la commande. Une confirmation et les justificatifs correspondants sont adressés à l’e-mail indiqué.</p><p>Les paiements de test ne créent pas d’abonnement commercial. L’accès public au paiement peut rester indisponible pendant la préparation du service.</p></>},
    {id:'tarifs',title:'4. Formules, prix et personnes autorisées',content:<><ul>{PLANS.map(plan=><li key={plan.id}><strong>{plan.name}</strong> : {plan.priceChfCents/100} CHF par mois, {plan.seats} personne{plan.seats>1?'s':''} au total.</li>)}</ul><p>Le titulaire compte dans ce total. Une invitation en attente réserve une place. Chaque membre utilise son propre compte ; plusieurs appareils peuvent être autorisés pour la même personne. Une fiche de salarié sans accès au logiciel ne consomme pas de place. Le titulaire choisit les rôles et retire les accès devenus inutiles.</p><p>L’éditeur n’est pas assujetti à la TVA suisse ; il ne facture pas de TVA suisse sur ces abonnements. Le montant et les éventuelles particularités du contrat sont présentés avant le paiement. Les anciens abonnements conservent leur prix contractuel tant qu’aucun changement n’est convenu.</p></>},
    {id:'duree',title:'5. Renouvellement et résiliation',content:<><p>L’abonnement mensuel se renouvelle à chaque échéance jusqu’à sa résiliation. Vous pouvez demander l’arrêt du renouvellement depuis la gestion de l’abonnement ou à info@zentraapp.ch avant l’échéance suivante. La résiliation prend effet à la fin de la période payée ; son terme est confirmé. La période commencée reste due, sous réserve d’un droit impératif ou d’un accord de remboursement.</p><p>En cas d’échec de paiement ou d’expiration de la licence, certaines fonctions peuvent passer en lecture seule. Exportez vos documents et sauvegardez vos données avant la fin du contrat. La résiliation de l’abonnement ne supprime pas automatiquement la base présente sur vos appareils et ne constitue pas à elle seule une demande d’effacement du compte.</p></>},
    {id:'utilisation',title:'6. Utilisation, données et assistance',content:<><p>Le client fournit des informations exactes, protège ses accès, dispose des droits nécessaires sur les données importées et informe les personnes concernées. Il vérifie les calculs, les paramètres d’assurance, les barèmes et les documents avant leur utilisation ou leur transmission. Zentra n’est pas certifié Swissdec et ne transmet pas de déclarations ELM.</p><p>Le client reste responsable de ses obligations comptables, sociales et fiscales, de la gestion des droits de ses collaborateurs et de ses sauvegardes. L’assistant local est facultatif : ses suggestions peuvent comporter des erreurs et doivent être contrôlées. L’assistance est joignable à info@zentraapp.ch ; aucun délai de réponse ni disponibilité continue n’est contractuellement garanti sans accord spécifique.</p></>},
    {id:'donnees',title:'7. Protection et traitement des données',content:<><p>Le client conserve ses droits sur ses données. La <a href="/confidentialite">politique de confidentialité</a> décrit les traitements réalisés pour le compte, le paiement et le fonctionnement du service. L’<a href="/sous-traitance">annexe de traitement des données</a> s’applique aux données d’entreprise confiées aux services distants. Les données laissées exclusivement sur un appareil ne sont pas mises à disposition de l’éditeur par le seul fait d’utiliser Zentra.</p><p>Le client ne doit transmettre que les données nécessaires. Les exports, la suppression des fichiers et les demandes de clôture suivent les modalités et les limites de conservation indiquées dans ces documents.</p></>},
    {id:'maintenance',title:'8. Mises à jour et interruptions',content:<p>Des mises à jour peuvent corriger des erreurs, modifier l’interface ou renforcer la sécurité. Leur disponibilité dépend des plateformes et des règles de distribution. Les services peuvent être interrompus pour maintenance ou à la suite d’un incident. Signalez tout défaut reproductible au support ; l’éditeur l’examine et indique les mesures possibles. Une restriction d’accès peut être nécessaire en cas d’abus ou de risque de sécurité, avec information lorsque cela est possible.</p>},
    {id:'responsabilite',title:'9. Responsabilité',content:<p>Chaque partie répond de ses obligations selon le droit applicable. Le logiciel ne garantit pas l’absence de toute erreur ni une conformité automatique à chaque situation particulière. Aucune clause de ces conditions n’exclut une responsabilité qui ne peut pas être exclue légalement, notamment en cas de dol ou de faute grave. Les droits légaux du client en cas de défaut demeurent réservés.</p>},
    {id:'modifications',title:'10. Évolutions des conditions et droit applicable',content:<><p>La date de version figure en tête du document. Une modification matérielle des conditions ou du prix d’un contrat existant doit être annoncée avant son application, avec la possibilité de mettre fin au renouvellement. Les nouvelles conditions ne modifient pas rétroactivement une période déjà payée. En cas de désaccord, contactez le support avant leur prise d’effet.</p><p>Le droit suisse est applicable, sous réserve des dispositions impératives éventuellement applicables. Les tribunaux compétents sont déterminés par les règles légales ; aucun for impératif n’est écarté. Ces conditions peuvent être imprimées ou enregistrées en PDF depuis cette page.</p></>},
  ]}/>;
}
