import { LegalPage } from '@/components/legal-page';
export const metadata = {title:'Cookies et stockage local',alternates:{canonical:'/cookies'}};
export default function Page() {
  return <LegalPage title="Cookies et stockage local" intro="Les données techniques utilisées pour maintenir votre connexion et vos préférences." sections={[
    {id:'connexion',title:'Connexion et sécurité',content:<><p>Les cookies de session Zentra sont sécurisés, limités au domaine utilisé et inaccessibles au JavaScript de la page (HttpOnly). Ils permettent la connexion et protègent le compte.</p><ul><li>Accès : durée du jeton, plafonnée à 7 jours.</li><li>Renouvellement de session : jusqu’à 30 jours, renouvelé lors du rafraîchissement de la connexion.</li><li>Confirmation ou récupération du compte : vérificateur PKCE et chemin de retour conservés 10 minutes.</li><li>Rattachement d’un paiement à la licence : jusqu’à 365 jours.</li></ul><p>Cloudflare peut déposer des cookies de sécurité. L’accès facultatif ChatGPT Sites et la page de paiement Stripe utilisent aussi les mécanismes de leurs fournisseurs.</p></>},
    {id:'local',title:'Préférences et copies sur l’appareil',content:<p>L’application conserve localement la langue, l’apparence, l’état du tutoriel et des brouillons. La base et les copies hors ligne des documents ne sont pas de simples cookies. Sauvegardez les modifications non synchronisées avant d’effacer les données de l’application.</p>},
    {id:'publicite',title:'Publicité et audience',content:<p>Le code du site Zentra n’intègre actuellement ni pixel publicitaire ni outil facultatif de mesure d’audience. Aucun consentement publicitaire n’est exigé pour créer un compte. Cela n’exclut pas les journaux techniques de sécurité des prestataires. Si un outil facultatif est ajouté, les informations et choix nécessaires seront présentés avant son activation.</p>},
    {id:'choix',title:'Gérer vos choix',content:<><p>Vous pouvez vous déconnecter puis supprimer les cookies du domaine depuis votre navigateur. Leur blocage peut empêcher la connexion. Leur suppression n’annule pas votre abonnement et n’efface pas les données hébergées.</p><p>Pour les demandes relatives aux données hébergées, consultez la <a href="/confidentialite#droits">politique de confidentialité</a>.</p></>},
  ]}/>;
}
