import type { AppLanguage } from './language';

type Localized = Readonly<Record<AppLanguage, string>>;
const copy = (fr: string, de: string, it: string, en: string): Localized => ({ fr, de, it, en });
export const releaseHistoryCopy = {
  title: copy('Les nouveautés de Zentra', 'Neues in Zentra', 'Le novità di Zentra', 'What’s new in Zentra'),
  current: copy('Voir les nouveautés de cette version', 'Neuerungen dieser Version ansehen', 'Vedi le novità di questa versione', 'See what’s new in this version'),
  older: copy('Voir les mises à jour précédentes', 'Frühere Updates ansehen', 'Vedi gli aggiornamenti precedenti', 'See previous updates'),
  installed: copy('Version installée', 'Installierte Version', 'Versione installata', 'Installed version'),
  unknown: copy('Les notes de cette version ne sont pas encore disponibles dans l’application.', 'Die Hinweise zu dieser Version sind in der App noch nicht verfügbar.', 'Le note di questa versione non sono ancora disponibili nell’app.', 'Notes for this version are not yet available in the app.'),
  loading: copy('Lecture de la version installée…', 'Installierte Version wird gelesen…', 'Lettura della versione installata…', 'Reading the installed version…'),
  archive: copy('Cet historique présente les versions documentées dans cette édition. Il reste consultable sans connexion.', 'Dieser Verlauf zeigt die in dieser Ausgabe dokumentierten Versionen. Er ist auch offline verfügbar.', 'Questa cronologia mostra le versioni documentate in questa edizione. È consultabile anche senza connessione.', 'This history lists the versions documented in this edition. It is also available offline.'),
  empty: copy('Aucune version précédente documentée pour cette installation.', 'Für diese Installation ist keine frühere Version dokumentiert.', 'Nessuna versione precedente documentata per questa installazione.', 'No earlier version is documented for this installation.'),
};

// Append a version with every shipped correction; never rewrite an older entry
// to describe work that was added later. See docs/RELEASE-*.md for release evidence.
export const releaseHistory = [
  { version: '1.89.1', title: copy('Connexion de la messagerie', 'Verbindung zum E-Mail-Konto', 'Connessione della casella e-mail', 'Mailbox connection'), changes: [
    copy('Correction de l’erreur qui empêchait de connecter une boîte Infomaniak ou SMTP depuis les réglages des e-mails. La vérification d’une connexion existante et la reconnexion après déconnexion sont également corrigées.', 'Der Fehler beim Verbinden eines Infomaniak- oder SMTP-Postfachs in den E-Mail-Einstellungen wurde behoben. Auch die Prüfung einer bestehenden Verbindung und das erneute Verbinden nach einer Trennung wurden korrigiert.', 'Corretto l’errore che impediva di collegare una casella Infomaniak o SMTP nelle impostazioni e-mail. Corrette anche la verifica di una connessione esistente e la riconnessione dopo la disconnessione.', 'Fixed the error preventing Infomaniak or SMTP mailbox connections in email settings. Checking an existing connection and reconnecting after disconnection are also fixed.'),
  ] },
  { version: '1.89.0', title: copy('Vos documents, de la réception à l’envoi', 'Dokumente vom Eingang bis zum Versand', 'Documenti dalla ricezione all’invio', 'Documents from receipt to sending'), changes: [
    copy('Scannez une facture PDF ou une photo dans Achats et fournisseurs. Automation prépare les informations, que vous vérifiez avant l’enregistrement. L’original rejoint le brouillon ; la comptabilisation garde les règles TVA de votre entreprise.', 'Scannen Sie eine PDF-Rechnung oder ein Foto unter Einkäufe und Lieferanten. Automation bereitet die Angaben zur Prüfung vor. Das Original wird dem Entwurf beigefügt; die Verbuchung berücksichtigt die Mehrwertsteuer-Einstellungen Ihres Unternehmens.', 'Scansiona una fattura PDF o una foto in Acquisti e fornitori. Automation prepara i dati da verificare prima del salvataggio. L’originale viene allegato alla bozza; la contabilizzazione rispetta le impostazioni IVA aziendali.', 'Scan a PDF invoice or photo in Purchases and suppliers. Automation prepares the details for your review. The original is attached to the draft; posting follows your company’s VAT settings.'),
    copy('Le registre des immobilisations suit vos équipements, leur valeur et leurs amortissements. Chaque écriture est confirmée et conservée dans le journal comptable.', 'Das Anlagenregister erfasst Ihre Ausstattung, ihren Wert und ihre Abschreibungen. Jede Buchung wird bestätigt und im Buchungsjournal gespeichert.', 'Il registro delle immobilizzazioni tiene traccia dei beni, del loro valore e degli ammortamenti. Ogni scrittura viene confermata e conservata nel giornale contabile.', 'The fixed assets register tracks equipment, book value and depreciation. Each posting is confirmed and preserved in the accounting journal.'),
    copy('Connectez Infomaniak ou une messagerie SMTP chiffrée dans Paramètres → E-mails. Les identifiants restent protégés sur chaque appareil.', 'Verbinden Sie Infomaniak oder einen verschlüsselten SMTP-Dienst unter Einstellungen → E-Mails. Die Zugangsdaten bleiben auf jedem Gerät geschützt.', 'Collega Infomaniak o una casella SMTP cifrata in Impostazioni → E-mail. Le credenziali restano protette su ciascun dispositivo.', 'Connect Infomaniak or an encrypted SMTP mailbox in Settings → Emails. Credentials stay protected on each device.'),
    copy('Envoyez vos devis, factures et relances avec leur PDF joint. Le destinataire, l’objet et le message restent modifiables avant votre confirmation.', 'Senden Sie Angebote, Rechnungen und Zahlungserinnerungen mit PDF-Anhang. Empfänger, Betreff und Nachricht bleiben vor der Bestätigung bearbeitbar.', 'Invia preventivi, fatture e solleciti con il PDF allegato. Destinatario, oggetto e messaggio restano modificabili prima della conferma.', 'Send quotes, invoices and reminders with their PDF attached. Review or edit the recipient, subject and message before confirming.'),
    copy('Personnalisez les modèles avec les coordonnées de l’entreprise, le client, le numéro, les montants et l’échéance. Aucun renvoi automatique en cas de résultat incertain.', 'Passen Sie Vorlagen mit Firmendaten, Kunde, Nummer, Beträgen und Fälligkeit an. Bei unklarem Ergebnis wird nichts automatisch erneut gesendet.', 'Personalizza i modelli con i dati aziendali, il cliente, il numero, gli importi e la scadenza. Nessun reinvio automatico se l’esito è incerto.', 'Customize templates with company details, client, document number, amounts and due date. Uncertain submissions are never resent automatically.'),
  ] },
  { version: '1.88.1', title: copy('Plus rapide au quotidien', 'Schneller im Alltag', 'Più veloce ogni giorno', 'Faster every day'), changes: [
    copy('Les grandes listes de devis, factures, achats et salaires sont préparées plus rapidement à l’ouverture et après une synchronisation.', 'Große Listen mit Angeboten, Rechnungen, Einkäufen und Löhnen werden beim Öffnen und nach einer Synchronisierung schneller vorbereitet.', 'Gli elenchi estesi di preventivi, fatture, acquisti e salari vengono preparati più rapidamente all’apertura e dopo una sincronizzazione.', 'Large lists of quotes, invoices, purchases and payroll are prepared faster on opening and after synchronization.'),
    copy('Les montants du tableau de bord et les dates demandent moins de calculs. Le pointage actualise uniquement son compteur, pour garder les écrans et les formulaires réactifs.', 'Die Beträge in der Übersicht und Datumsangaben benötigen weniger Berechnungen. Die Zeiterfassung aktualisiert nur ihren Zähler, damit Ansichten und Formulare reaktionsfähig bleiben.', 'Gli importi della panoramica e le date richiedono meno calcoli. Il rilevamento del tempo aggiorna solo il contatore, mantenendo schermate e moduli reattivi.', 'Dashboard amounts and dates require fewer calculations. Time tracking updates only its counter, keeping screens and forms responsive.'),
    copy('La lecture de l’espace local s’effectue en arrière-plan. La synchronisation automatique et les contrôles d’accès restent actifs.', 'Der lokale Arbeitsbereich wird im Hintergrund gelesen. Automatische Synchronisierung und Zugriffskontrollen bleiben aktiv.', 'La lettura dello spazio locale avviene in background. La sincronizzazione automatica e i controlli di accesso restano attivi.', 'The local workspace is read in the background. Automatic synchronization and access checks remain active.'),
  ] },
  { version: '1.88.0', title: copy('Zentra, à votre façon', 'Zentra, wie Sie es mögen', 'Zentra, a modo tuo', 'Zentra, your way'), changes: [
    copy('Choisissez les quatre raccourcis en bas de votre mobile et les quatre actions de l’accueil. Aperçu, ordre et réglages par défaut se trouvent dans Paramètres → Mes raccourcis. Chaque appareil garde ses propres choix.', 'Wählen Sie die vier Kurzbefehle am unteren Bildschirmrand und die vier Startaktionen. Vorschau, Reihenfolge und Standardwerte finden Sie unter Einstellungen → Meine Kurzbefehle. Jedes Gerät behält seine eigenen Einstellungen.', 'Scegli le quattro scorciatoie in basso sul telefono e le quattro azioni iniziali. Anteprima, ordine e valori predefiniti sono in Impostazioni → Le mie scorciatoie. Ogni dispositivo mantiene le proprie scelte.', 'Choose four mobile bottom shortcuts and four home actions. Preview, order and defaults are in Settings → My shortcuts. Each device keeps its own choices.'),
    copy('Un état discret indique la synchronisation de l’espace actif, l’envoi en cours ou le mode hors ligne. Un problème ouvre les réglages du compte. Les échanges restent en arrière-plan.', 'Ein dezenter Status zeigt die Synchronisierung des aktiven Bereichs, laufendes Senden oder den Offline-Modus. Bei Problemen öffnen Sie die Kontoeinstellungen. Der Austausch bleibt im Hintergrund.', 'Uno stato discreto indica la sincronizzazione dello spazio attivo, l’invio in corso o la modalità offline. In caso di problemi, apre le impostazioni dell’account. Gli scambi restano in background.', 'A quiet status shows active-workspace sync, sending or offline mode. Problems lead to account settings. Updates remain in the background.'),
    copy('Les résultats du bilan Automation ouvrent les factures, rendez-vous ou tâches correspondants. Les raccourcis tactiles et les commandes de personnalisation restent accessibles au-dessus de la barre mobile.', 'Die Ergebnisse der Automation-Übersicht öffnen die zugehörigen Rechnungen, Termine oder Aufgaben. Touch-Kurzbefehle und Anpassungsaktionen bleiben oberhalb der mobilen Leiste erreichbar.', 'I risultati del riepilogo Automation aprono fatture, appuntamenti o attività corrispondenti. Le scorciatoie e i comandi di personalizzazione restano accessibili sopra la barra mobile.', 'Automation briefing results open the corresponding invoices, appointments or tasks. Touch shortcuts and customization controls stay accessible above the mobile bar.'),
  ] },
  { version: '1.87.0', title: copy('Bienvenue dans votre nouvel espace', 'Willkommen in Ihrem neuen Arbeitsbereich', 'Benvenuto nel tuo nuovo spazio', 'Welcome to your new workspace'), changes: [
    copy('Une introduction animée et un guide accompagnent la configuration complète de votre entreprise. Vous pouvez passer l’animation à tout moment.', 'Eine animierte Einführung und ein Leitfaden begleiten die vollständige Einrichtung Ihres Unternehmens. Die Animation lässt sich jederzeit überspringen.', 'Un’introduzione animata e una guida accompagnano la configurazione completa della tua azienda. Puoi saltare l’animazione in qualsiasi momento.', 'An animated introduction and a guide accompany your complete company setup. You can skip the animation at any time.'),
    copy('Lorsque l’accès Automation de votre entreprise est confirmé, un accueil dédié vous conduit aux réglages ou à l’activité. Il peut être revu depuis les paramètres.', 'Sobald der Automation-Zugang Ihres Unternehmens bestätigt ist, führt eine eigene Begrüßung zu den Einstellungen oder zur Aktivität. Sie lässt sich in den Einstellungen erneut öffnen.', 'Quando l’accesso Automation della tua azienda è confermato, una schermata di benvenuto ti porta alle impostazioni o all’attività. Puoi rivederla dalle impostazioni.', 'When your company’s Automation access is confirmed, a dedicated welcome leads to settings or activity. You can replay it from settings.'),
    copy('Menus, champs et boutons sont harmonisés sur ordinateur et mobile. La sélection est plus douce, les thèmes plus cohérents et les transitions plus courtes.', 'Menüs, Felder und Schaltflächen sind auf Computer und Mobilgeräten einheitlicher. Die Auswahl ist dezenter, die Designs sind konsistenter und die Übergänge kürzer.', 'Menu, campi e pulsanti sono armonizzati su computer e dispositivi mobili. La selezione è più discreta, i temi più coerenti e le transizioni più brevi.', 'Menus, fields and buttons are harmonized across desktop and mobile. Selection is softer, themes are more consistent and transitions are shorter.'),
  ] },
  { version: '1.86.1', title: copy('Des commandes accessibles sur téléphone', 'Erreichbare Bedienelemente auf dem Smartphone', 'Comandi accessibili sul telefono', 'Accessible controls on phones'), changes: [
    copy('Les boutons principaux conservent un texte lisible en mode sombre après un appui sur écran tactile.', 'Die Hauptschaltflächen behalten im Dunkelmodus auch nach einer Berührung gut lesbaren Text.', 'I pulsanti principali mantengono il testo leggibile in modalità scura dopo un tocco.', 'Primary buttons keep readable text in dark mode after a touch interaction.'),
    copy('Les marges de l’écran respectent l’encoche et les bords arrondis, y compris en paysage. Les titres, menus et boutons restent accessibles.', 'Die Bildschirmabstände berücksichtigen Kameraaussparung und abgerundete Ränder, auch im Querformat. Titel, Menüs und Schaltflächen bleiben erreichbar.', 'I margini rispettano la tacca e i bordi arrotondati dello schermo, anche in orizzontale. Titoli, menu e pulsanti restano accessibili.', 'Screen spacing respects the notch and rounded edges, including in landscape. Titles, menus and buttons stay accessible.'),
  ] },
  { version: '1.86.0', title: copy('Un espace de travail repensé', 'Ein neu gestalteter Arbeitsbereich', 'Uno spazio di lavoro ripensato', 'A reimagined workspace'), changes: [
    copy('Navigation, tableaux de bord et paramètres adoptent une présentation plus sobre, avec des surfaces claires et sombres distinctes et le vert Zentra.', 'Navigation, Übersichten und Einstellungen erhalten eine ruhigere Gestaltung mit klar getrennten hellen und dunklen Flächen und dem Zentra-Grün.', 'Navigazione, panoramiche e impostazioni adottano una presentazione più essenziale, con superfici chiare e scure distinte e il verde Zentra.', 'Navigation, dashboards and settings use a calmer layout, with distinct light and dark surfaces and Zentra green.'),
    copy('Le journal Automation reste au premier plan. Les informations secondaires se déplient au besoin ; les achats, la comptabilité et les listes de documents sont plus faciles à parcourir.', 'Das Automation-Journal bleibt im Mittelpunkt. Zusatzinformationen lassen sich bei Bedarf öffnen; Einkauf, Buchhaltung und Dokumentlisten sind übersichtlicher.', 'Il registro Automation resta in primo piano. Le informazioni secondarie si aprono quando servono; acquisti, contabilità ed elenchi dei documenti sono più facili da consultare.', 'The Automation journal stays prominent. Supporting information expands when needed; purchases, accounting and document lists are easier to browse.'),
    copy('Sur téléphone, les commandes et les listes disposent de plus de place. Le mouvement réduit est respecté et les actions restent accessibles dans les petits écrans.', 'Auf dem Smartphone haben Bedienelemente und Listen mehr Platz. Reduzierte Bewegung wird berücksichtigt, und Aktionen bleiben auf kleinen Bildschirmen erreichbar.', 'Sul telefono, comandi ed elenchi hanno più spazio. Il movimento ridotto viene rispettato e le azioni restano accessibili sugli schermi piccoli.', 'On phones, controls and lists have more room. Reduced motion is respected and actions stay accessible on small screens.'),
    copy('Le panneau Compte affiche la connexion enregistrée sans attendre le réseau. Les vérifications simultanées sont regroupées et Automation charge ses données indépendantes en parallèle.', 'Der Kontobereich zeigt die gespeicherte Verbindung, ohne auf das Netzwerk zu warten. Gleichzeitige Prüfungen werden gebündelt und Automation lädt unabhängige Daten parallel.', 'Il pannello Account mostra la connessione salvata senza attendere la rete. Le verifiche simultanee vengono raggruppate e Automation carica i dati indipendenti in parallelo.', 'The Account panel displays the saved connection without waiting for the network. Concurrent checks are combined and Automation loads independent data in parallel.'),
  ] },
  { version: '1.85.1', title: copy('Votre espace s’ouvre plus vite', 'Ihr Arbeitsbereich öffnet sich schneller', 'Il tuo spazio si apre più velocemente', 'Your workspace opens faster'), changes: [
    copy('L’entreprise déjà reliée s’ouvre à partir de la session sécurisée de cet appareil. Le compte est vérifié en arrière-plan.', 'Das bereits verbundene Unternehmen öffnet sich über die geschützte Sitzung dieses Geräts. Das Konto wird im Hintergrund geprüft.', 'L’azienda già collegata si apre dalla sessione protetta del dispositivo. L’account viene verificato in background.', 'Your linked company opens using this device’s protected session. Your account is checked in the background.'),
    copy('Automation se charge sans attendre la vérification du compte. Les demandes répétées au retour dans l’app sont regroupées.', 'Automation lädt, ohne auf die Kontoprüfung zu warten. Wiederholte Anfragen bei der Rückkehr zur App werden gebündelt.', 'Automation si carica senza attendere la verifica dell’account. Le richieste ripetute al ritorno nell’app vengono raggruppate.', 'Automation loads without waiting for the account check. Repeated requests when returning to the app are combined.'),
    copy('Une ancienne réponse de connexion ne peut plus remplacer un compte qui vient d’être changé ou déconnecté.', 'Eine verspätete Anmeldeantwort kann ein inzwischen gewechseltes oder abgemeldetes Konto nicht mehr ersetzen.', 'Una risposta di accesso tardiva non può più sostituire un account appena cambiato o disconnesso.', 'A late sign-in response can no longer replace an account that has just been switched or signed out.'),
  ] },
  { version: '1.85.0', title: copy('Un espace plus clair, partout', 'Ein übersichtlicher Arbeitsplatz, überall', 'Uno spazio più chiaro, ovunque', 'A clearer workspace, everywhere'), changes: [
    copy('Navigation, tableaux, formulaires et paramètres redessinés avec des surfaces sobres et des contrastes harmonisés.', 'Navigation, Tabellen, Formulare und Einstellungen mit ruhigen Flächen und abgestimmten Kontrasten neu gestaltet.', 'Navigazione, tabelle, moduli e impostazioni ridisegnati con superfici sobrie e contrasti coerenti.', 'Redesigned navigation, tables, forms and settings with calm surfaces and consistent contrast.'),
    copy('Les chiffres de votre entreprise apparaissent en premier. Le bilan Automation est plus compact, avec les actions à ouvrir au besoin.', 'Ihre Unternehmenszahlen stehen an erster Stelle. Der Automation-Bericht ist kompakter; offene Aufgaben lassen sich bei Bedarf einblenden.', 'I dati aziendali vengono prima. Il riepilogo Automation è più compatto, con le azioni da aprire quando servono.', 'Company figures come first. The Automation summary is more compact, with pending actions available on demand.'),
    copy('Sur mobile, les listes, les menus et les étapes de saisie s’adaptent aux petits écrans. Les devis et factures disposent de libellés et d’erreurs traduits.', 'Auf Mobilgeräten passen sich Listen, Menüs und Eingabeschritte an kleine Bildschirme an. Offerten und Rechnungen zeigen übersetzte Beschriftungen und Fehlermeldungen.', 'Su mobile, liste, menu e passaggi di inserimento si adattano agli schermi piccoli. Preventivi e fatture hanno etichette ed errori tradotti.', 'On mobile, lists, menus and form steps adapt to smaller screens. Quotes and invoices have translated labels and errors.'),
  ] },
  {version:'1.84.0',title:copy('Votre nouvel espace Automation','Ihr neuer Automation-Bereich','Il tuo nuovo spazio Automation','Your new Automation workspace'),changes:[
    copy('Le journal présente les dernières opérations par date, avec recherche, filtres et détails à ouvrir.','Das Journal zeigt die letzten Vorgänge nach Datum, mit Suche, Filtern und aufklappbaren Details.','Il registro mostra le ultime operazioni per data, con ricerca, filtri e dettagli da aprire.','The journal shows recent operations by date, with search, filters and expandable details.'),
    copy('Les éléments à suivre et les réglages ont chacun leur espace. Le bilan du jour reste accessible à côté de l’activité.','Offene Aufgaben und Einstellungen haben eigene Bereiche. Die Tagesübersicht bleibt neben den Aktivitäten erreichbar.','Le attività da seguire e le impostazioni hanno spazi dedicati. Il riepilogo del giorno resta accessibile accanto alle attività.','Follow-up and settings have their own spaces. The daily summary remains accessible alongside activity.'),
    copy('Menus épurés, couleurs claires et sombres harmonisées, présentation adaptée aux petits écrans.','Aufgeräumte Menüs, abgestimmte helle und dunkle Farben und eine für kleine Bildschirme angepasste Darstellung.','Menu più essenziali, colori chiari e scuri armonizzati e una presentazione adatta ai piccoli schermi.','Cleaner menus, coordinated light and dark colors, and a layout adapted to small screens.')
  ]},
  {version:'1.83.0',title:copy('Un abonnement, une vue claire','Ihr Abonnement auf einen Blick','Un abbonamento, una vista chiara','Your subscription at a glance'),changes:[
    copy('Consultez les produits actifs, l’échéance, les places et les analyses restantes dans Compte → Abonnement.','Unter Konto → Abonnement sehen Sie aktive Produkte, Laufzeit, Teamplätze und verbleibende Analysen.','In Account → Abbonamento trovi prodotti attivi, scadenza, posti e analisi rimanenti.','See active products, renewal, team seats and remaining analyses in Account → Subscription.'),
    copy('Retrouvez le démarrage guidé et ouvrez la gestion sécurisée de votre formule depuis l’application.','Folgen Sie der kurzen Einrichtung und verwalten Sie Ihren Tarif sicher über die App.','Segui la guida iniziale e apri la gestione sicura del piano dall’app.','Follow the short setup guide and open secure plan management from the app.')
  ]},
  {version:'1.82.0',title:copy('Automation, plus clair au quotidien','Automation im Alltag übersichtlicher','Automation più chiaro ogni giorno','A clearer Automation workspace'),changes:[
    copy('Aujourd’hui réunit les éléments à vérifier et les résultats réels de la journée. Le suivi et les réglages ont leurs propres vues.','Heute zeigt offene Prüfungen und tatsächliche Tagesergebnisse. Aktivitäten und Einstellungen haben eigene Ansichten.','Oggi riunisce le verifiche e i risultati reali della giornata. Attività e impostazioni hanno viste separate.','Today brings together pending reviews and actual daily results. Follow-up and settings have separate views.'),
    copy('Le tableau de bord ouvre directement les factures, rendez-vous, tâches ou validations concernés. Les réponses se déplient seulement pour les relire.','Die Übersicht öffnet direkt Rechnungen, Termine, Aufgaben oder Freigaben. Antwortentwürfe werden erst zum Prüfen aufgeklappt.','La panoramica apre direttamente fatture, appuntamenti, attività o verifiche. Le risposte si espandono solo per rileggerle.','The dashboard opens the relevant invoices, appointments, tasks or reviews directly. Draft replies expand only when needed.'),
    copy('Ouvrir Support conserve l’entreprise active de Gestion. La connexion au site ne se coupe plus lorsqu’un ancien onglet de changement de compte reste ouvert.','Support behält das aktive Gestion-Unternehmen bei. Alte Kontowechsel-Tabs melden die Website nicht mehr automatisch ab.','Support mantiene l’azienda attiva di Gestion. Le vecchie schede per cambiare account non disconnettono più il sito.','Support keeps the active Gestion company. Old account-switching tabs no longer sign the website out automatically.')
  ]},
  { version:'1.81.0',title:copy('Vos règles et votre suivi Automation','Ihre Automation-Regeln und Aktivitäten','Regole e attività Automation','Your Automation rules and activity'),changes:[
    copy('Un centre partagé réunit les tâches, brouillons de réponses et validations issus de vos règles de messagerie.','Eine gemeinsame Zentrale bündelt Aufgaben, Antwortentwürfe und Freigaben aus Ihren E-Mail-Regeln.','Un centro condiviso riunisce attività, bozze di risposta e verifiche delle regole email.','A shared centre brings together tasks, reply drafts and reviews from your mail rules.'),
    copy('Choisissez les conditions, le destinataire, les délais et le niveau d’autonomie. Le mode observation permet de vérifier une règle avant de la laisser agir.','Wählen Sie Bedingungen, Empfänger, Verzögerungen und Autonomie. Der Beobachtungsmodus prüft Regeln ohne Änderungen.','Scegli condizioni, destinatario, tempi e autonomia. La modalità osservazione verifica le regole senza modifiche.','Choose conditions, assignees, delays and autonomy. Observation mode tests rules without making changes.'),
    copy('Les résumés reprennent des extraits des messages reçus. Les brouillons sont personnalisables et partagés, sans envoi automatique.','Zusammenfassungen übernehmen Auszüge empfangener Nachrichten. Entwürfe sind anpassbar und gemeinsam verfügbar, ohne automatischen Versand.','I riepiloghi riportano estratti dei messaggi ricevuti. Le bozze sono personalizzabili e condivise, senza invio automatico.','Summaries use excerpts from received messages. Drafts can be customized and shared, without automatic sending.'),
    copy('Le bilan quotidien affiche les tâches et réponses réellement préparées. Les reprises évitent les doublons et respectent les droits de votre entreprise.','Der Tagesbericht zeigt tatsächlich vorbereitete Aufgaben und Antworten. Wiederholungen vermeiden Duplikate und beachten Unternehmensrechte.','Il riepilogo giornaliero mostra attività e risposte effettivamente preparate. Le riprese evitano duplicati e rispettano i permessi aziendali.','The daily brief shows tasks and replies actually prepared. Retries avoid duplicates and respect company permissions.'),
  ]},
  { version: '1.80.3', title: copy('Le bon espace, sur chaque appareil', 'Der richtige Arbeitsbereich auf jedem Gerät', 'Lo spazio giusto su ogni dispositivo', 'The right workspace on every device'), changes: [
    copy('Choisissez l’espace à ouvrir sans remplacer une entreprise locale sans confirmation. Documents et Automation suivent l’espace sélectionné.', 'Wählen Sie den Arbeitsbereich, ohne ein lokales Unternehmen ohne Bestätigung zu ersetzen. Dokumente und Automation gehören zum gewählten Arbeitsbereich.', 'Scegli lo spazio senza sostituire un’azienda locale senza conferma. Documenti e Automation seguono lo spazio selezionato.', 'Choose a workspace without replacing a local company without confirmation. Documents and Automation follow the selected workspace.'),
    copy('Les collaborateurs renseignent leur prénom et leur nom à l’invitation. L’auteur du devis apparaît comme interlocuteur dans l’aperçu et le PDF.', 'Mitarbeitende geben bei der Einladung Vor- und Nachnamen an. Die erstellende Person erscheint als Ansprechperson auf der Offerte und im PDF.', 'I collaboratori indicano nome e cognome quando accettano l’invito. L’autore del preventivo appare come referente nell’anteprima e nel PDF.', 'Collaborators enter their first and last name when joining. The quote author appears as the contact person in the preview and PDF.'),
    copy('Achats, paie, compte et réglages Automation sont plus lisibles sur ordinateur et mobile, avec moins de texte répété et des actions de correction directes.', 'Einkauf, Lohn, Konto und Automation-Einstellungen sind auf Computer und Mobilgerät übersichtlicher, mit weniger Wiederholungen und direkten Korrekturmöglichkeiten.', 'Acquisti, stipendi, conto e impostazioni Automation sono più chiari su computer e mobile, con meno testo ripetuto e azioni di correzione dirette.', 'Purchases, payroll, account and Automation settings are clearer on desktop and mobile, with less repeated text and direct correction actions.'),
    copy('Automation est une option à 15 CHF/mois propre à chaque espace et partagée avec son équipe. Les fonctions manuelles restent disponibles sans cette option.', 'Automation ist eine Option für 15 CHF/Monat pro Arbeitsbereich und wird im Team geteilt. Manuelle Funktionen bleiben ohne diese Option verfügbar.', 'Automation è un’opzione da 15 CHF/mese per spazio, condivisa con il team. Le funzioni manuali restano disponibili senza questa opzione.', 'Automation is a CHF 15/month option per workspace, shared with its team. Manual features remain available without this option.'),
  ] },
  { version: '1.80.2', title: copy('Vos factures, préparées ensemble', 'Ihre Rechnungen gemeinsam vorbereiten', 'Le tue fatture, preparate insieme', 'Prepare your invoices together'), changes: [
    copy('« Vérifier toutes les factures » retrouve ou crée les fournisseurs reconnus en une seule action, y compris lorsque le type de document reste à confirmer. Les identités incertaines demandent toujours une vérification.', '« Alle Rechnungen prüfen » erkennt oder erstellt Lieferanten in einem Schritt, auch wenn die Dokumentart noch bestätigt werden muss. Unklare Identitäten müssen weiterhin geprüft werden.', '« Verifica tutte le fatture » trova o crea i fornitori riconosciuti in un’unica azione, anche quando il tipo di documento va confermato. Le identità incerte richiedono ancora una verifica.', '“Check all invoices” finds or creates recognised suppliers in one action, even when the document type still needs confirmation. Uncertain identities still require review.'),
    copy('Une facture incomplète ne bloque plus les autres. Son fournisseur est préparé dès qu’il est reconnu, sans valider automatiquement ses montants.', 'Eine unvollständige Rechnung blockiert die anderen nicht mehr. Ihr Lieferant wird vorbereitet, sobald er erkannt ist, ohne die Beträge automatisch zu bestätigen.', 'Una fattura incompleta non blocca più le altre. Il fornitore viene preparato appena riconosciuto, senza confermare automaticamente gli importi.', 'An incomplete invoice no longer blocks the others. Its supplier is prepared once identified, without automatically approving its amounts.'),
    copy('Un résumé compact remplace la longue liste de messages. Les factures préparées et les points à compléter restent accessibles sur ordinateur et mobile.', 'Eine kompakte Zusammenfassung ersetzt die lange Meldungsliste. Vorbereitete Rechnungen und offene Punkte bleiben auf Computer und Mobilgerät zugänglich.', 'Un riepilogo compatto sostituisce il lungo elenco di messaggi. Le fatture preparate e i dati da completare restano accessibili su computer e mobile.', 'A compact summary replaces the long message list. Prepared invoices and remaining details stay accessible on desktop and mobile.'),
  ] },
  { version: '1.80.1', title: copy('Les fournisseurs se préparent seuls', 'Lieferanten werden automatisch vorbereitet', 'Fornitori preparati automaticamente', 'Suppliers prepared automatically'), changes: [
    copy('Avec Automation actif, les factures reçues retrouvent automatiquement leur fournisseur ou créent sa fiche lorsque son identité est certaine. Un choix reste demandé en cas de doute ou de doublon.', 'Mit aktivem Automation wird der Lieferant eingegangener Rechnungen automatisch erkannt oder bei eindeutiger Identität angelegt. Bei Unsicherheit oder Duplikaten bleibt eine Auswahl erforderlich.', 'Con Automation attivo, le fatture ricevute vengono associate al fornitore esistente oppure ne creano la scheda se l’identità è certa. In caso di dubbi o duplicati viene richiesta una scelta.', 'With Automation enabled, received invoices automatically find their supplier or create a supplier record when the identity is clear. Ambiguous or duplicate matches still require a choice.'),
    copy('Un montant ou un classement à vérifier ne bloque plus la préparation du fournisseur. La vérification comptable reste distincte.', 'Ein zu prüfender Betrag oder eine Zuordnung blockiert die Lieferantenvorbereitung nicht mehr. Die Buchhaltungsprüfung bleibt unabhängig.', 'Un importo o una categoria da verificare non blocca più la preparazione del fornitore. La verifica contabile resta separata.', 'An amount or category requiring review no longer blocks supplier preparation. Accounting checks remain separate.'),
    copy('Support reconnaît les fichiers calendrier joints ou intégrés dans les e-mails et évite de traiter deux copies identiques comme un document illisible.', 'Support erkennt angehängte und eingebettete Kalenderdateien und behandelt identische Kopien nicht als unlesbares Dokument.', 'Support riconosce i calendari allegati o incorporati nelle e-mail e non considera illeggibili due copie identiche.', 'Support recognises attached or embedded calendar files and no longer treats identical copies as an unreadable document.'),
  ] },
  { version: '1.80.0', title: copy('Votre réception devient utile', 'Ihr Posteingang unterstützt Sie', 'La posta ricevuta diventa utile', 'Put your inbox to work'), changes: [
    copy('Les confirmations de rendez-vous reconnues par Support rejoignent l’agenda à l’ouverture de Gestion avec Automation actif. Les horaires incomplets, annulations et modifications restent à vérifier.', 'Von Support erkannte Terminbestätigungen werden beim Öffnen von Gestion mit aktivem Automation in den Kalender übernommen. Unvollständige Zeiten, Absagen und Änderungen bleiben zur Prüfung offen.', 'Le conferme di appuntamento riconosciute da Support passano all’agenda all’apertura di Gestion con Automation attivo. Orari incompleti, annullamenti e modifiche restano da verificare.', 'Appointment confirmations recognised by Support reach the calendar when Gestion opens with Automation enabled. Incomplete times, cancellations and updates remain for review.'),
    copy('Vérifiez plusieurs factures reçues ensemble. Automation retrouve ou prépare les fournisseurs et réutilise les classements que votre équipe a confirmés. Les habitudes sont visibles et peuvent être oubliées dans les réglages.', 'Prüfen Sie mehrere eingegangene Rechnungen gemeinsam. Automation findet oder bereitet Lieferanten vor und verwendet bestätigte Zuordnungen erneut. Gespeicherte Zuordnungen sind in den Einstellungen einsehbar und löschbar.', 'Verifica insieme più fatture ricevute. Automation trova o prepara i fornitori e riutilizza le classificazioni confermate dal team. Le preferenze sono visibili ed eliminabili nelle impostazioni.', 'Review multiple received invoices together. Automation finds or prepares suppliers and reuses classifications confirmed by your team. Remembered preferences can be viewed and removed in settings.'),
    copy('Le tableau de bord affiche le chiffre d’affaires facturé hors TVA de l’année. Rapports permet de choisir les rubriques d’un projet et d’exporter un PDF détaillé, avec son logo et sa mise en page.', 'Die Übersicht zeigt den fakturierten Jahresumsatz ohne MWST. Unter Berichte wählen Sie Projektbereiche und exportieren einen ausführlichen PDF-Bericht mit Firmenlogo und Layout.', 'La panoramica mostra il fatturato annuo al netto dell’IVA. In Rapporti puoi scegliere le sezioni del progetto ed esportare un PDF dettagliato con logo e impaginazione aziendale.', 'The dashboard shows annual invoiced revenue excluding VAT. Reports lets you choose project sections and export a detailed PDF using your company logo and layout.'),
  ] },
  { version: '1.79.1', title: copy('Votre entreprise sur chaque appareil', 'Ihr Unternehmen auf jedem Gerät', 'La tua azienda su ogni dispositivo', 'Your company on every device'), changes: [
    copy('La connexion récupère automatiquement l’entreprise du compte sur un appareil vide. Une nouvelle entreprise créée avec un compte connecté active son envoi automatiquement.', 'Die Anmeldung lädt das Unternehmen des Kontos automatisch auf ein leeres Gerät. Neu erstellte Unternehmen mit verbundenem Konto werden automatisch übertragen.', 'L’accesso recupera automaticamente l’azienda del conto su un dispositivo vuoto. Una nuova azienda creata con un conto collegato viene inviata automaticamente.', 'Signing in automatically retrieves the account’s company on an empty device. New companies created with a connected account are uploaded automatically.'),
    copy('Si une ancienne entreprise existe déjà sur l’appareil, un choix clair permet d’ouvrir celle du compte en conservant une sauvegarde locale de l’ancienne.', 'Ist bereits ein anderes Unternehmen auf dem Gerät vorhanden, können Sie das Unternehmen des Kontos öffnen. Das bisherige Unternehmen wird lokal gesichert.', 'Se sul dispositivo esiste già un’altra azienda, puoi aprire quella del conto conservando un backup locale della precedente.', 'If the device already contains another company, you can open the account’s company while keeping a local backup of the previous one.'),
  ] },
  { version: '1.79.0', title: copy('Automation, au cœur de votre journée', 'Automation im Mittelpunkt Ihres Tages', 'Automation al centro della tua giornata', 'Automation at the heart of your day'), changes: [
    copy('Les factures reçues se vérifient directement dans Automation. Retrouvez les documents à traiter, recherchez un fournisseur ou une référence et consultez les factures déjà enregistrées.', 'Prüfen Sie eingegangene Rechnungen direkt in Automation. Finden Sie offene Dokumente, suchen Sie nach Lieferanten oder Referenzen und sehen Sie erfasste Rechnungen ein.', 'Verifica le fatture ricevute direttamente in Automation. Trova i documenti da elaborare, cerca fornitori o riferimenti e consulta le fatture registrate.', 'Review received invoices directly in Automation. Find pending documents, search suppliers or references and view recorded invoices.'),
    copy('Après une validation, restez dans la liste pour poursuivre. Le menu indique les documents en attente et le tableau de bord présente un bilan quotidien plus compact.', 'Nach einer Bestätigung bleiben Sie in der Liste. Das Menü zeigt offene Dokumente und die Übersicht einen kompakteren Tagesbericht.', 'Dopo una conferma resti nella lista. Il menu indica i documenti in attesa e la panoramica mostra un riepilogo giornaliero più compatto.', 'Stay in the list after confirming an invoice. The menu shows pending documents and the dashboard presents a more compact daily summary.'),
    copy('Les outils et réglages partagés sont organisés en listes lisibles, avec des commandes adaptées au téléphone et aux thèmes clair et sombre.', 'Gemeinsame Werkzeuge und Einstellungen sind in übersichtlichen Listen mit mobilfreundlichen Bedienelementen für das helle und dunkle Design angeordnet.', 'Strumenti e impostazioni condivisi sono organizzati in liste leggibili, con comandi adatti al telefono e ai temi chiaro e scuro.', 'Shared tools and settings are arranged in readable lists with phone-friendly controls in light and dark themes.'),
  ] },
  { version: '1.78.0', title: copy('Automation vous prépare la suite', 'Automation bereitet den nächsten Schritt vor', 'Automation prepara il prossimo passo', 'Automation prepares your next step'), changes: [
    copy('Les factures reçues présentent un résumé et leur justificatif. Vérifiez puis confirmez pour enregistrer la facture et son écriture comptable ensemble, ou gardez un brouillon.', 'Eingegangene Rechnungen zeigen eine Zusammenfassung und den Beleg. Prüfen und bestätigen Sie, um Rechnung und Buchung gemeinsam zu erfassen, oder speichern Sie einen Entwurf.', 'Le fatture ricevute mostrano un riepilogo e il documento. Verifica e conferma per registrare insieme fattura e scrittura contabile, oppure conserva una bozza.', 'Received invoices show a summary and their source document. Review and confirm to record the invoice and accounting entry together, or keep a draft.'),
    copy('Ajoutez un fournisseur directement pendant la vérification, sans perdre vos modifications. Le tableau de bord montre les documents à vérifier et les derniers enregistrements.', 'Fügen Sie während der Prüfung einen Lieferanten hinzu, ohne Ihre Änderungen zu verlieren. Die Übersicht zeigt zu prüfende Dokumente und die letzten Erfassungen.', 'Aggiungi un fornitore durante la verifica senza perdere le modifiche. La panoramica mostra i documenti da verificare e le ultime registrazioni.', 'Add a supplier while reviewing without losing your edits. The dashboard shows documents needing review and recently recorded entries.'),
    copy('Sur mobile, les boutons de correction et les onglets Automation laissent davantage de place aux libellés, y compris en allemand.', 'Auf Mobilgeräten bieten Korrekturschaltflächen und Automation-Tabs mehr Platz für Beschriftungen, auch auf Deutsch.', 'Su mobile, i pulsanti di correzione e le schede Automation lasciano più spazio alle etichette, anche in tedesco.', 'On mobile, correction buttons and Automation tabs allow more space for labels, including German.'),
  ] },
  { version: '1.77.0', title: copy('Votre nouvel espace compte', 'Ihr neuer Kontobereich', 'Il tuo nuovo spazio account', 'Your new account space'), changes: [
    copy('Retrouvez votre profil, la sécurité, l’abonnement et les appareils depuis des raccourcis simples, adaptés au mobile.', 'Profil, Sicherheit, Abonnement und Geräte sind über einfache, mobilfreundliche Verknüpfungen erreichbar.', 'Accedi a profilo, sicurezza, abbonamento e dispositivi da collegamenti semplici, adatti al mobile.', 'Reach your profile, security, subscription and devices through simple mobile-friendly shortcuts.'),
    copy('Les nouvelles sauvegardes utilisent le format .zentra Phase 2. Les sauvegardes des anciennes versions sont refusées, même renommées.', 'Neue Sicherungen verwenden das Phase-2-Format .zentra. Sicherungen früherer Versionen werden auch nach Umbenennung abgelehnt.', 'I nuovi backup usano il formato .zentra Fase 2. I backup precedenti vengono rifiutati anche se rinominati.', 'New backups use the Phase 2 .zentra format. Older backups are rejected even if renamed.'),
    copy('Les réglages Automation détectent les modifications concurrentes pour éviter d’effacer le choix d’un collègue.', 'Automation-Einstellungen erkennen gleichzeitige Änderungen, damit die Auswahl eines Kollegen nicht überschrieben wird.', 'Le impostazioni Automation rilevano modifiche simultanee per non sovrascrivere le scelte dei colleghi.', 'Automation settings detect concurrent changes to avoid overwriting a colleague’s choices.'),
  ] },
  { version: '1.76.0', title: copy('De la boîte mail à vos achats', 'Vom Postfach zu Ihren Einkäufen', 'Dalla posta ai tuoi acquisti', 'From your mailbox to purchases'), changes: [
    copy('Reliez la boîte Infomaniak de Zentra Support à votre entreprise Gestion. Les justificatifs fournisseurs sont partagés dans Achats, avec le document original et une vérification avant validation.', 'Verbinden Sie das Infomaniak-Postfach von Zentra Support mit Ihrem Gestion-Unternehmen. Lieferantenbelege erscheinen unter Einkäufe mit dem Originaldokument und einer Prüfung vor der Buchung.', 'Collega la casella Infomaniak di Zentra Support alla tua azienda Gestion. I giustificativi dei fornitori sono condivisi in Acquisti, con originale e verifica prima della registrazione.', 'Link your Zentra Support Infomaniak mailbox to your Gestion company. Supplier documents are shared in Purchases, with the original and a review before posting.'),
    copy('Avec Automation et votre accord, les factures cohérentes de fournisseurs connus reprennent le compte de charges déjà validé. Les documents incertains restent à vérifier ; aucun paiement n’est déclenché.', 'Mit Automation und Ihrer Zustimmung übernehmen stimmige Rechnungen bekannter Lieferanten das bereits bestätigte Aufwandskonto. Unsichere Belege bleiben zur Prüfung; es wird keine Zahlung ausgelöst.', 'Con Automation e il tuo consenso, le fatture coerenti di fornitori conosciuti usano il conto di costo già approvato. I documenti incerti restano da verificare; nessun pagamento viene avviato.', 'With Automation and your consent, consistent invoices from known suppliers use the previously approved expense account. Uncertain documents remain for review; no payment is initiated.'),
    copy('Le bilan du jour indique les factures reçues, comptabilisées et à vérifier. L’extraction concerne les PDF contenant du texte ; les scans se complètent manuellement. Gestion doit être ouverte pour terminer la comptabilisation.', 'Die Tagesübersicht zeigt eingegangene, gebuchte und zu prüfende Rechnungen. Die Extraktion verarbeitet PDFs mit Text; Scans werden manuell ergänzt. Gestion muss geöffnet sein, um die Buchung abzuschliessen.', 'Il riepilogo del giorno mostra fatture ricevute, registrate e da verificare. L’estrazione riguarda i PDF con testo; le scansioni vanno completate manualmente. Gestion deve essere aperto per completare la registrazione.', 'The daily summary shows received, posted and pending invoices. Extraction supports PDFs containing text; scans need manual completion. Gestion must be open to finish posting.'),
  ] },
  { version: '1.75.0', title: copy('Une synchronisation plus légère', 'Effizientere Synchronisierung', 'Una sincronizzazione più leggera', 'Lighter synchronization'), changes: [
    copy('Les changements de votre équipe arrivent automatiquement en arrière-plan. Les vérifications répétées sont réduites lorsque la connexion en temps réel fonctionne.', 'Änderungen Ihres Teams werden automatisch im Hintergrund übernommen. Bei aktiver Echtzeitverbindung werden wiederholte Prüfungen reduziert.', 'Le modifiche del team arrivano automaticamente in background. Le verifiche ripetute sono ridotte quando la connessione in tempo reale funziona.', 'Team changes arrive automatically in the background. Repeated checks are reduced while the real-time connection is working.'),
    copy('Les parties inchangées des données et documents sont réutilisées : seuls les blocs manquants sont transférés lors des prochaines synchronisations.', 'Unveränderte Daten- und Dokumentteile werden wiederverwendet: Bei folgenden Synchronisierungen werden nur fehlende Blöcke übertragen.', 'Le parti invariate dei dati e dei documenti vengono riutilizzate: nelle sincronizzazioni successive vengono trasferiti solo i blocchi mancanti.', 'Unchanged data and document parts are reused: subsequent synchronizations transfer only missing blocks.'),
    copy('Après une interruption, les envois reprennent automatiquement. Les contrôles des encaissements, des droits d’accès et des modifications simultanées sont conservés.', 'Nach einer Unterbrechung werden Übertragungen automatisch fortgesetzt. Prüfungen für Zahlungen, Zugriffsrechte und gleichzeitige Änderungen bleiben erhalten.', 'Dopo un’interruzione, gli invii riprendono automaticamente. Restano attivi i controlli su incassi, permessi di accesso e modifiche simultanee.', 'Transfers resume automatically after an interruption. Payment, access permission and simultaneous edit checks remain in place.'),
  ] },
  { version: '1.74.1', title: copy('Une connexion Automation plus claire', 'Klarere Automation-Verbindung', 'Una connessione Automation più chiara', 'Clearer Automation connection'), changes: [
    copy('Automation distingue une entreprise mal reliée, une session expirée, un service indisponible et une coupure réseau. Le message ne vous demande plus de vous connecter à Internet pour un problème de compte.', 'Automation unterscheidet eine falsche Unternehmenszuordnung, eine abgelaufene Sitzung, einen nicht verfügbaren Dienst und eine Netzwerkunterbrechung.', 'Automation distingue un’azienda collegata in modo errato, una sessione scaduta, un servizio non disponibile e un’interruzione di rete.', 'Automation distinguishes a company mismatch, an expired session, an unavailable service and a network interruption.'),
    copy('Un bouton ouvre directement Compte et équipe pour corriger le lien, sans mélanger les données de deux entreprises.', 'Eine Schaltfläche öffnet Konto und Team, um die Zuordnung ohne Vermischen der Unternehmensdaten zu korrigieren.', 'Un pulsante apre Account e team per correggere il collegamento senza mescolare i dati di due aziende.', 'A button opens Account and team to correct the link without mixing two companies’ data.'),
  ] },
  { version: '1.74.0', title: copy('Votre espace Zentra Automation', 'Ihr Zentra Automation-Bereich', 'Il tuo spazio Zentra Automation', 'Your Zentra Automation workspace'), changes: [
    copy('Un espace dédié apparaît dans le menu dès que l’entreprise dispose d’Automation : activité, outils et réglages partagés.', 'Ein eigener Bereich erscheint im Menü, sobald das Unternehmen Automation hat: Aktivitäten, Werkzeuge und gemeinsame Einstellungen.', 'Uno spazio dedicato appare nel menu quando l’azienda dispone di Automation: attività, strumenti e impostazioni condivise.', 'A dedicated space appears in the menu when your company has Automation: activity, tools and shared settings.'),
    copy('Démarrez avec les réglages conseillés et retrouvez les outils liés à la banque, aux documents, aux achats, aux factures et au catalogue.', 'Starten Sie mit empfohlenen Einstellungen und finden Sie Werkzeuge für Bank, Dokumente, Einkäufe, Rechnungen und Katalog.', 'Inizia con le impostazioni consigliate e trova gli strumenti per banca, documenti, acquisti, fatture e catalogo.', 'Start with recommended settings and find tools for banking, documents, purchases, invoices and catalog.'),
    copy('Des états clairs pour la configuration, les pauses et la connexion. Les droits de chaque rôle restent appliqués sur ordinateur et mobile.', 'Klare Zustände für Einrichtung, Pausen und Verbindung. Die Rollenrechte gelten weiterhin auf Computer und Mobilgerät.', 'Stati chiari per configurazione, pause e connessione. I diritti di ogni ruolo restano applicati su computer e mobile.', 'Clear setup, paused and connection states. Role permissions are preserved on desktop and mobile.'),
  ] },
  { version: '1.73.0', title: copy('Automation pour toute votre équipe', 'Automation für Ihr ganzes Team', 'Automation per tutto il team', 'Automation for your whole team'), changes: [
    copy('Une seule activation par entreprise. Chaque collaborateur profite des fonctions actives avec ses droits habituels.', 'Eine Aktivierung pro Unternehmen. Alle Mitarbeitenden nutzen die aktiven Funktionen mit ihren bestehenden Rechten.', 'Un’attivazione per azienda. Tutti i collaboratori usano le funzioni attive con i propri permessi.', 'One activation per company. Every collaborator benefits from active features with their existing permissions.'),
    copy('Un bilan quotidien sur l’accueil présente les analyses terminées, les suggestions et les choix confirmés par l’équipe. Il se met à jour en arrière-plan.', 'Eine Tagesübersicht zeigt abgeschlossene Analysen, Vorschläge und bestätigte Auswahlen des Teams. Sie wird im Hintergrund aktualisiert.', 'Il riepilogo giornaliero mostra analisi, suggerimenti e scelte confermate dal team, aggiornandosi in background.', 'A daily summary shows completed analyses, suggestions and choices confirmed by the team, updating in the background.'),
    copy('Réglages partagés directement dans l’application et outils contextuels repliables, adaptés au mobile et à l’ordinateur.', 'Gemeinsame Einstellungen direkt in der App und einklappbare Werkzeuge für Mobilgeräte und Computer.', 'Impostazioni condivise nell’app e strumenti contestuali richiudibili, adatti a mobile e computer.', 'Shared settings in the app and collapsible contextual tools for mobile and desktop.'),
  ] },
  { version: '1.72.0', title: copy('Zentra Automation, à votre rythme', 'Zentra Automation in Ihrem Tempo', 'Zentra Automation, al tuo ritmo', 'Zentra Automation at your pace'), changes: [
    copy('Une option facultative à 15 CHF par mois par entreprise, présentée pendant la configuration et accessible dans les paramètres.', 'Eine freiwillige Option für 15 CHF pro Monat und Unternehmen, in der Einrichtung und den Einstellungen verfügbar.', 'Un’opzione facoltativa a 15 CHF al mese per azienda, disponibile durante la configurazione e nelle impostazioni.', 'An optional CHF 15 monthly add-on per company, available during setup and in settings.'),
    copy('Suggestions pour classer les opérations et documents, préparer les achats et choisir les colonnes des imports. Vous vérifiez avant d’enregistrer.', 'Vorschläge zum Einordnen von Buchungen und Dokumenten, Vorbereiten von Einkäufen und Zuordnen von Importspalten. Sie prüfen vor dem Speichern.', 'Suggerimenti per classificare operazioni e documenti, preparare gli acquisti e abbinare le colonne degli import. Verifica prima di salvare.', 'Suggestions for transactions, documents, purchases and import columns. Review before saving.'),
    copy('Activation depuis le compte en ligne après votre accord. Les opérations manuelles et l’assistant local restent disponibles.', 'Aktivierung im Online-Konto nach Ihrer Zustimmung. Manuelle Abläufe und der lokale Assistent bleiben verfügbar.', 'Attivazione dall’account online con il tuo consenso. Operazioni manuali e assistente locale restano disponibili.', 'Activate from your online account with consent. Manual workflows and the local assistant remain available.'),
  ] },
  { version: '1.71.1', title: copy('Un mode sombre plus clair, un partage discret', 'Klarere dunkle Darstellung und dezente Synchronisierung', 'Tema scuro più chiaro e sincronizzazione discreta', 'Clearer dark mode and discreet syncing'), changes: [
    copy('Sur mobile et ordinateur, les panneaux sombres sont mieux séparés. Les icônes des paramètres suivent le même style et les menus sélectionnés utilisent un fond neutre avec une touche de vert.', 'Auf Mobilgeräten und Computern sind dunkle Bereiche klarer getrennt. Die Einstellungssymbole sind einheitlich und ausgewählte Menüs haben einen neutralen Hintergrund mit einem grünen Akzent.', 'Su mobile e computer, i pannelli scuri sono meglio separati. Le icone delle impostazioni sono uniformi e i menu selezionati hanno uno sfondo neutro con un accento verde.', 'On mobile and desktop, dark panels are easier to distinguish. Settings icons share a consistent style, and selected menus use a neutral background with a green accent.'),
    copy('Les données de votre équipe se mettent à jour sans panneau de chargement ni voile sur l’écran. La page reste visible pendant la réception.', 'Die Daten Ihres Teams werden ohne Ladefenster oder abgedunkelten Bildschirm aktualisiert. Die Seite bleibt während des Empfangs sichtbar.', 'I dati del team si aggiornano senza pannello di caricamento né oscuramento dello schermo. La pagina resta visibile durante la ricezione.', 'Team data updates without a loading panel or dimmed screen. Your page stays visible while changes arrive.'),
    copy('Les saisies en cours restent protégées et les montants reçus s’actualisent automatiquement. La recherche retrouve son focus après la réception.', 'Laufende Eingaben bleiben geschützt und empfangene Beträge werden automatisch aktualisiert. Nach dem Empfang erhält die Suche ihren Fokus zurück.', 'I dati in compilazione restano protetti e gli importi ricevuti si aggiornano automaticamente. La ricerca riacquista il focus dopo la ricezione.', 'Work in progress stays protected and incoming amounts update automatically. Search focus is restored after receiving changes.'),
  ] },
  { version: '1.71.0', title: copy('Un partage plus fiable, un compte plus simple', 'Zuverlässiger teilen, das Konto einfacher verwalten', 'Condivisione più affidabile, account più semplice', 'More reliable sharing, simpler account settings'), changes: [
    copy('Les changements sur des documents différents sont réunis automatiquement : une facture créée sur un appareil et un paiement enregistré sur un autre peuvent être partagés ensemble.', 'Änderungen an verschiedenen Dokumenten werden automatisch zusammengeführt: Eine Rechnung auf einem Gerät und eine Zahlung auf einem anderen können gemeinsam geteilt werden.', 'Le modifiche a documenti diversi vengono unite automaticamente: una fattura creata su un dispositivo e un pagamento registrato su un altro possono essere condivisi insieme.', 'Changes to different documents merge automatically: an invoice created on one device and a payment recorded on another can be shared together.'),
    copy('Le déplacement du même logo entre Windows et iPhone ne bloque plus le partage. Les copies d’origine et l’historique sont conservés lors de la réunion des changements.', 'Der Speicherort desselben Logos unter Windows und auf dem iPhone blockiert die Freigabe nicht mehr. Originalkopien und Verlauf bleiben beim Zusammenführen erhalten.', 'Il percorso dello stesso logo su Windows e iPhone non blocca più la condivisione. Le copie originali e la cronologia vengono conservate durante l’unione.', 'Moving the same logo between Windows and iPhone no longer blocks sharing. Original copies and history are preserved when changes are merged.'),
    copy('Compte et équipe : un écran plus clair, les invitations à la demande et un état automatique du partage. Les modifications contradictoires d’un même document sont signalées sans remplacer vos données.', 'Konto und Team: eine übersichtlichere Ansicht, Einladungen bei Bedarf und automatischer Freigabestatus. Widersprüchliche Änderungen am selben Dokument werden gemeldet, ohne Ihre Daten zu ersetzen.', 'Account e team: schermata più chiara, inviti quando servono e stato automatico della condivisione. Le modifiche contrastanti allo stesso documento sono segnalate senza sostituire i dati.', 'Account and team: a clearer screen, invitations when needed and automatic sharing status. Conflicting changes to the same document are reported without replacing your data.'),
  ] },
  { version: '1.70.0', title: copy('Votre équipe à jour, votre mobile plus stable', 'Ihr Team auf dem neuesten Stand, eine stabilere mobile Ansicht', 'Team aggiornato e interfaccia mobile più stabile', 'An up-to-date team and a steadier mobile interface'), changes: [
    copy('Quand l’application est ouverte et connectée, elle vérifie les changements de l’équipe toutes les 3 secondes. Les factures et paiements reçus actualisent automatiquement les montants de l’accueil.', 'Bei geöffneter App und bestehender Verbindung werden Teamänderungen alle 3 Sekunden geprüft. Empfangene Rechnungen und Zahlungen aktualisieren die Beträge auf der Startseite automatisch.', 'Con l’app aperta e connessa, le modifiche del team vengono controllate ogni 3 secondi. Fatture e pagamenti ricevuti aggiornano automaticamente gli importi nella schermata iniziale.', 'While the app is open and connected, team changes are checked every 3 seconds. Received invoices and payments automatically update home screen amounts.'),
    copy('Les contrôles de relances sans modification ne bloquent plus la réception. Les saisies en cours et les vrais changements simultanés restent protégés.', 'Mahnungsprüfungen ohne Änderungen blockieren den Empfang nicht mehr. Laufende Eingaben und tatsächliche gleichzeitige Änderungen bleiben geschützt.', 'I controlli dei solleciti senza modifiche non bloccano più la ricezione. I dati in compilazione e le vere modifiche simultanee restano protetti.', 'Reminder checks that change no business data no longer block incoming updates. Unsaved input and genuine concurrent edits remain protected.'),
    copy('Sur mobile, l’interface garde sa taille : boutons et textes s’adaptent à l’écran. Le zoom à deux doigts reste disponible dans les documents.', 'Auf Mobilgeräten bleibt die Oberfläche in ihrer Grösse stabil: Schaltflächen und Texte passen sich dem Bildschirm an. Dokumente lassen sich weiterhin mit zwei Fingern vergrössern.', 'Su mobile l’interfaccia mantiene la sua scala: pulsanti e testi si adattano allo schermo. Lo zoom con due dita resta disponibile nei documenti.', 'On mobile, the interface keeps its scale: buttons and text fit the screen. Two-finger zoom remains available inside documents.'),
  ] },
  { version: '1.69.1', title: copy('Votre compte sur zentraapp.ch', 'Ihr Konto auf zentraapp.ch', 'Il vostro account su zentraapp.ch', 'Your account on zentraapp.ch'), changes: [
    copy('Le compte, la connexion et le renouvellement de la licence utilisent zentraapp.ch. Les anciennes demandes de connexion en cours sont reprises sur la nouvelle adresse.', 'Konto, Anmeldung und Lizenzverlängerung verwenden zentraapp.ch. Bereits gestartete Anmeldungen werden unter der neuen Adresse fortgesetzt.', 'Account, accesso e rinnovo della licenza utilizzano zentraapp.ch. Le richieste di accesso già avviate proseguono al nuovo indirizzo.', 'Account access, sign-in and licence renewal use zentraapp.ch. Pending sign-in requests continue at the new address.'),
  ] },
  { version: '1.69.0', title: copy('Connectés à votre entreprise', 'Mit Ihrem Unternehmen verbunden', 'Connessi alla vostra azienda', 'Connected to your company'), changes: [
    copy('Les modifications enregistrées déclenchent automatiquement leur envoi à l’équipe. Une notification accélère la réception des nouveaux documents et montants.', 'Gespeicherte Änderungen werden automatisch an das Team gesendet. Eine Benachrichtigung beschleunigt den Empfang neuer Dokumente und Beträge.', 'Le modifiche salvate vengono inviate automaticamente al team. Una notifica accelera la ricezione di nuovi documenti e importi.', 'Saved changes automatically start syncing to your team. A notification speeds up receiving new documents and amounts.'),
    copy('La réception reprend après la fermeture d’un formulaire. Les saisies en cours et les modifications concurrentes restent protégées.', 'Der Empfang wird nach dem Schliessen eines Formulars fortgesetzt. Laufende Eingaben und gleichzeitige Änderungen bleiben geschützt.', 'La ricezione riprende alla chiusura del modulo. I dati in compilazione e le modifiche contemporanee restano protetti.', 'Receiving resumes after closing a form. Work in progress and concurrent changes stay protected.'),
    copy('Connectez-vous au compte de votre abonnement pour activer votre licence automatiquement, sans copier de jeton.', 'Melden Sie sich mit Ihrem Abonnementkonto an, um Ihre Lizenz automatisch und ohne kopierten Code zu aktivieren.', 'Accedete con il vostro account di abbonamento per attivare automaticamente la licenza, senza copiare codici.', 'Sign in to your subscription account to activate your licence automatically, without copying a token.'),
  ] },

  { version: '1.68.0', title: copy('Plus d’espace sur mobile', 'Mehr Platz auf dem Smartphone', 'Più spazio sullo smartphone', 'More room on mobile'), changes: [
    copy('Un accueil mobile simplifié : les montants essentiels, les documents récents et les actions du quotidien.', 'Eine einfachere mobile Startseite: die wichtigsten Beträge, aktuelle Dokumente und alltägliche Aktionen.', 'Una schermata iniziale mobile più semplice: importi essenziali, documenti recenti e azioni quotidiane.', 'A simpler mobile home: key amounts, recent documents and everyday actions.'),
    copy('Devis, factures, projets et salaires : moins de texte à l’écran, avec les détails et les actions supplémentaires accessibles au toucher.', 'Angebote, Rechnungen, Projekte und Löhne: weniger Text auf dem Bildschirm, Details und weitere Aktionen per Fingertipp.', 'Preventivi, fatture, progetti e stipendi: meno testo sullo schermo, dettagli e altre azioni accessibili con un tocco.', 'Quotes, invoices, projects and payroll: less text on screen, with details and extra actions a tap away.'),
    copy('Des espaces plus généreux, des boutons adaptés au toucher et des écrans vérifiés en quatre langues, en mode clair et sombre.', 'Mehr Freiraum, berührungsfreundliche Schaltflächen und in vier Sprachen geprüfte Bildschirme im hellen und dunklen Modus.', 'Più spazio, pulsanti adatti al tocco e schermate verificate in quattro lingue, in modalità chiara e scura.', 'More breathing room, touch-friendly buttons and screens checked in four languages, in light and dark modes.'),
  ] },
  { version: '1.67.2', title: copy('Partage rétabli', 'Freigabe wiederhergestellt', 'Condivisione ripristinata', 'Sharing restored'), changes: [
    copy('Le serveur peut à nouveau recevoir les documents de l’entreprise. Le correctif s’applique aussi aux installations 1.67.1.', 'Der Server kann Unternehmensdokumente wieder empfangen. Die Korrektur gilt auch für Installationen der Version 1.67.1.', 'Il server può nuovamente ricevere i documenti aziendali. La correzione si applica anche alle installazioni 1.67.1.', 'The server can receive company documents again. This fix also applies to installations running 1.67.1.'),
    copy('Les erreurs de connexion ou de serveur ne sont plus présentées comme un champ mal rempli.', 'Verbindungs- oder Serverfehler werden nicht mehr als fehlerhaftes Formularfeld angezeigt.', 'Gli errori di connessione o del server non vengono più presentati come campi compilati male.', 'Connection and server errors are no longer shown as invalid form fields.'),
  ] },
  { version: '1.67.1', title: copy('Inviter et partager, simplement', 'Einfach einladen und teilen', 'Invitare e condividere, facilmente', 'Invite and share, simply'), changes: [
    copy('Correction de « Route de compte refusée » lors du partage ou de la réception de l’entreprise.', 'Fehler „Kontoroute abgelehnt“ beim Teilen oder Empfangen des Unternehmens behoben.', 'Corretto l’errore di accesso al servizio durante la condivisione o la ricezione dell’azienda.', 'Fixed the rejected account route when sharing or receiving a company.'),
    copy('Correction du blocage du partage lorsque des coordonnées facultatives sont vides.', 'Die Freigabe wird nicht mehr durch leere optionale Unternehmensangaben blockiert.', 'La condivisione non viene più bloccata dai dati aziendali facoltativi vuoti.', 'Empty optional company details no longer block sharing.'),
    copy('Créer une invitation prépare directement le partage complet : documents, montants, comptabilité, logo et salaires. Moins de texte et aucune case de partage supplémentaire.', 'Eine Einladung bereitet direkt die vollständige Freigabe vor: Dokumente, Beträge, Buchhaltung, Logo und Löhne. Weniger Text und kein zusätzliches Freigabefeld.', 'Un invito prepara direttamente la condivisione completa: documenti, importi, contabilità, logo e stipendi. Meno testo e nessuna casella aggiuntiva.', 'Creating an invitation prepares full sharing: documents, amounts, accounting, logo and payroll. Less text and no extra sharing checkbox.'),
  ] },
  { version: '1.67.0', title: copy('Votre entreprise, partagée avec votre équipe', 'Ihr Unternehmen gemeinsam im Team', 'La vostra azienda condivisa con il team', 'Your company shared with your team'), changes: [
    copy('Partage continu de la base complète via Supabase : clients, devis, factures, projets, logo, réglages, comptabilité, salaires et pièces jointes. Activation dans Paramètres → Compte et équipe.', 'Fortlaufende Freigabe aller Unternehmensdaten über Supabase: Kunden, Angebote, Rechnungen, Projekte, Logo, Einstellungen, Buchhaltung, Löhne und Anhänge. Aktivierung unter Einstellungen → Konto und Team.', 'Condivisione continua tramite Supabase: clienti, preventivi, fatture, progetti, logo, impostazioni, contabilità, salari e allegati. Attivazione in Impostazioni → Account e team.', 'Ongoing sharing through Supabase: customers, quotes, invoices, projects, logo, settings, accounting, payroll and attachments. Enable it in Settings → Account and team.'),
    copy('Les nouveaux devis et factures affichent leur créateur et peuvent être filtrés par personne. Les anciens documents sans auteur connu restent identifiés comme tels.', 'Neue Angebote und Rechnungen zeigen ihren Ersteller und lassen sich nach Person filtern. Ältere Dokumente ohne bekannten Ersteller werden entsprechend gekennzeichnet.', 'I nuovi preventivi e le nuove fatture mostrano il creatore e possono essere filtrati per persona. I documenti precedenti senza autore noto sono indicati come tali.', 'New quotes and invoices show their creator and can be filtered by person. Older documents without a known creator are labelled accordingly.'),
    copy('Envoi repris après une interruption, numéros réservés par appareil et réception différée pendant la saisie. En cas de modifications concurrentes, une sauvegarde conserve la copie locale avant de recevoir celle de l’équipe ; les changements non envoyés doivent être repris manuellement.', 'Übertragungen werden nach Unterbrechungen fortgesetzt, Nummern pro Gerät reserviert und eingehende Änderungen während der Eingabe zurückgestellt. Bei gleichzeitigen Änderungen wird die lokale Kopie vor dem Empfang der Teamversion gesichert; nicht übertragene Änderungen müssen manuell übernommen werden.', 'Gli invii riprendono dopo le interruzioni, i numeri sono riservati per dispositivo e la ricezione attende durante la compilazione. In caso di modifiche contemporanee, la copia locale viene salvata prima di ricevere quella del team; le modifiche non inviate devono essere riprese manualmente.', 'Interrupted uploads resume, numbers are reserved per device and incoming changes wait while you edit. Concurrent changes require a local backup before receiving the team version; unsent changes must be reapplied manually.'),
  ] },

  { version: '1.66.0', title: copy('Recommencer simplement, rejoindre une entreprise complète', 'Einfach neu beginnen und einem vollständigen Unternehmen beitreten', 'Ricominciare facilmente e accedere all’azienda completa', 'Start over easily and join a complete company'), changes: [
    copy('Réinitialisation de l’appareil avec confirmation, sauvegarde de sécurité et retour à la configuration initiale.', 'Gerät mit Bestätigung, Sicherheitskopie und Rückkehr zur Ersteinrichtung zurücksetzen.', 'Ripristino del dispositivo con conferma, copia di sicurezza e ritorno alla configurazione iniziale.', 'Reset the device with confirmation, a safety backup and a return to initial setup.'),
    copy('L’administrateur peut partager une copie complète de l’entreprise ; les appareils invités la récupèrent automatiquement après connexion.', 'Administratoren können eine vollständige Unternehmenskopie teilen; eingeladene Geräte laden sie nach der Anmeldung automatisch.', 'L’amministratore può condividere una copia completa dell’azienda; i dispositivi invitati la ricevono automaticamente dopo l’accesso.', 'Administrators can share a full company copy; invited devices download it automatically after connecting.'),
    copy('Les modifications métier suivantes restent locales. Les fichiers des projets conservent leur synchronisation habituelle.', 'Spätere Geschäftsdatenänderungen bleiben lokal. Projektdateien werden weiterhin wie gewohnt synchronisiert.', 'Le successive modifiche ai dati aziendali restano locali. I file dei progetti mantengono la sincronizzazione abituale.', 'Subsequent business data changes remain local. Project files keep their existing synchronisation.')
  ] },
  { version: '1.65.0', title: copy('Des couleurs plus lisibles, du sombre au clair', 'Besser lesbare Farben, von dunkel zu hell', 'Colori più leggibili, dallo scuro al chiaro', 'Clearer colours, from dark to light'), changes: [
    copy('Une palette sombre plus neutre, avec des textes, champs et menus mieux contrastés.', 'Eine neutralere dunkle Farbpalette mit deutlicheren Texten, Eingabefeldern und Menüs.', 'Una palette scura più neutra, con testi, campi e menu più contrastati.', 'A more neutral dark palette, with clearer text, fields and menus.'),
    copy('Le retour au mode clair remet aussi le fond de la fenêtre à jour, même après un redémarrage ou plusieurs changements rapides.', 'Beim Wechsel zur hellen Darstellung wird auch der Fensterhintergrund aktualisiert, selbst nach einem Neustart oder mehreren schnellen Wechseln.', 'Il ritorno alla modalità chiara aggiorna anche lo sfondo della finestra, anche dopo un riavvio o più cambi rapidi.', 'Returning to light mode also updates the window background, even after restarting or switching quickly several times.'),
    copy('Sur iPhone, les bords de l’écran et le fond visible pendant le défilement suivent le thème choisi.', 'Auf dem iPhone folgen Bildschirmränder und der beim Scrollen sichtbare Hintergrund der gewählten Darstellung.', 'Su iPhone, i bordi dello schermo e lo sfondo visibile durante lo scorrimento seguono il tema scelto.', 'On iPhone, screen edges and the background visible while scrolling follow the selected theme.'),
    copy('Les aperçus des documents et les échantillons de personnalisation gardent leurs couleurs d’impression.', 'Dokumentvorschauen und Gestaltungsmuster behalten ihre Druckfarben.', 'Le anteprime dei documenti e i campioni di personalizzazione mantengono i colori di stampa.', 'Document previews and design samples retain their print colours.'),
  ] },
  { version: '1.64.0', title: copy('Confort mobile, mode sombre et invitations', 'Mobiler Komfort, dunkle Darstellung und Einladungen', 'Comfort mobile, modalità scura e inviti', 'Mobile comfort, dark mode and invitations'), changes: [
    copy("Un mode sombre complet, avec choix clair, sombre ou automatique et préférence conservée sur cet appareil. Les documents gardent leurs couleurs d’impression.", "Dunkle Darstellung mit heller, dunkler oder automatischer Auswahl, gespeichert auf diesem Gerät. Dokumente behalten ihre Druckfarben.", "Modalità scura con scelta chiara, scura o automatica, salvata sul dispositivo. I documenti mantengono i colori di stampa.", "Dark appearance with light, dark or automatic options saved on this device. Documents keep their print colours."),
    copy("Sur mobile, tirez depuis le bord gauche pour ouvrir le menu et glissez dans l’autre sens pour le fermer. Les commandes tiennent compte des zones réservées de l’écran.", "Auf Mobilgeräten vom linken Rand wischen, um das Menü zu öffnen, und zurückwischen, um es zu schliessen. Bedienelemente berücksichtigen die sicheren Bildschirmbereiche.", "Su mobile, scorri dal bordo sinistro per aprire il menu e in senso opposto per chiuderlo. I comandi rispettano le aree sicure dello schermo.", "On mobile, swipe from the left edge to open the menu and swipe back to close it. Controls respect the screen’s safe areas."),
    copy("Pincez les devis, factures, PDF et photos pour zoomer, puis faites glisser pour explorer le document.", "Offerten, Rechnungen, PDFs und Fotos mit zwei Fingern vergrössern und zum Erkunden verschieben.", "Pizzica preventivi, fatture, PDF e foto per ingrandirli, poi scorri per esplorare il documento.", "Pinch quotes, invoices, PDFs and photos to zoom, then pan to explore the document."),
    copy("Invitez une personne avec un rôle, dans les places de votre formule, titulaire compris. Un nouveau code ne peut plus être remplacé par une ancienne réponse de connexion.", "Personen mit einer Rolle im Rahmen des Tarifs einladen, Kontoinhaber eingeschlossen. Alte Verbindungsantworten überschreiben keinen neuen Code mehr.", "Invita persone con un ruolo entro i posti del piano, titolare incluso. Le vecchie risposte di connessione non sostituiscono più un nuovo codice.", "Invite people with a role within your plan’s places, including the owner. An old connection response can no longer replace a new code."),
    copy("Au démarrage, « Rejoindre une entreprise » récupère les coordonnées partagées via Supabase. Les fichiers de projets sont partagés ; les autres données métier restent locales.", "Beim Start lädt «Einem Unternehmen beitreten» die über Supabase geteilten Angaben. Projektdateien werden geteilt; andere Geschäftsdaten bleiben lokal.", "All’avvio, «Unisciti a un’azienda» recupera i dati condivisi tramite Supabase. I file dei progetti sono condivisi; gli altri dati aziendali restano locali.", "At startup, “Join a company” retrieves details shared through Supabase. Project files are shared; other business data remains local."),
  ] },
  { version: '1.63.1', title: copy('Assurance accidents : reprendre la fiche de salaire', 'Unfallversicherung: Lohnabrechnung fortsetzen', 'Assicurazione infortuni: riprendere la busta paga', 'Accident insurance: continue your payslip'), changes: [
    copy('Le nom de l’assureur est demandé directement lorsqu’il manque, sans redemander le taux déjà enregistré.', 'Ein fehlender Versicherername wird direkt abgefragt, ohne den bereits gespeicherten Satz erneut zu verlangen.', 'Se manca il nome dell’assicuratore, viene richiesto direttamente senza ripetere l’aliquota già registrata.', 'A missing insurer name is requested directly, without asking again for an already saved rate.'),
    copy('Réutilisez une cotisation existante dans la fiche. Si plusieurs contrats sont présents, choisissez celui du collaborateur sans créer de doublon.', 'Verwenden Sie einen bestehenden Beitrag in der Abrechnung. Bei mehreren Verträgen wählen Sie den passenden für die Person, ohne ein Duplikat anzulegen.', 'Riutilizza un contributo esistente nella busta paga. Se ci sono più contratti, scegli quello del collaboratore senza creare duplicati.', 'Reuse an existing contribution in the payslip. If several contracts exist, choose the employee’s contract without creating duplicates.'),
  ] },
  { version: '1.63.0', title: copy('Navigation Apple et suivi des améliorations', 'Apple-Navigation und Neuerungen', 'Navigazione Apple e novità', 'Apple navigation and update history'), changes: [
    copy('iPhone et Mac : les commandes Apple gardent leur connexion lors des changements d’écran et après la fermeture d’une fenêtre.', 'iPhone und Mac: Apple-Steuerelemente behalten ihre Verbindung beim Bildschirmwechsel und nach dem Schliessen eines Dialogs.', 'iPhone e Mac: i controlli Apple mantengono la connessione durante i cambi di schermata e dopo la chiusura di una finestra.', 'iPhone and Mac: Apple controls stay connected across screen changes and after closing a dialog.'),
    copy('Paramètres : consultez les nouveautés de la version installée et les mises à jour précédentes, même hors ligne.', 'Einstellungen: Neuerungen der installierten Version und frühere Updates sind auch offline einsehbar.', 'Impostazioni: consulta le novità della versione installata e gli aggiornamenti precedenti, anche offline.', 'Settings: view changes in the installed version and previous updates, even offline.'),
    copy('Achats : préparation, vérification et paiement des factures fournisseurs guidés, avec reprise après une interruption et explication du solde.', 'Einkäufe: geführte Erfassung, Prüfung und Zahlung von Lieferantenrechnungen, mit Wiederaufnahme nach Unterbrechungen und Erklärung des Restbetrags.', 'Acquisti: preparazione, verifica e pagamento guidati delle fatture fornitori, con ripresa dopo un’interruzione e spiegazione del saldo.', 'Purchases: guided supplier invoice preparation, review and payment, with recovery after interruptions and a clear balance breakdown.'),
  ] },
  { version: '1.62.1', title: copy('Activation de l’édition iPhone personnelle', 'Aktivierung der persönlichen iPhone-Ausgabe', 'Attivazione dell’edizione iPhone personale', 'Personal iPhone edition activation'), changes: [
    copy('L’écran d’activation indique la cause du blocage et l’identifiant de l’appareil. Il permet de réessayer ou de saisir une licence fournie par l’assistance.', 'Der Aktivierungsbildschirm zeigt den Grund der Sperre und die Gerätekennung. Ein erneuter Versuch oder die Eingabe einer vom Support bereitgestellten Lizenz ist möglich.', 'La schermata di attivazione mostra la causa del blocco e l’identificativo del dispositivo. Permette di riprovare o inserire una licenza fornita dall’assistenza.', 'The activation screen shows the reason for the problem and the device ID. It lets you retry or enter a licence provided by support.'),
  ] },
  { version: '1.62.0', title: copy('Langues et présentation des documents', 'Sprachen und Dokumentgestaltung', 'Lingue e presentazione dei documenti', 'Languages and document design'), changes: [
    copy('Choix du français, de l’allemand, de l’italien et de l’anglais au démarrage et dans les paramètres. Configuration, tutoriel et parcours de paie traduits ; certains écrans et PDF restent en français.', 'Französisch, Deutsch, Italienisch und Englisch beim Start und in den Einstellungen wählbar. Einrichtung, Einführung und Lohnabläufe übersetzt; einige Ansichten und PDFs bleiben auf Französisch.', 'Scelta di francese, tedesco, italiano e inglese all’avvio e nelle impostazioni. Configurazione, tutorial e percorsi salari tradotti; alcune schermate e PDF restano in francese.', 'Choose French, German, Italian or English at startup or in settings. Setup, tutorial and payroll flows translated; some screens and PDFs remain in French.'),
    copy('Atelier de documents plus spacieux avec outils de mise en page et aperçu.', 'Mehr Platz im Dokumenteditor mit Layoutwerkzeugen und Vorschau.', 'Editor documenti più spazioso con strumenti di impaginazione e anteprima.', 'A roomier document editor with layout tools and a preview.'),
  ] },
  { version: '1.61.0', title: copy('Polices et factures liées', 'Schriftarten und verknüpfte Rechnungen', 'Caratteri e fatture collegate', 'Fonts and linked invoices'), changes: [
    copy('Polices Inter et Literata incluses pour les documents et PDF, utilisables hors ligne en normal, gras et italique.', 'Inter und Literata für Dokumente und PDFs enthalten, offline in normaler, fetter und kursiver Schrift nutzbar.', 'Caratteri Inter e Literata inclusi per documenti e PDF, disponibili offline in normale, grassetto e corsivo.', 'Inter and Literata fonts included for documents and PDFs, available offline in regular, bold and italic.'),
    copy('Préparation des factures d’acompte et de solde en trois étapes : prestation, paiement, vérification. Les erreurs renvoient au champ à corriger.', 'Anzahlungs- und Schlussrechnungen in drei Schritten: Leistung, Zahlung, Prüfung. Fehler führen zum betroffenen Feld.', 'Fatture di acconto e saldo in tre passaggi: prestazione, pagamento, verifica. Gli errori rimandano al campo da correggere.', 'Deposit and final invoices in three steps: service, payment, review. Errors point to the field that needs attention.'),
  ] },
  { version: '1.60.0', title: copy('Documents, paiements et projets', 'Dokumente, Zahlungen und Projekte', 'Documenti, pagamenti e progetti', 'Documents, payments and projects'), changes: [
    copy('Modèles de documents réutilisables, portrait ou paysage, couleurs des tableaux, listes et réglages des paragraphes.', 'Wiederverwendbare Dokumentvorlagen, Hoch- oder Querformat, Tabellenfarben, Listen und Absatzeinstellungen.', 'Modelli riutilizzabili, formato verticale o orizzontale, colori delle tabelle, elenchi e impostazioni dei paragrafi.', 'Reusable document templates, portrait or landscape, table colours, lists and paragraph settings.'),
    copy('Paiements, remboursements, réceptions et mouvements de stock guidés. Réparation d’une copie locale de document et reprise de la synchronisation des projets.', 'Geführte Zahlungen, Rückzahlungen, Wareneingänge und Lagerbewegungen. Wiederherstellung lokaler Dokumentkopien und Wiederaufnahme der Projektsynchronisierung.', 'Pagamenti, rimborsi, ricezioni e movimenti di magazzino guidati. Riparazione della copia locale di un documento e ripresa della sincronizzazione dei progetti.', 'Guided payments, refunds, receipts and stock movements. Repair local document copies and resume project syncing.'),
  ] },
] as const;

function versionParts(value: string): number[] | null {
  if (!/^\d+\.\d+\.\d+$/.test(value)) return null;
  const parts = value.split('.').map(Number);
  return parts.every(Number.isSafeInteger) ? parts : null;
}
export function compareReleaseVersions(left: string, right: string): number | null {
  const a = versionParts(left), b = versionParts(right);
  if (!a || !b) return null;
  for (let index = 0; index < 3; index++) if (a[index] !== b[index]) return a[index] > b[index] ? 1 : -1;
  return 0;
}
export function releaseNotesFor(version: string) {
  return {
    current: releaseHistory.find(entry => entry.version === version),
    older: releaseHistory.filter(entry => compareReleaseVersions(entry.version, version) === -1),
  };
}
