import type { AppLanguage } from './language';

type Localized = Readonly<Record<AppLanguage, string>>;
const copy = (fr: string, de: string, it: string, en: string): Localized => ({ fr, de, it, en });
export const releaseHistoryCopy = {
  title: copy('Les nouveautés de Zentra', 'Neues in Zentra', 'Le novità di Zentra', 'What’s new in Zentra'),
  current: copy('Voir les nouveautés de cette version', 'Neuerungen dieser Version ansehen', 'Vedi le novità di questa versione', 'See what’s new in this version'),
  older: copy('Voir les mises à jour précédentes', 'Frühere Updates ansehen', 'Vedi gli aggiornamenti precedenti', 'See previous updates'),
  installed: copy('Version installée', 'Installierte Version', 'Versione installata', 'Installed version'),
  unknown: copy('Les notes de cette version ne sont pas encore disponibles dans l’application.', 'Die Hinweise zu dieser Version sind in der App noch nicht verfügbar.', 'Le note di questa versione non sono ancora disponibili nell’app.', 'Notes for this version are not yet available in the app.'),
  loading: copy('Lecture de la version installée…', 'Installierte Version wird gelesen…', 'Lettura della versione installata…', 'Reading the installed version…'),
  archive: copy('Cet historique présente les versions documentées dans cette édition. Il reste consultable sans connexion.', 'Dieser Verlauf zeigt die in dieser Ausgabe dokumentierten Versionen. Er ist auch offline verfügbar.', 'Questa cronologia mostra le versioni documentate in questa edizione. È consultabile anche senza connessione.', 'This history lists the versions documented in this edition. It is also available offline.'),
  empty: copy('Aucune version précédente documentée pour cette installation.', 'Für diese Installation ist keine frühere Version dokumentiert.', 'Nessuna versione precedente documentata per questa installazione.', 'No earlier version is documented for this installation.'),
};

// Append a version with every shipped correction; never rewrite an older entry
// to describe work that was added later. See docs/RELEASE-*.md for release evidence.
export const releaseHistory = [
  { version: '1.67.2', title: copy('Partage rétabli', 'Freigabe wiederhergestellt', 'Condivisione ripristinata', 'Sharing restored'), changes: [
    copy('Le serveur peut à nouveau recevoir les documents de l’entreprise. Le correctif s’applique aussi aux installations 1.67.1.', 'Der Server kann Unternehmensdokumente wieder empfangen. Die Korrektur gilt auch für Installationen der Version 1.67.1.', 'Il server può nuovamente ricevere i documenti aziendali. La correzione si applica anche alle installazioni 1.67.1.', 'The server can receive company documents again. This fix also applies to installations running 1.67.1.'),
    copy('Les erreurs de connexion ou de serveur ne sont plus présentées comme un champ mal rempli.', 'Verbindungs- oder Serverfehler werden nicht mehr als fehlerhaftes Formularfeld angezeigt.', 'Gli errori di connessione o del server non vengono più presentati come campi compilati male.', 'Connection and server errors are no longer shown as invalid form fields.'),
  ] },
  { version: '1.67.1', title: copy('Inviter et partager, simplement', 'Einfach einladen und teilen', 'Invitare e condividere, facilmente', 'Invite and share, simply'), changes: [
    copy('Correction de « Route de compte refusée » lors du partage ou de la réception de l’entreprise.', 'Fehler „Kontoroute abgelehnt“ beim Teilen oder Empfangen des Unternehmens behoben.', 'Corretto l’errore di accesso al servizio durante la condivisione o la ricezione dell’azienda.', 'Fixed the rejected account route when sharing or receiving a company.'),
    copy('Correction du blocage du partage lorsque des coordonnées facultatives sont vides.', 'Die Freigabe wird nicht mehr durch leere optionale Unternehmensangaben blockiert.', 'La condivisione non viene più bloccata dai dati aziendali facoltativi vuoti.', 'Empty optional company details no longer block sharing.'),
    copy('Créer une invitation prépare directement le partage complet : documents, montants, comptabilité, logo et salaires. Moins de texte et aucune case de partage supplémentaire.', 'Eine Einladung bereitet direkt die vollständige Freigabe vor: Dokumente, Beträge, Buchhaltung, Logo und Löhne. Weniger Text und kein zusätzliches Freigabefeld.', 'Un invito prepara direttamente la condivisione completa: documenti, importi, contabilità, logo e stipendi. Meno testo e nessuna casella aggiuntiva.', 'Creating an invitation prepares full sharing: documents, amounts, accounting, logo and payroll. Less text and no extra sharing checkbox.'),
  ] },
  { version: '1.67.0', title: copy('Votre entreprise, partagée avec votre équipe', 'Ihr Unternehmen gemeinsam im Team', 'La vostra azienda condivisa con il team', 'Your company shared with your team'), changes: [
    copy('Partage continu de la base complète via Supabase : clients, devis, factures, projets, logo, réglages, comptabilité, salaires et pièces jointes. Activation dans Paramètres → Compte et équipe.', 'Fortlaufende Freigabe aller Unternehmensdaten über Supabase: Kunden, Angebote, Rechnungen, Projekte, Logo, Einstellungen, Buchhaltung, Löhne und Anhänge. Aktivierung unter Einstellungen → Konto und Team.', 'Condivisione continua tramite Supabase: clienti, preventivi, fatture, progetti, logo, impostazioni, contabilità, salari e allegati. Attivazione in Impostazioni → Account e team.', 'Ongoing sharing through Supabase: customers, quotes, invoices, projects, logo, settings, accounting, payroll and attachments. Enable it in Settings → Account and team.'),
    copy('Les nouveaux devis et factures affichent leur créateur et peuvent être filtrés par personne. Les anciens documents sans auteur connu restent identifiés comme tels.', 'Neue Angebote und Rechnungen zeigen ihren Ersteller und lassen sich nach Person filtern. Ältere Dokumente ohne bekannten Ersteller werden entsprechend gekennzeichnet.', 'I nuovi preventivi e le nuove fatture mostrano il creatore e possono essere filtrati per persona. I documenti precedenti senza autore noto sono indicati come tali.', 'New quotes and invoices show their creator and can be filtered by person. Older documents without a known creator are labelled accordingly.'),
    copy('Envoi repris après une interruption, numéros réservés par appareil et réception différée pendant la saisie. En cas de modifications concurrentes, une sauvegarde conserve la copie locale avant de recevoir celle de l’équipe ; les changements non envoyés doivent être repris manuellement.', 'Übertragungen werden nach Unterbrechungen fortgesetzt, Nummern pro Gerät reserviert und eingehende Änderungen während der Eingabe zurückgestellt. Bei gleichzeitigen Änderungen wird die lokale Kopie vor dem Empfang der Teamversion gesichert; nicht übertragene Änderungen müssen manuell übernommen werden.', 'Gli invii riprendono dopo le interruzioni, i numeri sono riservati per dispositivo e la ricezione attende durante la compilazione. In caso di modifiche contemporanee, la copia locale viene salvata prima di ricevere quella del team; le modifiche non inviate devono essere riprese manualmente.', 'Interrupted uploads resume, numbers are reserved per device and incoming changes wait while you edit. Concurrent changes require a local backup before receiving the team version; unsent changes must be reapplied manually.'),
  ] },

  { version: '1.66.0', title: copy('Recommencer simplement, rejoindre une entreprise complète', 'Einfach neu beginnen und einem vollständigen Unternehmen beitreten', 'Ricominciare facilmente e accedere all’azienda completa', 'Start over easily and join a complete company'), changes: [
    copy('Réinitialisation de l’appareil avec confirmation, sauvegarde de sécurité et retour à la configuration initiale.', 'Gerät mit Bestätigung, Sicherheitskopie und Rückkehr zur Ersteinrichtung zurücksetzen.', 'Ripristino del dispositivo con conferma, copia di sicurezza e ritorno alla configurazione iniziale.', 'Reset the device with confirmation, a safety backup and a return to initial setup.'),
    copy('L’administrateur peut partager une copie complète de l’entreprise ; les appareils invités la récupèrent automatiquement après connexion.', 'Administratoren können eine vollständige Unternehmenskopie teilen; eingeladene Geräte laden sie nach der Anmeldung automatisch.', 'L’amministratore può condividere una copia completa dell’azienda; i dispositivi invitati la ricevono automaticamente dopo l’accesso.', 'Administrators can share a full company copy; invited devices download it automatically after connecting.'),
    copy('Les modifications métier suivantes restent locales. Les fichiers des projets conservent leur synchronisation habituelle.', 'Spätere Geschäftsdatenänderungen bleiben lokal. Projektdateien werden weiterhin wie gewohnt synchronisiert.', 'Le successive modifiche ai dati aziendali restano locali. I file dei progetti mantengono la sincronizzazione abituale.', 'Subsequent business data changes remain local. Project files keep their existing synchronisation.')
  ] },
  { version: '1.65.0', title: copy('Des couleurs plus lisibles, du sombre au clair', 'Besser lesbare Farben, von dunkel zu hell', 'Colori più leggibili, dallo scuro al chiaro', 'Clearer colours, from dark to light'), changes: [
    copy('Une palette sombre plus neutre, avec des textes, champs et menus mieux contrastés.', 'Eine neutralere dunkle Farbpalette mit deutlicheren Texten, Eingabefeldern und Menüs.', 'Una palette scura più neutra, con testi, campi e menu più contrastati.', 'A more neutral dark palette, with clearer text, fields and menus.'),
    copy('Le retour au mode clair remet aussi le fond de la fenêtre à jour, même après un redémarrage ou plusieurs changements rapides.', 'Beim Wechsel zur hellen Darstellung wird auch der Fensterhintergrund aktualisiert, selbst nach einem Neustart oder mehreren schnellen Wechseln.', 'Il ritorno alla modalità chiara aggiorna anche lo sfondo della finestra, anche dopo un riavvio o più cambi rapidi.', 'Returning to light mode also updates the window background, even after restarting or switching quickly several times.'),
    copy('Sur iPhone, les bords de l’écran et le fond visible pendant le défilement suivent le thème choisi.', 'Auf dem iPhone folgen Bildschirmränder und der beim Scrollen sichtbare Hintergrund der gewählten Darstellung.', 'Su iPhone, i bordi dello schermo e lo sfondo visibile durante lo scorrimento seguono il tema scelto.', 'On iPhone, screen edges and the background visible while scrolling follow the selected theme.'),
    copy('Les aperçus des documents et les échantillons de personnalisation gardent leurs couleurs d’impression.', 'Dokumentvorschauen und Gestaltungsmuster behalten ihre Druckfarben.', 'Le anteprime dei documenti e i campioni di personalizzazione mantengono i colori di stampa.', 'Document previews and design samples retain their print colours.'),
  ] },
  { version: '1.64.0', title: copy('Confort mobile, mode sombre et invitations', 'Mobiler Komfort, dunkle Darstellung und Einladungen', 'Comfort mobile, modalità scura e inviti', 'Mobile comfort, dark mode and invitations'), changes: [
    copy("Un mode sombre complet, avec choix clair, sombre ou automatique et préférence conservée sur cet appareil. Les documents gardent leurs couleurs d’impression.", "Dunkle Darstellung mit heller, dunkler oder automatischer Auswahl, gespeichert auf diesem Gerät. Dokumente behalten ihre Druckfarben.", "Modalità scura con scelta chiara, scura o automatica, salvata sul dispositivo. I documenti mantengono i colori di stampa.", "Dark appearance with light, dark or automatic options saved on this device. Documents keep their print colours."),
    copy("Sur mobile, tirez depuis le bord gauche pour ouvrir le menu et glissez dans l’autre sens pour le fermer. Les commandes tiennent compte des zones réservées de l’écran.", "Auf Mobilgeräten vom linken Rand wischen, um das Menü zu öffnen, und zurückwischen, um es zu schliessen. Bedienelemente berücksichtigen die sicheren Bildschirmbereiche.", "Su mobile, scorri dal bordo sinistro per aprire il menu e in senso opposto per chiuderlo. I comandi rispettano le aree sicure dello schermo.", "On mobile, swipe from the left edge to open the menu and swipe back to close it. Controls respect the screen’s safe areas."),
    copy("Pincez les devis, factures, PDF et photos pour zoomer, puis faites glisser pour explorer le document.", "Offerten, Rechnungen, PDFs und Fotos mit zwei Fingern vergrössern und zum Erkunden verschieben.", "Pizzica preventivi, fatture, PDF e foto per ingrandirli, poi scorri per esplorare il documento.", "Pinch quotes, invoices, PDFs and photos to zoom, then pan to explore the document."),
    copy("Invitez une personne avec un rôle, dans les places de votre formule, titulaire compris. Un nouveau code ne peut plus être remplacé par une ancienne réponse de connexion.", "Personen mit einer Rolle im Rahmen des Tarifs einladen, Kontoinhaber eingeschlossen. Alte Verbindungsantworten überschreiben keinen neuen Code mehr.", "Invita persone con un ruolo entro i posti del piano, titolare incluso. Le vecchie risposte di connessione non sostituiscono più un nuovo codice.", "Invite people with a role within your plan’s places, including the owner. An old connection response can no longer replace a new code."),
    copy("Au démarrage, « Rejoindre une entreprise » récupère les coordonnées partagées via Supabase. Les fichiers de projets sont partagés ; les autres données métier restent locales.", "Beim Start lädt «Einem Unternehmen beitreten» die über Supabase geteilten Angaben. Projektdateien werden geteilt; andere Geschäftsdaten bleiben lokal.", "All’avvio, «Unisciti a un’azienda» recupera i dati condivisi tramite Supabase. I file dei progetti sono condivisi; gli altri dati aziendali restano locali.", "At startup, “Join a company” retrieves details shared through Supabase. Project files are shared; other business data remains local."),
  ] },
  { version: '1.63.1', title: copy('Assurance accidents : reprendre la fiche de salaire', 'Unfallversicherung: Lohnabrechnung fortsetzen', 'Assicurazione infortuni: riprendere la busta paga', 'Accident insurance: continue your payslip'), changes: [
    copy('Le nom de l’assureur est demandé directement lorsqu’il manque, sans redemander le taux déjà enregistré.', 'Ein fehlender Versicherername wird direkt abgefragt, ohne den bereits gespeicherten Satz erneut zu verlangen.', 'Se manca il nome dell’assicuratore, viene richiesto direttamente senza ripetere l’aliquota già registrata.', 'A missing insurer name is requested directly, without asking again for an already saved rate.'),
    copy('Réutilisez une cotisation existante dans la fiche. Si plusieurs contrats sont présents, choisissez celui du collaborateur sans créer de doublon.', 'Verwenden Sie einen bestehenden Beitrag in der Abrechnung. Bei mehreren Verträgen wählen Sie den passenden für die Person, ohne ein Duplikat anzulegen.', 'Riutilizza un contributo esistente nella busta paga. Se ci sono più contratti, scegli quello del collaboratore senza creare duplicati.', 'Reuse an existing contribution in the payslip. If several contracts exist, choose the employee’s contract without creating duplicates.'),
  ] },
  { version: '1.63.0', title: copy('Navigation Apple et suivi des améliorations', 'Apple-Navigation und Neuerungen', 'Navigazione Apple e novità', 'Apple navigation and update history'), changes: [
    copy('iPhone et Mac : les commandes Apple gardent leur connexion lors des changements d’écran et après la fermeture d’une fenêtre.', 'iPhone und Mac: Apple-Steuerelemente behalten ihre Verbindung beim Bildschirmwechsel und nach dem Schliessen eines Dialogs.', 'iPhone e Mac: i controlli Apple mantengono la connessione durante i cambi di schermata e dopo la chiusura di una finestra.', 'iPhone and Mac: Apple controls stay connected across screen changes and after closing a dialog.'),
    copy('Paramètres : consultez les nouveautés de la version installée et les mises à jour précédentes, même hors ligne.', 'Einstellungen: Neuerungen der installierten Version und frühere Updates sind auch offline einsehbar.', 'Impostazioni: consulta le novità della versione installata e gli aggiornamenti precedenti, anche offline.', 'Settings: view changes in the installed version and previous updates, even offline.'),
    copy('Achats : préparation, vérification et paiement des factures fournisseurs guidés, avec reprise après une interruption et explication du solde.', 'Einkäufe: geführte Erfassung, Prüfung und Zahlung von Lieferantenrechnungen, mit Wiederaufnahme nach Unterbrechungen und Erklärung des Restbetrags.', 'Acquisti: preparazione, verifica e pagamento guidati delle fatture fornitori, con ripresa dopo un’interruzione e spiegazione del saldo.', 'Purchases: guided supplier invoice preparation, review and payment, with recovery after interruptions and a clear balance breakdown.'),
  ] },
  { version: '1.62.1', title: copy('Activation de l’édition iPhone personnelle', 'Aktivierung der persönlichen iPhone-Ausgabe', 'Attivazione dell’edizione iPhone personale', 'Personal iPhone edition activation'), changes: [
    copy('L’écran d’activation indique la cause du blocage et l’identifiant de l’appareil. Il permet de réessayer ou de saisir une licence fournie par l’assistance.', 'Der Aktivierungsbildschirm zeigt den Grund der Sperre und die Gerätekennung. Ein erneuter Versuch oder die Eingabe einer vom Support bereitgestellten Lizenz ist möglich.', 'La schermata di attivazione mostra la causa del blocco e l’identificativo del dispositivo. Permette di riprovare o inserire una licenza fornita dall’assistenza.', 'The activation screen shows the reason for the problem and the device ID. It lets you retry or enter a licence provided by support.'),
  ] },
  { version: '1.62.0', title: copy('Langues et présentation des documents', 'Sprachen und Dokumentgestaltung', 'Lingue e presentazione dei documenti', 'Languages and document design'), changes: [
    copy('Choix du français, de l’allemand, de l’italien et de l’anglais au démarrage et dans les paramètres. Configuration, tutoriel et parcours de paie traduits ; certains écrans et PDF restent en français.', 'Französisch, Deutsch, Italienisch und Englisch beim Start und in den Einstellungen wählbar. Einrichtung, Einführung und Lohnabläufe übersetzt; einige Ansichten und PDFs bleiben auf Französisch.', 'Scelta di francese, tedesco, italiano e inglese all’avvio e nelle impostazioni. Configurazione, tutorial e percorsi salari tradotti; alcune schermate e PDF restano in francese.', 'Choose French, German, Italian or English at startup or in settings. Setup, tutorial and payroll flows translated; some screens and PDFs remain in French.'),
    copy('Atelier de documents plus spacieux avec outils de mise en page et aperçu.', 'Mehr Platz im Dokumenteditor mit Layoutwerkzeugen und Vorschau.', 'Editor documenti più spazioso con strumenti di impaginazione e anteprima.', 'A roomier document editor with layout tools and a preview.'),
  ] },
  { version: '1.61.0', title: copy('Polices et factures liées', 'Schriftarten und verknüpfte Rechnungen', 'Caratteri e fatture collegate', 'Fonts and linked invoices'), changes: [
    copy('Polices Inter et Literata incluses pour les documents et PDF, utilisables hors ligne en normal, gras et italique.', 'Inter und Literata für Dokumente und PDFs enthalten, offline in normaler, fetter und kursiver Schrift nutzbar.', 'Caratteri Inter e Literata inclusi per documenti e PDF, disponibili offline in normale, grassetto e corsivo.', 'Inter and Literata fonts included for documents and PDFs, available offline in regular, bold and italic.'),
    copy('Préparation des factures d’acompte et de solde en trois étapes : prestation, paiement, vérification. Les erreurs renvoient au champ à corriger.', 'Anzahlungs- und Schlussrechnungen in drei Schritten: Leistung, Zahlung, Prüfung. Fehler führen zum betroffenen Feld.', 'Fatture di acconto e saldo in tre passaggi: prestazione, pagamento, verifica. Gli errori rimandano al campo da correggere.', 'Deposit and final invoices in three steps: service, payment, review. Errors point to the field that needs attention.'),
  ] },
  { version: '1.60.0', title: copy('Documents, paiements et projets', 'Dokumente, Zahlungen und Projekte', 'Documenti, pagamenti e progetti', 'Documents, payments and projects'), changes: [
    copy('Modèles de documents réutilisables, portrait ou paysage, couleurs des tableaux, listes et réglages des paragraphes.', 'Wiederverwendbare Dokumentvorlagen, Hoch- oder Querformat, Tabellenfarben, Listen und Absatzeinstellungen.', 'Modelli riutilizzabili, formato verticale o orizzontale, colori delle tabelle, elenchi e impostazioni dei paragrafi.', 'Reusable document templates, portrait or landscape, table colours, lists and paragraph settings.'),
    copy('Paiements, remboursements, réceptions et mouvements de stock guidés. Réparation d’une copie locale de document et reprise de la synchronisation des projets.', 'Geführte Zahlungen, Rückzahlungen, Wareneingänge und Lagerbewegungen. Wiederherstellung lokaler Dokumentkopien und Wiederaufnahme der Projektsynchronisierung.', 'Pagamenti, rimborsi, ricezioni e movimenti di magazzino guidati. Riparazione della copia locale di un documento e ripresa della sincronizzazione dei progetti.', 'Guided payments, refunds, receipts and stock movements. Repair local document copies and resume project syncing.'),
  ] },
] as const;

function versionParts(value: string): number[] | null {
  if (!/^\d+\.\d+\.\d+$/.test(value)) return null;
  const parts = value.split('.').map(Number);
  return parts.every(Number.isSafeInteger) ? parts : null;
}
export function compareReleaseVersions(left: string, right: string): number | null {
  const a = versionParts(left), b = versionParts(right);
  if (!a || !b) return null;
  for (let index = 0; index < 3; index++) if (a[index] !== b[index]) return a[index] > b[index] ? 1 : -1;
  return 0;
}
export function releaseNotesFor(version: string) {
  return {
    current: releaseHistory.find(entry => entry.version === version),
    older: releaseHistory.filter(entry => compareReleaseVersions(entry.version, version) === -1),
  };
}
