// @vitest-environment jsdom
// @vitest-environment-options {"url":"http://localhost","pretendToBeVisual":true}
import './languageTestPacks';
import React, {act} from 'react';
import {createRoot, type Root} from 'react-dom/client';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {CustomerCreditPanel} from './CustomerCreditPanel';
import {CustomerCreditRecovery} from './CustomerCreditRecovery';
import {FormDraftIdentityProvider} from './useFormDraft';
import {desktopApi} from './bridge';
import {getAppLanguage,setAppLanguage,t,type AppLanguage} from './language';
import {saveCreditRecovery,readCreditRecovery,type CustomerCreditRecoveryPlan,type CustomerCreditRecoveryPreview} from './customerCreditRecoveryState';
import type {Invoice,Workspace} from './types';
vi.mock('@tauri-apps/api/core',()=>({invoke:vi.fn(),isTauri:()=>false,Channel:class{}}));

const languages=['fr','de','it','en'] as const;
const scope={companyId:'company-credit-qa',organizationId:'organization-credit-qa',memberId:'member-credit-qa',type:'customer-credit-recovery',recordId:'invoice-credit-qa'};
const reference='Courriel {number} – été 客戶';
const reason='Motif libre français conservé : déjà déduit.';
const original={id:'invoice-credit-qa',number:'FAC-{name}-été',type:'invoice',currency:'CHF',status:'issued'} as unknown as Invoice;
const credit={id:'credit-qa',number:'AVO-été-{count}',title:'Titre libre français',type:'credit_note',originalInvoiceId:original.id,currency:'CHF',status:'issued',customerCredit:{allocatedCents:2000,refundedCents:1000,remainingCents:7000},creditSettlements:[
  {id:'event-apply',eventType:'apply',invoiceId:original.id,date:'2026-01-15',amountCents:2000,reference,reason,reversesId:null,bankAccountId:null,journalEntryId:'journal-qa',journalValid:true},
  {id:'event-refund',eventType:'refund',invoiceId:null,date:'2026-01-16',amountCents:1000,reference,reason,reversesId:null,bankAccountId:'bank-qa',journalEntryId:null,journalValid:false,bankMatchId:'bank-match-qa'},
  {id:'event-reverse-apply',eventType:'reverse_apply',invoiceId:original.id,date:'2026-01-17',amountCents:1000,reference,reason,reversesId:'event-apply',bankAccountId:null,journalEntryId:'journal-review-qa',journalValid:false},
  {id:'event-reverse-refund',eventType:'reverse_refund',invoiceId:null,date:'2026-01-18',amountCents:500,reference,reason,reversesId:'event-old-qa',bankAccountId:'bank-qa',journalEntryId:null,journalValid:false},
],creditRecovery:{recordedAt:'2026-01-20T10:00:00Z',reference,reason,receivedVat:true,vatAdjustments:[{date:'2026-01-15',reference,dueChangeCents:150}]}} as Invoice;
const workspace={workNotesScope:scope.companyId,invoices:[original,credit],accounts:[{id:'bank-qa',name:'Banque française {name}'}],attachments:[]} as unknown as Workspace;
const plan:CustomerCreditRecoveryPlan={sourceToken:'source-token-raw',originalInvoiceId:original.id,number:original.number,currency:'CHF',invoiceTotalCents:20000,paidCents:5000,blocker:null,receivedVat:true,credits:[{id:credit.id,number:credit.number,totalCents:10000,issueDate:'2026-01-01',earliestApplicationDate:'2026-01-01'}]};
const preview:CustomerCreditRecoveryPreview={originalInvoiceId:original.id,number:original.number,currency:'CHF',invoiceRemainingCents:13766,receivedVat:true,credits:[{creditNoteId:credit.id,number:credit.number,allocatedCents:1234,remainingCents:8766}],vatAdjustments:[
  {sourceType:'credit',sourceId:'credit-qa',date:'2026-01-01',reference,expectedVatCents:100,dueChangeCents:-100},
  {sourceType:'application',sourceId:'application-qa',date:'2026-01-15',reference,expectedVatCents:10,dueChangeCents:10},
  {sourceType:'payment',sourceId:'payment-qa',date:'2026-01-15',reference,expectedVatCents:20,dueChangeCents:20},
]};
const visible={
  fr:{panel:'Avoirs et règlements',history:'Historique · 4 opérations',attachment:'Justificatif du règlement',recovery:'Documenter les avoirs',invalid:'Saisissez un montant positif avec au plus deux décimales.',future:'Indiquez une date effective, au plus tard aujourd’hui.',loadError:'Le dossier de reprise ne peut pas être chargé.',review:'Vérifier les soldes après reprise'},
  de:{panel:'Gutschriften und Abwicklungen',history:'Verlauf · 4 Vorgänge',attachment:'Beleg zur Abwicklung',recovery:'Gutschriften dokumentieren',invalid:'Geben Sie einen positiven Betrag mit höchstens zwei Dezimalstellen ein.',future:'Geben Sie ein tatsächliches Datum an, spätestens heute.',loadError:'Das Übernahmedossier kann nicht geladen werden.',review:'Salden nach der Übernahme prüfen'},
  it:{panel:'Note di credito e regolamenti',history:'Cronologia · 4 operazioni',attachment:'Giustificativo del regolamento',recovery:'Documentare le note di credito',invalid:'Inserite un importo positivo con al massimo due decimali.',future:'Indicate una data effettiva, non successiva a oggi.',loadError:'Il dossier di ripresa non può essere caricato.',review:'Verificare i saldi dopo la ripresa'},
  en:{panel:'Credit notes and settlements',history:'History · 4 transactions',attachment:'Settlement supporting document',recovery:'Document credit notes',invalid:'Enter a positive amount with no more than two decimal places.',future:'Enter an actual date no later than today.',loadError:'The recovery file cannot be loaded.',review:'Check balances after recovery'},
};
let root:Root,host:HTMLDivElement;
let scrollIntoViewDescriptor:PropertyDescriptor|undefined;
const actionRunner=vi.fn(async(action:()=>Promise<Workspace>,_message:string,_close?:boolean,onError?:(cause:unknown)=>void,validate?:(next:Workspace)=>void)=>{try{const next=await action();validate?.(next);return true;}catch(cause){onError?.(cause);return false;}});
beforeEach(()=>{scrollIntoViewDescriptor=Object.getOwnPropertyDescriptor(Element.prototype,'scrollIntoView');Object.defineProperty(Element.prototype,'scrollIntoView',{configurable:true,writable:true,value:vi.fn(function(this:Element,_options?:boolean|ScrollIntoViewOptions){})});localStorage.clear();vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);vi.stubGlobal('requestAnimationFrame',(callback:FrameRequestCallback)=>setTimeout(()=>callback(0),0));vi.stubGlobal('cancelAnimationFrame',clearTimeout);vi.stubGlobal('matchMedia',()=>({matches:false,addEventListener(){},removeEventListener(){}}));host=document.createElement('div');document.body.append(host);root=createRoot(host);actionRunner.mockClear();vi.spyOn(desktopApi,'getCustomerCreditRecovery').mockResolvedValue(plan);vi.spyOn(desktopApi,'previewCustomerCreditRecovery').mockResolvedValue(preview);vi.spyOn(desktopApi,'adoptCustomerCreditRecovery').mockResolvedValue(workspace);});
afterEach(async()=>{await act(async()=>root.unmount());host.remove();await act(async()=>setAppLanguage('fr'));vi.restoreAllMocks();vi.unstubAllGlobals();if(scrollIntoViewDescriptor)Object.defineProperty(Element.prototype,'scrollIntoView',scrollIntoViewDescriptor);else delete (Element.prototype as Partial<Element>).scrollIntoView;});
function identity(children:React.ReactNode){return <FormDraftIdentityProvider {...scope} ready>{children}</FormDraftIdentityProvider>;}
async function mount(language:AppLanguage,panel=false,readOnly=false,panelWorkspace=workspace){await act(async()=>{await setAppLanguage(language);root.render(identity(panel?<CustomerCreditPanel invoice={original} workspace={panelWorkspace} busy={false} readOnly={readOnly} act={actionRunner} onReadWorkspace={async()=>panelWorkspace} onOpenHelp={vi.fn()}/>:<CustomerCreditRecovery originalInvoiceId={original.id} workspace={workspace} busy={false} readOnly={readOnly} act={actionRunner} onReadWorkspace={async()=>workspace}/>));});}
const localResume={fr:'Reprendre la même reprise',de:'Denselben Antrag fortsetzen',it:'Riprendere la stessa richiesta',en:'Resume the same request'};
const localCheck={fr:'Vérifier la même reprise',de:'Denselben Antrag prüfen',it:'Verificare la stessa richiesta',en:'Check the same request'};
function button(source:string){const label=source==='Reprendre la même reprise'?localResume[getAppLanguage()]:source==='Vérifier la même reprise'?localCheck[getAppLanguage()]:t(source);const found=[...host.querySelectorAll<HTMLButtonElement>('button')].find(node=>node.textContent?.trim()===label);expect(found,source).toBeTruthy();return found!;}
async function click(source:string){await act(async()=>button(source).click());}
async function change(node:HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement,value:string){await act(async()=>{Object.getOwnPropertyDescriptor(Object.getPrototypeOf(node),'value')!.set!.call(node,value);node.dispatchEvent(new Event(node instanceof HTMLSelectElement?'change':'input',{bubbles:true}));});}
async function fillRecovery(){await click('Documenter les règlements');await change(host.querySelector('select')!,'applied');await change(host.querySelector<HTMLInputElement>('input[inputmode="decimal"]')!,'12.34');await change(host.querySelector<HTMLInputElement>('input[type="date"]')!,'2026-01-15');await change(host.querySelector<HTMLInputElement>('input[maxlength="255"]')!,reference);await change(host.querySelector('textarea')!,reason);await act(async()=>host.querySelector<HTMLInputElement>('input[type="checkbox"]')!.click());}

describe('customer credit interface language and financial preservation',()=>{
  it.each(languages)('renders panel history, actions and attachment labels in %s while retaining document text',async language=>{await mount(language,true);expect(host.querySelector('h3')?.textContent).toBe(visible[language].panel);expect(host.textContent).toContain(visible[language].history);expect(host.textContent).toContain(reference);expect(host.textContent).toContain(reason);expect(host.textContent).toContain(original.number);await click('Joindre une pièce');expect(host.querySelector('h4')?.textContent).toBe(visible[language].attachment);expect(host.querySelector('input[type="file"]')?.closest('label')?.textContent).toContain(t('Fichier à joindre'));expect(host.textContent).toContain(t('La pièce restera conservée avec l’historique, y compris après une correction.'));expect(button('Ajouter le justificatif').disabled).toBe(true);expect(desktopApi.getCustomerCreditRecovery).not.toHaveBeenCalled();});
  it.each(languages)('localizes nested open/remove attachment controls in %s and retains the exact filename and scope',async language=>{const filename='Courriel – été {name}.pdf';const attachment={id:'attachment-qa',entityType:'customer_credit_settlement',entityId:'event-apply',originalName:filename,sizeBytes:4};const panelWorkspace={...workspace,attachments:[attachment]} as Workspace;vi.spyOn(desktopApi,'openAttachment').mockResolvedValue('closed-synthetic-attachment-path');await mount(language,true,false,panelWorkspace);const opener=host.querySelector<HTMLButtonElement>('.refund-attachments button')!;expect(opener.textContent?.trim()).toBe(t('Ouvrir'));expect(opener.getAttribute('aria-label')).toBe(t('Ouvrir {name}',{name:filename}));await act(async()=>opener.click());expect(desktopApi.openAttachment).toHaveBeenCalledExactlyOnceWith('attachment-qa',scope.companyId);await click('Joindre une pièce');const file=new File(['test'],filename,{type:'application/pdf'}),picker=host.querySelector<HTMLInputElement>('input[type="file"]')!;await act(async()=>{Object.defineProperty(picker,'files',{value:[file],configurable:true});picker.dispatchEvent(new Event('change',{bubbles:true}));});expect(host.querySelector('.refund-receipt-selection strong')?.textContent).toBe(filename);const remover=host.querySelector<HTMLButtonElement>('.refund-receipt-selection button')!;expect(remover.getAttribute('aria-label')).toBe(t('Retirer le justificatif sélectionné'));await act(async()=>remover.click());expect(host.querySelector('.refund-receipt-selection')).toBeNull();expect(button('Ajouter le justificatif').disabled).toBe(true);});
  it.each(languages)('previews and confirms a real form interaction in %s with identical raw RPC input',async language=>{await mount(language);await fillRecovery();expect(host.querySelector('h4')?.textContent).toContain(visible[language].recovery);expect(desktopApi.getCustomerCreditRecovery).toHaveBeenCalledExactlyOnceWith(original.id,scope.companyId);expect(button('Vérifier la reprise').disabled).toBe(false);await act(async()=>host.querySelector('form')!.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));expect(host.querySelector('h4')?.textContent).toBe(visible[language].review);const [input,company]=vi.mocked(desktopApi.previewCustomerCreditRecovery).mock.calls[0];expect(company).toBe(scope.companyId);expect(input).toEqual({requestId:expect.any(String),originalInvoiceId:original.id,sourceToken:plan.sourceToken,reference,reason,noPriorRefund:true,credits:[{creditNoteId:credit.id,appliedCents:1234,applicationDate:'2026-01-15'}]});expect(button('Confirmer la reprise').disabled).toBe(true);expect(host.querySelector('a')?.href).toBe('https://www.estv.admin.ch/fr/decompter-la-tva');await act(async()=>host.querySelector<HTMLInputElement>('input[type="checkbox"]')!.click());await click('Confirmer la reprise');expect(desktopApi.adoptCustomerCreditRecovery).toHaveBeenCalledExactlyOnceWith({...input,confirmVatReconciliation:true},scope.companyId);expect(actionRunner.mock.calls[0][1]).toBe(t('Les avoirs et leurs règlements documentés sont reliés au dossier.'));expect(plan.sourceToken).toBe('source-token-raw');expect(preview.vatAdjustments?.[0].reference).toBe(reference);});
  it.each(languages)('localizes amount/date validation in %s without allowing an invalid preview',async language=>{await mount(language);await click('Documenter les règlements');await change(host.querySelector('select')!,'applied');await change(host.querySelector<HTMLInputElement>('input[inputmode="decimal"]')!,'1.234');await change(host.querySelector<HTMLInputElement>('input[type="date"]')!,'2099-01-01');expect(host.textContent).toContain(visible[language].invalid);expect(host.textContent).toContain(visible[language].future);expect(button('Vérifier la reprise').disabled).toBe(true);expect(desktopApi.previewCustomerCreditRecovery).not.toHaveBeenCalled();});
  it.each(languages)('localizes the authored load failure in %s while retaining its raw rejection',async language=>{const failure=Error('Le dossier de reprise ne peut pas être chargé.');vi.mocked(desktopApi.getCustomerCreditRecovery).mockRejectedValue(failure);await mount(language);await click('Documenter les règlements');expect(host.textContent).toContain(visible[language].loadError);expect(failure.message).toBe('Le dossier de reprise ne peut pas être chargé.');expect(desktopApi.previewCustomerCreditRecovery).not.toHaveBeenCalled();});
  it('changes language on the same open form without losing values, selection, focus or raw references',async()=>{await mount('fr');await fillRecovery();const referenceInput=host.querySelector<HTMLInputElement>('input[maxlength="255"]')!;referenceInput.focus();for(const language of ['en','de','it','fr'] as const){await act(async()=>setAppLanguage(language));expect(host.querySelector('h4')?.textContent).toContain(visible[language].recovery);expect(referenceInput.value).toBe(reference);expect(host.querySelector('textarea')!.value).toBe(reason);expect(host.querySelector('select')!.value).toBe('applied');expect(host.querySelector<HTMLInputElement>('input[inputmode="decimal"]')!.value).toBe('12.34');expect(document.activeElement).toBe(referenceInput);expect(button('Vérifier la reprise').disabled).toBe(false);}expect(desktopApi.getCustomerCreditRecovery).toHaveBeenCalledTimes(1);expect(desktopApi.previewCustomerCreditRecovery).not.toHaveBeenCalled();});
  it('keeps the same retained request through language changes and requires history before replay',async()=>{const retained={input:{requestId:'12345678-1234-1234-1234-123456789abc',originalInvoiceId:original.id,sourceToken:plan.sourceToken,reference,reason,noPriorRefund:true,confirmVatReconciliation:true,credits:[{creditNoteId:credit.id,appliedCents:1234,applicationDate:'2026-01-15'}]},preview};saveCreditRecovery(retained,scope);await mount('en');expect(button('Reprendre la même reprise').disabled).toBe(true);await act(async()=>setAppLanguage('de'));expect(host.querySelector('h4')?.textContent).toBe(visible.de.review);expect(readCreditRecovery(original.id,scope)).toEqual(retained);await click('Vérifier la même reprise');expect(button('Reprendre la même reprise').disabled).toBe(false);await click('Reprendre la même reprise');expect(desktopApi.adoptCustomerCreditRecovery).toHaveBeenCalledExactlyOnceWith(retained.input,scope.companyId);expect(desktopApi.previewCustomerCreditRecovery).not.toHaveBeenCalled();});
  it('keeps read-only controls disabled in a localized retained review',async()=>{saveCreditRecovery({input:{requestId:'12345678-1234-1234-1234-123456789abc',originalInvoiceId:original.id,sourceToken:plan.sourceToken,reference,reason,noPriorRefund:true,confirmVatReconciliation:true,credits:[{creditNoteId:credit.id,appliedCents:1234,applicationDate:'2026-01-15'}]},preview},scope);await mount('it',false,true);expect(button('Reprendre la même reprise').disabled).toBe(true);expect(host.textContent).toContain('La ripresa è consultabile. La registrazione richiede l’accesso in scrittura.');expect(desktopApi.adoptCustomerCreditRecovery).not.toHaveBeenCalled();});
});
