import assert from 'node:assert/strict';
import {afterEach,beforeEach,describe,it,vi} from 'vitest';
import * as recovery from './customerCreditRecoveryState';
const pending={input:{requestId:'12211111-1111-4111-8111-111111111111',originalInvoiceId:'11111111-1111-4111-8111-111111111111',sourceToken:'a'.repeat(64),reference:'SYNTHETIC-A',reason:'Synthetic documented credit',noPriorRefund:true,credits:[{creditNoteId:'22222222-2222-4222-8222-222222222222',appliedCents:0,applicationDate:null}]},preview:{originalInvoiceId:'11111111-1111-4111-8111-111111111111',number:'SYNTHETIC-ORIGINAL',currency:'CHF',invoiceRemainingCents:10000,credits:[{creditNoteId:'22222222-2222-4222-8222-222222222222',number:'SYNTHETIC-CREDIT',allocatedCents:0,remainingCents:10000}]}};
const scopeA={companyId:'synthetic-company-a',organizationId:'synthetic-org-a',memberId:'synthetic-member-a'},scopeC={companyId:'synthetic-company-c',organizationId:'synthetic-org-c',memberId:'synthetic-member-c'},id=pending.input.originalInvoiceId;

const map=new Map<string,string>();
beforeEach(()=>{map.clear();vi.stubGlobal('localStorage',{getItem:(k:string)=>map.get(k)??null,setItem:(k:string,v:string)=>map.set(k,v),removeItem:(k:string)=>map.delete(k)});});
afterEach(()=>vi.unstubAllGlobals());
describe('customer recovery scoped storage and exact pending identity',()=>{
  it('legacy exact UUID and payload remain readable explicitly',()=>{recovery.saveCreditRecovery(pending);assert.deepEqual(recovery.readCreditRecovery(id),pending);});
  it('different organization/member/physical scope cannot expose the saved request',()=>{recovery.saveCreditRecovery(pending,scopeA);assert.equal(recovery.readCreditRecovery(id,scopeC),undefined);});
  it('same company and org with another member cannot expose the saved request',()=>{recovery.saveCreditRecovery(pending,scopeA);assert.equal(recovery.readCreditRecovery(id,{...scopeA,memberId:'synthetic-member-other'}),undefined);});
  it('same org/member restored to another physical scope cannot expose the saved request',()=>{recovery.saveCreditRecovery(pending,scopeA);assert.equal(recovery.readCreditRecovery(id,{...scopeA,companyId:'synthetic-restored-scope'}),undefined);});
  it('unknown identity cannot read a scoped receipt',()=>{recovery.saveCreditRecovery(pending,scopeA);assert.equal(recovery.readCreditRecovery(id,null),undefined);});
  it('unknown identity cannot save a receipt',()=>{assert.throws(()=>recovery.saveCreditRecovery(pending,null));assert.equal(map.size,0);});
  it('same UUID and same input can be retained again',()=>{recovery.saveCreditRecovery(pending,scopeA);const raw=[...map.values()][0];recovery.saveCreditRecovery(structuredClone(pending),scopeA);assert.equal([...map.values()][0],raw);});
  it('another pending UUID cannot replace the receipt',()=>{recovery.saveCreditRecovery(pending,scopeA);const raw=[...map.values()][0];assert.throws(()=>recovery.saveCreditRecovery({...pending,input:{...pending.input,requestId:'33333333-3333-4333-8333-333333333333'}},scopeA));assert.equal([...map.values()][0],raw);});
  it('same UUID with changed native input cannot replace the receipt',()=>{recovery.saveCreditRecovery(pending,scopeA);const raw=[...map.values()][0];assert.throws(()=>recovery.saveCreditRecovery({...pending,input:{...pending.input,reference:'CHANGED'}},scopeA));assert.equal([...map.values()][0],raw);});
  it('clearing an older ACK cannot remove a different pending UUID',()=>{recovery.saveCreditRecovery(pending,scopeA);const raw=[...map.values()][0];recovery.clearCreditRecovery(id,scopeA,{...pending,input:{...pending.input,requestId:'33333333-3333-4333-8333-333333333333'}});assert.equal([...map.values()][0],raw);});
  it('matching ACK clears only the current scoped receipt',()=>{recovery.saveCreditRecovery(pending);recovery.saveCreditRecovery(pending,scopeA);const legacy=map.get('zentra.customer-credit-recovery.v1.'+id);recovery.clearCreditRecovery(id,scopeA,pending);assert.equal(map.get('zentra.customer-credit-recovery.v1.'+id),legacy);assert.equal(recovery.readCreditRecovery(id,scopeA),undefined);});
  it('v1 stays quarantined until an explicit read-linked choice',()=>{recovery.saveCreditRecovery(pending);assert.equal(recovery.readCreditRecovery(id,scopeA),undefined);assert(recovery.legacyCreditRecoveryReviewRequired(id,scopeA));const raw=recovery.legacyCreditRecoveryToken(id);assert(raw!==null);assert.deepEqual(recovery.adoptLegacyCreditRecovery(id,scopeA,raw),pending);assert.equal(recovery.legacyCreditRecoveryToken(id),raw);assert.deepEqual(recovery.readCreditRecovery(id,scopeA),pending);assert.equal(recovery.legacyCreditRecoveryReviewRequired(id,scopeA),false);assert(recovery.legacyCreditRecoveryReviewRequired(id,scopeC));});
  it('changed v1 invalidates the previous explicit choice',()=>{recovery.saveCreditRecovery(pending);const raw=recovery.legacyCreditRecoveryToken(id);assert(raw!==null);recovery.acknowledgeLegacyCreditRecoveryOtherCompany(id,scopeA,raw);assert.equal(recovery.legacyCreditRecoveryReviewRequired(id,scopeA),false);recovery.saveCreditRecovery({...pending,input:{...pending.input,reference:'CHANGED'}});assert(recovery.legacyCreditRecoveryReviewRequired(id,scopeA));assert.throws(()=>recovery.adoptLegacyCreditRecovery(id,scopeA,raw));});
  it('unreadable storage reblocks the legacy review',()=>{globalThis.localStorage.getItem=()=>{throw Error('Synthetic denied storage');};assert(recovery.legacyCreditRecoveryReviewRequired(id,scopeA));assert.throws(()=>recovery.saveCreditRecovery(pending,scopeA));globalThis.localStorage.getItem=k=>map.get(k)??null;});
  it('malformed existing v2 is retained instead of overwritten',()=>{recovery.saveCreditRecovery(pending,scopeA);const key=[...map.keys()][0];map.set(key,'{');assert.throws(()=>recovery.saveCreditRecovery(pending,scopeA));assert.equal(map.get(key),'{');});
  it('legacy adoption refuses another scoped unknown receipt',()=>{recovery.saveCreditRecovery(pending);const raw=recovery.legacyCreditRecoveryToken(id),other={...pending,input:{...pending.input,requestId:'33333333-3333-4333-8333-333333333333'}};assert(raw!==null);recovery.saveCreditRecovery(other,scopeA);assert.throws(()=>recovery.adoptLegacyCreditRecovery(id,scopeA,raw));assert.deepEqual(recovery.readCreditRecovery(id,scopeA),other);assert.equal(recovery.legacyCreditRecoveryToken(id),raw);});
});
