import {useEffect,useRef,useState} from 'react';
import {revealInDialog} from './dialogFocus';
import {desktopApi} from './bridge';
import type {Workspace} from './types';
import {Button,Field} from './ui';
import {createId,errorMessage,formatDate,formatMoney,invoiceOpenBalance,todayIso} from './utils';
import {creditAmount,creditAmountInput} from './creditAllocationWorkflow';
import {readCustomerCreditRequest,saveCustomerCreditRequest,clearCustomerCreditRequest,type PendingCustomerCreditRequest} from './customerCreditRequest';
import {customerSettlementAvailable,customerSettlementTargets,customerSettlementMinimum,customerSettlementProblem,customerSettlementNativeProblem,customerSettlementWasRecorded,requireCustomerSettlementWorkspace,type CustomerSettlementDraft,type CustomerSettlementProblem} from './customerSettlementWorkflow';
import './credit-allocation.css';

export function CustomerSettlementForm({creditId,mode,reverseId,workspace,busy,readOnly,act,onReadWorkspace,onOpenHelp,onDone,onCancel}:{creditId:string;mode:'apply'|'refund';reverseId?:string;workspace:Workspace;busy:boolean;readOnly:boolean;act:(action:()=>Promise<Workspace>,message:string,close?:boolean,onError?:(cause:unknown)=>void)=>Promise<boolean>;onReadWorkspace:()=>Promise<Workspace>;onOpenHelp:(destination:'accounts'|'periods'|'bank')=>void;onDone:()=>void;onCancel:()=>void;}){
 const credit=workspace.invoices.find(row=>row.id===creditId),events=credit?.creditSettlements??[],original=events.find(row=>row.id===reverseId);
 const [saved]=useState(()=>readCustomerCreditRequest(creditId));
 const [request,setRequest]=useState<PendingCustomerCreditRequest|undefined>(saved),[checked,setChecked]=useState(false),[pending,setPending]=useState(false);
 const [draft,setDraft]=useState<CustomerSettlementDraft>(()=>({amount:saved?creditAmountInput(saved.input.amountCents):original?creditAmountInput(original.amountCents):'',date:saved?.input.date||todayIso(),invoiceId:saved?.input.invoiceId||original?.invoiceId||'',bankAccountId:saved?.input.bankAccountId||original?.bankAccountId||workspace.accountingSettings?.bankAccountId||'',reference:saved?.input.reference||original?.reference||'',reason:saved?.input.reason||''}));
 const [review,setReview]=useState<string|null>(null),[problem,setProblem]=useState<CustomerSettlementProblem|null>(null),[detail,setDetail]=useState('');
 const form=useRef<HTMLFormElement>(null),flight=useRef(false);
 useEffect(()=>{revealInDialog(form.current?.querySelector<HTMLElement>('h4')??null);},[]);
 const locked=busy||pending,disabled=locked||readOnly||Boolean(request),available=customerSettlementAvailable(credit),amount=original?.amountCents??creditAmount(draft.amount);
 const target=workspace.invoices.find(row=>row.id===(original?.invoiceId||draft.invoiceId)),targetBalance=mode==='apply'&&target?invoiceOpenBalance(target,workspace.invoices,workspace.payments):null;
 const bank=workspace.accounts.find(row=>row.id===(original?.bankAccountId||draft.bankAccountId));
 const key=JSON.stringify([credit?.status,credit?.customerCredit,events,target?.status,target?.issueDate,targetBalance,bank,workspace.accountingSettings?.enabled,draft]);
 const changed=review!==null&&review!==key;
 const preview=!request&&available!==null&&amount!==null&&amount>0&&(mode==='refund'||targetBalance!==null)&&(reverseId?Number.isSafeInteger(available+amount):amount<=available&&(mode==='refund'||targetBalance!==null&&amount<=targetBalance));
 function focus(field:CustomerSettlementProblem['field']){requestAnimationFrame(()=>{const node=form.current?.querySelector<HTMLElement>(`[name="${field}"]`)||form.current?.querySelector<HTMLElement>('.credit-allocation-alert');node?.focus({preventScroll:true});const anchor=node?.closest('.field')||node,body=form.current?.closest('.modal__body');if(anchor&&body)body.scrollTop+=anchor.getBoundingClientRect().top-body.getBoundingClientRect().top-12;});}
 function update(patch:Partial<CustomerSettlementDraft>){setDraft(row=>({...row,...patch}));setProblem(null);setDetail('');}
 function finish(){clearCustomerCreditRequest(creditId);setRequest(undefined);onDone();}
 async function refresh(){if(flight.current||locked)return;flight.current=true;setPending(true);setChecked(false);try{const next=await onReadWorkspace();requireCustomerSettlementWorkspace(next);if(request){if(customerSettlementWasRecorded(next,request)){finish();return;}setChecked(true);}setProblem(null);setDetail('');}catch(cause){setProblem({field:'record',message:errorMessage(cause,'La lecture est interrompue. Votre saisie est conservée ; réessayez.')});focus('record');}finally{flight.current=false;setPending(false);}}
 async function execute(intent:PendingCustomerCreditRequest){
  if(flight.current||locked||readOnly)return;flight.current=true;setPending(true);setProblem(null);setDetail('');setChecked(false);
  try{
   try{saveCustomerCreditRequest(intent);setRequest(intent);}catch{setProblem({field:'record',message:'La demande ne peut pas être conservée pour sa reprise. Libérez du stockage local avant de continuer.'});focus('record');return;}
   const success=await act(()=>intent.reverseId?desktopApi.reverseCustomerCreditSettlement({requestId:intent.input.requestId,settlementId:intent.reverseId,date:intent.input.date,reason:intent.input.reason,context:intent}):desktopApi.recordCustomerCreditSettlement(intent.input),intent.reverseId?'La correction est enregistrée dans l’historique.':'Le règlement de l’avoir est enregistré.',false,cause=>{
    const message=errorMessage(cause,'Le résultat n’a pas pu être confirmé.');setDetail(message);setProblem(customerSettlementNativeProblem(message));
    if(/^(Champ invalide|Erreur de base de données locale|Enregistrement introuvable|Données JSON invalides)/.test(message)){clearCustomerCreditRequest(creditId);setRequest(undefined);setReview(null);}focus('record');
   });if(success)finish();
  }finally{flight.current=false;setPending(false);}
 }
 async function submit(){if(disabled||flight.current)return;const issue=customerSettlementProblem(credit,original,reverseId,mode,draft,workspace,todayIso());if(issue){setReview(null);setProblem(issue);setDetail('');focus(issue.field);return;}if(review===null||changed){setReview(key);setProblem(null);setDetail('');requestAnimationFrame(()=>{const heading=form.current?.querySelector<HTMLElement>('h4');heading?.focus({preventScroll:true});const body=form.current?.closest('.modal__body');if(heading&&body)body.scrollTop+=heading.getBoundingClientRect().top-body.getBoundingClientRect().top-12;});return;}if(available===null||!amount)return;
  await execute({input:{requestId:createId(),creditNoteId:creditId,eventType:mode,invoiceId:mode==='apply'?target?.id||null:null,date:draft.date,amountCents:amount,bankAccountId:mode==='refund'?bank?.id||null:null,reference:original?.reference||draft.reference.trim(),reason:draft.reason.trim(),expectedReview:{creditAvailableCents:available,invoiceBalanceCents:targetBalance,bankAccountId:mode==='refund'?bank?.id||null:null,accountingEnabled:Boolean(workspace.accountingSettings?.enabled)}},reverseId});
 }
 return <form ref={form} className="customer-credit-form customer-settlement-form" noValidate onSubmit={event=>{event.preventDefault();void submit();}}>
  <h4 tabIndex={-1}>{reverseId?'Corriger un règlement':mode==='apply'?'Déduire de la facture':'Remboursement versé au client'}</h4>
  {request?<div className="credit-allocation-alert" role="status" tabIndex={-1}><strong>Vérifier la demande précédente</strong><p>Les informations envoyées sont conservées. Relisez l’historique avant toute nouvelle tentative.</p><p>{formatMoney(request.input.amountCents,credit?.currency)} · {formatDate(request.input.date)} · {request.input.reference}</p>{checked&&<p>Cette demande n’a pas été retrouvée. Vous pouvez renvoyer exactement la même demande ; son identifiant empêche un double règlement.</p>}<Button type="button" variant="secondary" disabled={locked} onClick={()=>void refresh()}>Vérifier la même demande</Button>{checked&&<Button type="button" disabled={locked||readOnly} onClick={()=>void execute(request)}>Reprendre la même demande</Button>}</div>:<>
   <ol className="credit-allocation-steps" aria-label="Étapes"><li aria-current={review===null?'step':undefined}>1 · {reverseId?'Expliquer':'Préparer'}</li><li aria-current={review!==null?'step':undefined}>2 · Vérifier</li></ol>
   {review===null?<>
    <p>{reverseId?'La correction rétablit les soldes et conserve le règlement initial dans l’historique. Aucun virement n’est envoyé.':mode==='refund'?'Recopiez le virement déjà versé au client. Si l’argent n’a pas encore été envoyé, conservez l’avoir.':'Choisissez la facture à réduire. Vous pouvez utiliser seulement une partie de l’avoir. Aucun virement n’est effectué.'}</p>
    <fieldset className="credit-allocation-fields" disabled={disabled}>
     {!reverseId&&mode==='apply'&&<Field label="Facture à régler" required error={problem?.field==='invoiceId'?problem.message:undefined}><select name="invoiceId" value={draft.invoiceId} onChange={event=>{const next=workspace.invoices.find(row=>row.id===event.target.value);update({invoiceId:event.target.value,reference:!draft.reference.trim()||draft.reference===target?.number?next?.number||'':draft.reference});}}><option value="">Choisir une facture</option>{customerSettlementTargets(credit,workspace).map(row=><option key={row.id} value={row.id}>{row.number} · {formatDate(row.issueDate)} · {formatMoney(invoiceOpenBalance(row,workspace.invoices,workspace.payments),row.currency)}</option>)}</select></Field>}
     {!reverseId&&mode==='refund'&&<Field label="Compte du virement" required error={problem?.field==='bankAccountId'?problem.message:undefined}><select name="bankAccountId" value={draft.bankAccountId} onChange={event=>update({bankAccountId:event.target.value})}><option value="">Choisir un compte</option>{workspace.accounts.filter(row=>row.active&&row.accountType==='asset'&&row.id!==workspace.accountingSettings?.arAccountId).map(row=><option key={row.id} value={row.id}>{row.code} · {row.name}</option>)}</select></Field>}
     <Field label={`Montant (${credit?.currency||'CHF'})`} required error={problem?.field==='amount'?problem.message:undefined} hint={reverseId?'Le montant d’origine est conservé.':'Indiquez le montant réellement déduit ou remboursé.'}><input name="amount" inputMode="decimal" value={draft.amount} readOnly={Boolean(reverseId)} onChange={event=>update({amount:event.target.value})}/></Field>
     {!reverseId&&available!==null&&available>0&&(mode==='refund'||targetBalance!==null&&targetBalance>0)&&<Button type="button" variant="secondary" onClick={()=>update({amount:creditAmountInput(Math.min(available,targetBalance??available))})}>Utiliser le maximum · {formatMoney(Math.min(available,targetBalance??available),credit?.currency)}</Button>}
     <Field label={reverseId?'Date de correction':'Date effective'} required error={problem?.field==='date'?problem.message:undefined} hint="La date réelle de cette opération, au plus tard aujourd’hui."><input name="date" type="date" min={customerSettlementMinimum(credit,mode==='apply'?target:undefined,workspace)} max={todayIso()} value={draft.date} onChange={event=>update({date:event.target.value})}/></Field>
     <Field label={mode==='refund'?'Référence bancaire':'Référence de la déduction'} required error={problem?.field==='reference'?problem.message:undefined} hint={reverseId?'La référence d’origine est conservée.':'Recopiez un libellé bancaire ou le numéro de la facture.'}><input name="reference" maxLength={255} readOnly={Boolean(reverseId)} value={draft.reference} onChange={event=>update({reference:event.target.value})}/></Field>
     <Field label="Motif" required error={problem?.field==='reason'?problem.message:undefined} hint="Une courte explication suffit, de 5 à 1 000 caractères."><textarea name="reason" rows={3} maxLength={1000} value={draft.reason} onChange={event=>update({reason:event.target.value})}/></Field>
     <Button type="button" variant="ghost" onClick={()=>update({reason:reverseId?'Erreur de saisie du règlement':'Retour de marchandises'})}>Utiliser un exemple de motif</Button>
    </fieldset>
   </>:<section className="credit-allocation-review"><div className="customer-settlement-form__amount"><span>{reverseId?'Règlement à corriger':mode==='apply'?'Montant déduit':'Remboursement déjà versé'}</span><strong>{formatMoney(amount??0,credit?.currency)}</strong></div><p>{formatDate(draft.date)} · {original?.reference||draft.reference}</p>{changed&&<p className="credit-allocation-notice" role="alert">Les données ont changé. Relisez les montants, puis reprenez la vérification.</p>}</section>}
  </>}
  <div className="credit-allocation-balances"><div><span>Disponible sur l’avoir</span><strong>{available===null?'À vérifier':formatMoney(available,credit?.currency)}</strong>{preview&&<small>Après : {formatMoney(available!+(reverseId?amount!:-amount!),credit?.currency)}</small>}</div><div><span>{mode==='apply'?`Reste à payer · ${target?.number||'Facture à choisir'}`:reverseId?'Compte du remboursement initial':'Compte du virement'}</span><strong>{mode==='apply'?targetBalance===null?'À choisir':formatMoney(targetBalance,credit?.currency):bank?`${bank.code} · ${bank.name}`:'À choisir'}</strong>{preview&&<small>{mode==='apply'?`Après : ${formatMoney(targetBalance!+(reverseId?amount!:-amount!),credit?.currency)}`:`${reverseId?'Correction : +':'Virement versé : −'}${formatMoney(amount!,credit?.currency)}`}</small>}</div></div>
  {review!==null&&!request&&<details><summary>Motif du règlement</summary><p className="credit-allocation-reason">{draft.reason}</p></details>}
  {readOnly&&<p className="credit-allocation-notice">Accès en lecture seule : les enregistrements sont désactivés. Vous pouvez consulter et vérifier l’historique.</p>}
  {!workspace.accountingSettings?.enabled&&<p>La comptabilité est inactive : cette opération restera à comptabiliser.</p>}
  {problem&&(problem.field==='record'||problem.destination)&&<div className="credit-allocation-alert" role="alert" tabIndex={-1}><strong>Vérifions ce point</strong><p>{problem.message}</p>{detail&&<details><summary>Voir le message détaillé</summary><p>{detail}</p></details>}{problem.destination&&<><p>Retrouvez ensuite cet avoir pour préparer à nouveau le règlement. Une demande interrompue reste conservée.</p><Button type="button" variant="secondary" disabled={locked} onClick={()=>onOpenHelp(problem.destination!)}>{problem.destination==='bank'?'Ouvrir Banque':problem.destination==='periods'?'Ouvrir les exercices':'Ouvrir Plan & liaisons'}</Button></>}</div>}
  {!request&&<Button type="button" variant="ghost" disabled={locked} onClick={()=>void refresh()}>Actualiser les factures</Button>}
  <div className="form-actions"><Button type="button" variant="secondary" disabled={locked||Boolean(request)} onClick={()=>review!==null?setReview(null):onCancel()}>{review!==null?'Modifier':'Annuler'}</Button>{!request&&<Button type="submit" disabled={locked||readOnly}>{pending?'Vérification…':review===null?'Vérifier le règlement':changed?'Reprendre la vérification':reverseId?'Enregistrer la correction':'Enregistrer le règlement'}</Button>}</div>
 </form>;
}
