import {describe,expect,it} from 'vitest';
import {documentQuickClientFields,emptyDocumentQuickClient,validQuickClientCreationId,QuickClientCreationUnconfirmedError,quickClientCreationRecovery} from './documentQuickClientDraft';
import {initialDocumentFormDraft,validDocumentFormDraft} from './documentFormDraft';
import {initialOnboardingSettings} from './onboardingDraft';
import {WorkspaceCreationOutcomeUnknownError} from './workspaceCreation';
const id='11111111-aaaa-4aaa-8aaa-111111111111';
describe('durable document quick-client protocol',()=>{
  it('keeps all ten controlled quick-client fields with the same empty defaults',()=>{const value=emptyDocumentQuickClient();expect(Object.keys(value)).toEqual([...documentQuickClientFields]);expect(value.country).toBe('CH');expect(Object.values(value).filter(Boolean)).toEqual(['CH']);});
  it.each(['', 'not-a-uuid',id+' ', ' '+id, id.replaceAll('-',''), undefined, null, 123])('rejects malformed hidden creation identity %s',value=>{expect(validQuickClientCreationId(value)).toBe(false);});
  it('creates a strict modern draft while retaining all historic document values',()=>{const old=initialDocumentFormDraft('quotes',initialOnboardingSettings,'line');const modern=initialDocumentFormDraft('quotes',initialOnboardingSettings,'line',undefined,undefined,undefined,0,id);expect(modern).toEqual({...old,quickClientCreationId:id});expect(validDocumentFormDraft(modern)).toBe(true);});
  it('allows legacy data without an ID only for explicit UI decision and rejects present invalid identity',()=>{const legacy=initialDocumentFormDraft('quotes',initialOnboardingSettings,'line');expect(validDocumentFormDraft(legacy)).toBe(true);for(const value of ['',undefined,null,'broken',id+' '])expect(validDocumentFormDraft({...legacy,quickClientCreationId:value})).toBe(false);expect(validDocumentFormDraft({...legacy,quickClientCreationId:id})).toBe(true);});
  it('preserves strict document field validation and rejects unknown draft keys',()=>{const draft=initialDocumentFormDraft('invoices',initialOnboardingSettings,'line',undefined,undefined,undefined,0,id);expect(validDocumentFormDraft({...draft,unrecognized:'extra'})).toBe(false);expect(validDocumentFormDraft({...draft,quickClient:{...draft.quickClient,other:'x'}})).toBe(false);expect(validDocumentFormDraft({...draft,lines:[]})).toBe(false);});
  it('uses an ordinary unknown error rather than ID-only creation confirmation while retaining the cause',()=>{const cause=new WorkspaceCreationOutcomeUnknownError('clients',id,new Error('Closed fixture'));const wrapped=new QuickClientCreationUnconfirmedError(cause);expect(wrapped).not.toBeInstanceOf(WorkspaceCreationOutcomeUnknownError);expect(wrapped.cause).toBe(cause);expect(wrapped.name).toBe('QuickClientCreationUnconfirmedError');expect(wrapped.message).not.toContain(id);});
  it.each(['fr','de','it','en'] as const)('provides complete local, legacy and unknown-create instructions in %s',language=>{const text=quickClientCreationRecovery[language];expect(Object.values(text)).toHaveLength(8);expect(Object.values(text).every(value=>value.length>10)).toBe(true);expect(Object.values(text).join(' ')).not.toContain(id);});
});
