// @vitest-environment jsdom
// @vitest-environment-options {"url":"http://localhost"}
/** Real bridge plus the exact production DocumentEditor callback extracted by AST.
 * IPC alone is simulated, including a local guard after a held write. Callback
 * extraction is not a React UI / WorkspaceApp.act / SQLite authority witness.
 * Stable document/quick-client UUIDs and lost-ACK resolution remain out of scope. */
import documentEditorSource from './DocumentEditor.tsx?raw';
import ts from 'typescript';
import {beforeEach,afterEach,describe,expect,it,vi} from 'vitest';
import {desktopApi} from './bridge';
import {workspaceOriginFailure,WorkspaceOriginChangedError} from './workspaceOrigin';
import {WorkspaceRefreshAfterMutationError} from './workspaceMutation';
import {WorkspaceMemberOriginChangedError,type WorkspaceMutationOrigin} from './workspaceMemberOrigin';
import {bindWorkspaceMutationRead} from './memberOriginBridge';
import type {DocumentLine,Quote,Invoice} from './types';

const native=vi.hoisted(()=>({invoke:vi.fn()}));
vi.mock('@tauri-apps/api/core',()=>({Channel:class{},invoke:native.invoke,isTauri:()=>false}));
vi.hoisted(()=>{(globalThis as any).__documentOriginImportRequests=0;globalThis.fetch=async()=>{(globalThis as any).__documentOriginImportRequests++;throw Error('Network forbidden during document origin test import');};Object.defineProperty(window,'matchMedia',{configurable:true,value:()=>({matches:false,addEventListener(){},removeEventListener(){}})});});
const scope='document-origin-company',otherScope='document-origin-other',nonceA='a'.repeat(32),nonceB='b'.repeat(32);
const origin:WorkspaceMutationOrigin=Object.freeze({workspaceScope:scope,memberContextNonce:nonceA});
const lines:DocumentLine[]=[{id:'kept-line',catalogItemId:'catalog-item',description:'Travail de recette\nAvec détail',quantity:2.5,unit:'h',unitPriceCents:12345,discountBp:750,vatRateBp:810},{id:'new-line',catalogItemId:null,description:'Prestation',quantity:1,unit:'forfait',unitPriceCents:9876,vatRateBp:260}];
const quoteData={clientId:'client',projectId:'project',title:'Devis de recette',status:'draft',issueDate:'2026-10-03',validUntil:'2026-10-31',currency:'CHF',subtotalCents:40000,discountCents:3000,vatCents:2997,totalCents:39997,notes:'Notes de recette\nDeux lignes',terms:'Conditions de recette'};
const invoiceData={...quoteData,title:'Facture de recette',validUntil:undefined,dueDate:'2026-10-31',type:'deposit',quoteId:'quote-source',originalInvoiceId:null,serviceDateFrom:'2026-10-01',serviceDateTo:'2026-10-03',paidCents:0,depositPercentageBp:3333,depositBasisLines:lines};
const previousQuote={id:'existing-quote',lines:[lines[0]],status:'draft'} as Quote;
const previousInvoice={id:'existing-invoice',lines:[lines[0]],status:'draft'} as Invoice;
let currentScope=scope,currentNonce=nonceA,mode='',writes=0,external=0,writeEntered=false;
let writeHold:{promise:Promise<void>;resolve:()=>void}|undefined;
function held(){let resolve!:()=>void;const promise=new Promise<void>(yes=>resolve=yes);return {promise,resolve};}
function guard(args:any){if(args?.expectedWorkspaceScope!==undefined&&args.expectedWorkspaceScope!==currentScope)throw 'Champ invalide : L’entreprise ouverte a changé. Rouvrez cette action dans le bon espace.';if(args?.expectedMemberContextNonce!==undefined&&args.expectedMemberContextNonce!==currentNonce)throw 'Champ invalide : Le compte connecté a changé. Rouvrez cette action avec le bon compte.';}
function trackedCalls(){return native.invoke.mock.calls.filter(([command])=>command!=='append_diagnostic_events');}
function atomicCalls(){return native.invoke.mock.calls.filter(([command])=>command==='save_document_with_items');}
function save(entity:'quotes'|'invoices',edit=false){return desktopApi.saveDocument(entity,entity==='quotes'?quoteData:invoiceData,lines,edit?(entity==='quotes'?previousQuote:previousInvoice):undefined,origin.workspaceScope,origin.memberContextNonce);}
async function waitEntered(){for(let i=0;i<20&&!writeEntered;i++)await Promise.resolve();expect(writeEntered).toBe(true);}
function productionCallback(entity:'quotes'|'invoices',edit=false,reservedTime=false){
  const ast=ts.createSourceFile('DocumentEditor.tsx',documentEditorSource,ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX),callbacks:string[]=[];
  const visit=(node:ts.Node)=>{if(ts.isCallExpression(node)&&ts.isPropertyAccessExpression(node.expression)&&node.expression.getText(ast)==='desktopApi.saveDocument'){let parent:ts.Node|undefined=node.parent;while(parent&&!ts.isArrowFunction(parent))parent=parent.parent;if(!parent)throw Error('No production callback');callbacks.push(parent.getText(ast));}ts.forEachChild(node,visit);};visit(ast);expect(callbacks).toHaveLength(1);
  const data=entity==='quotes'?quoteData:invoiceData,item=edit?(entity==='quotes'?previousQuote:previousInvoice):undefined;
  return new Function('desktopApi','reservedTime','currentInvoice','entity','data','depositLines','item','originWorkspaceScope','issueDate','dueDate','return ('+callbacks[0]+');')(desktopApi,reservedTime,reservedTime?previousInvoice:undefined,entity,data,lines,item,scope,data.issueDate,entity==='quotes'?quoteData.validUntil:invoiceData.dueDate) as (value:WorkspaceMutationOrigin)=>Promise<unknown>;
}
beforeEach(()=>{
  currentScope=scope;currentNonce=nonceA;mode='';writes=0;external=0;writeEntered=false;writeHold=undefined;
  vi.stubGlobal('fetch',vi.fn(async()=>{external++;throw Error('No network in closed document fixture');}));native.invoke.mockReset();native.invoke.mockImplementation(async(command:string,args:any)=>{
    if(command==='append_diagnostic_events')return;
    if(command==='save_document_with_items'||command==='update_record'){if(writeHold){writeEntered=true;await writeHold.promise;}guard(args);writes++;if(mode==='ack-member')currentNonce=nonceB;if(mode==='ack-physical')currentScope=otherScope;if(mode==='lost')throw Error('Synthetic ACK lost after commit');return {id:'saved-document'};}
    guard(args);
    if(command==='get_app_state'){if(mode==='read-failure')throw Error('Synthetic local read unavailable');if(mode==='between-member')currentNonce=nonceB;if(mode==='between-physical')currentScope=otherScope;return {onboarding_completed:true};}
    if(command==='get_workspace')return {work_notes_scope:mode==='wrong-read-scope'?otherScope:currentScope,quotes:[],invoices:[],settings:null};
    throw Error('Closed document fixture rejects '+command);
  });
});
afterEach(()=>{writeHold?.resolve();expect(external).toBe(0);expect((globalThis as any).__documentOriginImportRequests).toBe(0);expect(native.invoke.mock.calls.some(([command])=>command==='get_form_draft_identity'||command==='get_cloud_account_state')).toBe(false);vi.unstubAllGlobals();});

describe('atomic sales document bridge original physical/member context',()=>{
  it.each([['quotes',false],['quotes',true],['invoices',false],['invoices',true]] as const)('forwards unchanged origin to %s edit=%s write and both readback commands',async(entity,edit)=>{
    const result=await save(entity,edit);expect(result.workNotesScope).toBe(scope);expect(writes).toBe(1);const calls=trackedCalls();expect(calls.map(([command])=>command)).toEqual(['save_document_with_items','get_app_state','get_workspace']);for(const [,args]of calls)expect(args).toMatchObject({expectedWorkspaceScope:scope,expectedMemberContextNonce:nonceA});expect(calls[0][1].input.entity).toBe(entity);expect(calls[0][1].input.id).toBe(edit?(entity==='quotes'?previousQuote.id:previousInvoice.id):null);
  });
  it('preserves quote amounts, multiline text, line order and create-vs-retained item identifiers',async()=>{
    await save('quotes',true);const input=atomicCalls()[0][1].input;expect(input.data).toEqual({client_id:'client',project_id:'project',title:'Devis de recette',status:'brouillon',issue_date:'2026-10-03',valid_until:'2026-10-31',currency:'CHF',subtotal_cents:40000,discount_cents:3000,vat_cents:2997,total_cents:39997,notes:quoteData.notes,terms:quoteData.terms});expect(input.items).toEqual([{id:'kept-line',catalog_item_id:'catalog-item',description:lines[0].description,quantity:2.5,unit:'h',unit_price_cents:12345,discount_bp:750,vat_bp:810},{id:null,catalog_item_id:null,description:'Prestation',quantity:1,unit:'forfait',unit_price_cents:9876,discount_bp:0,vat_bp:260}]);
  });
  it('preserves deposit percentage and the original unscaled basis lines separately from the document items',async()=>{
    await save('invoices',true);const input=atomicCalls()[0][1].input;expect(input.data).toMatchObject({type:'deposit',quote_id:'quote-source',original_invoice_id:null,service_date_from:'2026-10-01',service_date_to:'2026-10-03',due_date:'2026-10-31',paid_cents:0,deposit_percentage_bp:3333,subtotal_cents:40000,discount_cents:3000,vat_cents:2997,total_cents:39997});expect(input.data).not.toHaveProperty('deposit_basis_lines');expect(input.data.deposit_basis_json).toEqual([{id:'kept-line',catalog_item_id:'catalog-item',description:lines[0].description,quantity:2.5,unit:'h',unit_price_cents:12345,discount_bp:750,vat_bp:810},{id:'new-line',catalog_item_id:null,description:'Prestation',quantity:1,unit:'forfait',unit_price_cents:9876,discount_bp:0,vat_bp:260}]);expect(input.items.map((row:any)=>row.id)).toEqual(['kept-line',null]);
  });
  it('keeps explicit null deposit basis and does not mutate the caller data or its line objects',async()=>{
    const data={...invoiceData,type:'standard',depositPercentageBp:null,depositBasisLines:null},savedData=JSON.stringify(data),savedLines=JSON.stringify(lines);Object.freeze(data);lines.forEach(Object.freeze);Object.freeze(lines);await desktopApi.saveDocument('invoices',data,lines,undefined,scope,nonceA);expect(atomicCalls()[0][1].input.data.deposit_basis_json).toBeNull();expect(JSON.stringify(data)).toBe(savedData);expect(JSON.stringify(lines)).toBe(savedLines);
  });
  it.each(['physical','member'] as const)('refuses changed %s before the native write',async(kind)=>{if(kind==='physical')currentScope=otherScope;else currentNonce=nonceB;await expect(save('invoices')).rejects.toBeInstanceOf(kind==='physical'?WorkspaceOriginChangedError:WorkspaceMemberOriginChangedError);expect(writes).toBe(0);expect(atomicCalls()).toHaveLength(1);expect(trackedCalls().filter(([command])=>command==='get_app_state'||command==='get_workspace')).toHaveLength(0);});
  it.each(['physical','member'] as const)('rejects %s change while a native write is queued before the simulated lock',async(kind)=>{writeHold=held();const pending=save('quotes');await waitEntered();if(kind==='physical')currentScope=otherScope;else currentNonce=nonceB;writeHold.resolve();await expect(pending).rejects.toBeInstanceOf(kind==='physical'?WorkspaceOriginChangedError:WorkspaceMemberOriginChangedError);expect(writes).toBe(0);expect(atomicCalls()).toHaveLength(1);});
  it.each(['physical','member'] as const)('keeps %s origin failure after ACK terminal instead of acknowledging a newer context',async(kind)=>{mode='ack-'+kind;let failure:unknown;try{await save('invoices');}catch(error){failure=error;}expect(writes).toBe(1);expect(failure).toBeInstanceOf(WorkspaceRefreshAfterMutationError);expect(workspaceOriginFailure(failure)).toBeInstanceOf(kind==='physical'?WorkspaceOriginChangedError:WorkspaceMemberOriginChangedError);expect(atomicCalls()).toHaveLength(1);expect(trackedCalls().filter(([command])=>command==='get_workspace')).toHaveLength(0);for(const [,args]of trackedCalls())expect(args).toMatchObject({expectedWorkspaceScope:scope,expectedMemberContextNonce:nonceA});});
  it.each(['physical','member'] as const)('rejects %s change between app-state and workspace readback with the same original read arguments',async(kind)=>{mode='between-'+kind;let failure:unknown;try{await save('quotes',true);}catch(error){failure=error;}expect(failure).toBeInstanceOf(WorkspaceRefreshAfterMutationError);expect(workspaceOriginFailure(failure)).toBeInstanceOf(kind==='physical'?WorkspaceOriginChangedError:WorkspaceMemberOriginChangedError);expect(writes).toBe(1);expect(trackedCalls().map(([command])=>command)).toEqual(['save_document_with_items','get_app_state','get_workspace']);for(const [,args]of trackedCalls())expect(args).toMatchObject({expectedWorkspaceScope:scope,expectedMemberContextNonce:nonceA});});
  it('rejects a returned workspace with a different physical scope even if the simulated IPC guard passed',async()=>{mode='wrong-read-scope';let failure:unknown;try{await save('invoices');}catch(error){failure=error;}expect(workspaceOriginFailure(failure)).toBeInstanceOf(WorkspaceOriginChangedError);expect(writes).toBe(1);expect(atomicCalls()).toHaveLength(1);});
  it('recovers an ACK/read failure through a real original-bound read without replaying the atomic mutation',async()=>{const read=bindWorkspaceMutationRead(origin,desktopApi.loadWorkspace);mode='read-failure';await expect(save('quotes')).rejects.toBeInstanceOf(WorkspaceRefreshAfterMutationError);mode='';const restored=await read();expect(restored.workNotesScope).toBe(scope);expect(writes).toBe(1);expect(atomicCalls()).toHaveLength(1);expect(trackedCalls().map(([command])=>command)).toEqual(['save_document_with_items','get_app_state','get_app_state','get_workspace']);for(const [,args]of trackedCalls())expect(args).toMatchObject({expectedWorkspaceScope:scope,expectedMemberContextNonce:nonceA});});
  it.each(['physical','member'] as const)('does not replace the original pair during recovery after a %s change',async(kind)=>{const read=bindWorkspaceMutationRead(origin,desktopApi.loadWorkspace);mode='read-failure';await expect(save('invoices')).rejects.toBeInstanceOf(WorkspaceRefreshAfterMutationError);mode='';if(kind==='physical')currentScope=otherScope;else currentNonce=nonceB;await expect(read()).rejects.toBeInstanceOf(kind==='physical'?WorkspaceOriginChangedError:WorkspaceMemberOriginChangedError);expect(writes).toBe(1);expect(atomicCalls()).toHaveLength(1);for(const [,args]of trackedCalls())expect(args).toMatchObject({expectedWorkspaceScope:scope,expectedMemberContextNonce:nonceA});});
  it('does not pretend to resolve a lost ACK or automatically repeat the command',async()=>{mode='lost';await expect(save('invoices')).rejects.toThrow('Synthetic ACK lost');expect(writes).toBe(1);expect(atomicCalls()).toHaveLength(1);expect(trackedCalls().filter(([command])=>command==='get_app_state'||command==='get_workspace')).toHaveLength(0);});
  it.each([['quotes',false],['quotes',true],['invoices',false],['invoices',true]] as const)('preserves historical optional-argument IPC shape for %s edit=%s without introducing automatic fallback',async(entity,edit)=>{const existing=edit?(entity==='quotes'?previousQuote:previousInvoice):undefined;await desktopApi.saveDocument(entity,entity==='quotes'?quoteData:invoiceData,lines,existing);expect(writes).toBe(1);for(const [,args]of trackedCalls()){expect(args??{}).not.toHaveProperty('expectedWorkspaceScope');expect(args??{}).not.toHaveProperty('expectedMemberContextNonce');}expect(atomicCalls()[0][1].input.id).toBe(existing?.id??null);});
  it('rejects a malformed supplied nonce before IPC instead of silently retrying as a historical caller',async()=>{await expect(desktopApi.saveDocument('quotes',quoteData,lines,undefined,scope,'bad')).rejects.toBeInstanceOf(WorkspaceMemberOriginChangedError);expect(trackedCalls()).toHaveLength(0);expect(writes).toBe(0);});
  it('rejects nonce without a physical scope before IPC instead of granting an unguarded write',async()=>{await expect(desktopApi.saveDocument('quotes',quoteData,lines,undefined,undefined,nonceA)).rejects.toBeInstanceOf(WorkspaceOriginChangedError);expect(trackedCalls()).toHaveLength(0);expect(writes).toBe(0);});
  it.each([['quotes',false],['quotes',true],['invoices',false],['invoices',true]] as const)('executes the real extracted DocumentEditor callback for %s edit=%s',async(entity,edit)=>{const callback=productionCallback(entity,edit);await callback(origin);expect(writes).toBe(1);expect(atomicCalls()).toHaveLength(1);expect(atomicCalls()[0][1].input.entity).toBe(entity);expect(atomicCalls()[0][1].input.id).toBe(edit?(entity==='quotes'?previousQuote.id:previousInvoice.id):null);for(const [,args]of trackedCalls())expect(args).toMatchObject({expectedWorkspaceScope:scope,expectedMemberContextNonce:nonceA});expect(atomicCalls()[0][1].input.items.map((row:any)=>row.unit_price_cents)).toEqual([12345,9876]);if(entity==='invoices')expect(atomicCalls()[0][1].input.data.deposit_percentage_bp).toBe(3333);});
  it('preserves the real reserved-time callback branch as a metadata-only scoped update',async()=>{await productionCallback('invoices',true,true)(origin);expect(atomicCalls()).toHaveLength(0);expect(writes).toBe(1);const calls=trackedCalls();expect(calls.map(([command])=>command)).toEqual(['update_record','get_app_state','get_workspace']);expect(calls[0][1].data).toEqual({title:invoiceData.title,notes:invoiceData.notes,terms:invoiceData.terms,issue_date:invoiceData.issueDate,due_date:invoiceData.dueDate});for(const [,args]of calls)expect(args).toMatchObject({expectedWorkspaceScope:scope,expectedMemberContextNonce:nonceA});expect(calls[0][1].id).toBe(previousInvoice.id);});
});
