import {describe,expect,it} from 'vitest';
import {listDocumentCreationConsultations} from './documentCreationConsultation';
import {initialDocumentFormDraft} from './documentFormDraft';
import {initialOnboardingSettings} from './onboardingDraft';
import {prepareDocumentCreationRequest} from './documentCreationRequest';
import {formDraftKey,FORM_DRAFT_COMPLETED_PREFIX,FORM_DRAFT_PREFIX,formDraftFingerprint} from './formDrafts';
const company='company',member='member',id='11111111-2222-4333-8444-555555555555',identity={companyId:company,organizationId:'org',memberId:member,ready:true};
function fixture(){const values=new Map<string,string>(),writes:string[]=[],scope={companyId:company,organizationId:'org',memberId:member,type:'quotes',context:'quote:;project:'},key=formDraftKey(scope);
 const draft=initialDocumentFormDraft('quotes',initialOnboardingSettings,'line',undefined,undefined,undefined,3,undefined,id);draft.documentTitle='Private retained title';draft.documentCreationRequest=prepareDocumentCreationRequest(id,{entity:'quotes',id:null,data:{title:'Private retained title'},items:[{id:null,description:'Private'}]},company,member);
 values.set(key,JSON.stringify({version:1,scope:key,fingerprint:'new',savedAt:Date.now(),value:draft}));const store={get length(){return values.size;},key:(i:number)=>[...values.keys()][i]??null,getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>{writes.push(key);values.set(key,value);},removeItem:(key:string)=>{writes.push(key);values.delete(key);}};return {values,writes,key,draft,store};}
describe('pure retained document inventory using real FormDraftSession verification',()=>{
 it('returns a strict same-company/member/entity request with original context and no storage writes',()=>{const f=fixture();const found=listDocumentCreationConsultations(company,identity,'quotes',()=>f.store);expect(found).toHaveLength(1);expect(found[0].request).toEqual(f.draft.documentCreationRequest);expect(found[0].scope.context).toBe('quote:;project:');expect(found[0]).not.toHaveProperty('memberContextNonce');expect(f.writes).toEqual([]);});
 it.each(['company','member','organization','ready','entity'] as const)('refuses different %s context without writing',kind=>{const f=fixture(),current={...identity};if(kind==='company')current.companyId='other';if(kind==='member')current.memberId='other';if(kind==='organization')current.organizationId='other';if(kind==='ready')current.ready=false;expect(listDocumentCreationConsultations(company,current,kind==='entity'?'invoices':'quotes',()=>f.store)).toEqual([]);expect(f.writes).toEqual([]);});
 it.each(['legacy','invalid','expired','malformed','marker','acknowledged'] as const)('refuses %s retained record, preserving bytes',kind=>{const f=fixture(),raw=JSON.parse(f.values.get(f.key)!);if(kind==='legacy')delete raw.value.documentCreationRequest;if(kind==='invalid')raw.value.documentCreationId='invalid';if(kind==='expired')raw.savedAt=1;if(kind==='acknowledged')raw.acknowledged=true;if(kind==='malformed')f.values.set(f.key,'not JSON');else f.values.set(f.key,JSON.stringify(raw));if(kind==='marker')f.values.set(f.key.replace(FORM_DRAFT_PREFIX,FORM_DRAFT_COMPLETED_PREFIX),JSON.stringify({version:1,recordFingerprint:formDraftFingerprint(f.values.get(f.key)!)}));const before=[...f.values];expect(listDocumentCreationConsultations(company,identity,'quotes',()=>f.store)).toEqual([]);expect([...f.values]).toEqual(before);expect(f.writes).toEqual([]);});
 it.each(['draft','marker','key'] as const)('refused %s read never makes an entry or deletes local bytes',kind=>{const f=fixture();const original=f.store.getItem;f.store.getItem=key=>{if(kind!=='key'&&key===(kind==='draft'?f.key:f.key.replace(FORM_DRAFT_PREFIX,FORM_DRAFT_COMPLETED_PREFIX)))throw Error('Read forbidden');return original(key);};if(kind==='key')f.store.key=()=>{throw Error('Enumeration forbidden');};expect(listDocumentCreationConsultations(company,identity,'quotes',()=>f.store)).toEqual([]);expect(f.writes).toEqual([]);});
 it('a changed draft between first inventory read and core pair read is rejected',()=>{const f=fixture(),get=f.store.getItem;let reads=0;f.store.getItem=key=>{if(key===f.key&&++reads===2)return null;return get(key);};expect(listDocumentCreationConsultations(company,identity,'quotes',()=>f.store)).toEqual([]);expect(f.writes).toEqual([]);});
 it('request payload changed but same UUID remains a distinct explicit inventory snapshot',()=>{const f=fixture();const first=listDocumentCreationConsultations(company,identity,'quotes',()=>f.store)[0];const raw=JSON.parse(f.values.get(f.key)!);raw.value.documentCreationRequest.input.data.title='Later retained title';f.values.set(f.key,JSON.stringify(raw));const later=listDocumentCreationConsultations(company,identity,'quotes',()=>f.store)[0];expect(first.request.input.data.title).toBe('Private retained title');expect(later.request.input.data.title).toBe('Later retained title');expect(first.request).not.toEqual(later.request);expect(f.writes).toEqual([]);});
});
