import {beforeEach,describe,expect,it,vi} from 'vitest';
import {desktopApi,prepareDocumentSaveInput} from './bridge';
import {prepareDocumentCreationRequest,DocumentCreationUnconfirmedError,type DocumentCreationInput} from './documentCreationRequest';
import {WorkspaceOriginChangedError} from './workspaceOrigin';
import {WorkspaceMemberOriginChangedError} from './workspaceMemberOrigin';
import {diagnosticsApi,knownErrorIncident,recentDiagnosticEvents} from './diagnostics';
const transport=vi.hoisted(()=>({invoke:vi.fn()}));
vi.mock('@tauri-apps/api/core',()=>({Channel:class{},invoke:transport.invoke,isTauri:()=>false}));
const id='11111111-2222-4333-8444-555555555555',scope='company',nonce='a'.repeat(32);
const line={id:'line',catalogItemId:null,description:'Private line',quantity:2,unit:'h',unitPriceCents:3000,discountBp:200,vatRateBp:810};
function request(){return prepareDocumentCreationRequest(id,prepareDocumentSaveInput('invoices',{title:'Private title',status:'draft',notes:'Private notes',depositBasisLines:[line]},[line]) as DocumentCreationInput,scope,'member');}
function missing(req=request()){return {receiptVersion:1,creationRequestId:id,entity:req.input.entity,status:'missing',documentId:id,originalResponse:null,currentDocument:null,currentItems:[],originalMatchesCurrent:null};}
beforeEach(async()=>{transport.invoke.mockReset();transport.invoke.mockImplementation(async(command:string)=>{if(command==='clear_diagnostics')return;throw Error('Unexpected native command '+command);});await diagnosticsApi.clear();transport.invoke.mockClear();});
describe('actual bridge exact-input document creation and pure receipt',()=>{
 it('payload helper preserves former order, nullable fields, lines and deposit basis exactly',()=>{const req=request();expect(Object.keys(req.input)).toEqual(['entity','id','data','items']);expect(req.input.id).toBeNull();expect(req.input.items[0]).toEqual({id:null,catalog_item_id:null,description:'Private line',quantity:2,unit:'h',unit_price_cents:3000,discount_bp:200,vat_bp:810});expect(req.input.data.deposit_basis_json).toEqual([{id:'line',catalog_item_id:null,description:'Private line',quantity:2,unit:'h',unit_price_cents:3000,discount_bp:200,vat_bp:810}]);});
 it('probe is one guarded native call, no app-state/workspace/auth/licence read',async()=>{const req=request();transport.invoke.mockResolvedValue(missing(req));expect((await desktopApi.getDocumentCreationReceipt(req,scope,nonce)).status).toBe('missing');expect(transport.invoke.mock.calls).toEqual([['get_document_creation_receipt',{input:req.input,creationRequestId:id,expectedWorkspaceScope:scope,expectedMemberContextNonce:nonce}]]);});
 it('creation preflights the new pure command, sends input.id null + durable request, then two original-bound reads',async()=>{const req=request();transport.invoke.mockImplementation(async(command:string)=>command==='get_document_creation_receipt'?missing(req):command==='save_document_with_items'?{creationRequestId:id,document:{id},items:[{id:'line'}]}:command==='get_app_state'?{onboarding_completed:true}:{work_notes_scope:scope});await desktopApi.saveDocumentCreation(req,scope,nonce);expect(transport.invoke.mock.calls.map(call=>call[0])).toEqual(['get_document_creation_receipt','save_document_with_items','get_app_state','get_workspace']);expect(transport.invoke.mock.calls[0][1]).toEqual(transport.invoke.mock.calls[1][1]);expect(transport.invoke.mock.calls[1][1]).toEqual({input:req.input,creationRequestId:id,expectedWorkspaceScope:scope,expectedMemberContextNonce:nonce});for(const call of transport.invoke.mock.calls.slice(2))expect(call[1]).toEqual({expectedWorkspaceScope:scope,expectedMemberContextNonce:nonce});});
 it('lost ACK is ordinary correlated failure and performs no workspace read or replay',async()=>{const source=Error('Private transport message');transport.invoke.mockImplementation(async(command:string)=>{if(command==='get_document_creation_receipt')return missing();throw source;});const reason=await desktopApi.saveDocumentCreation(request(),scope,nonce).catch(error=>error);expect(reason).toBeInstanceOf(DocumentCreationUnconfirmedError);expect(knownErrorIncident(reason)?.code).toBe(knownErrorIncident(source)?.code);expect(transport.invoke.mock.calls.map(call=>call[0])).toEqual(['get_document_creation_receipt','save_document_with_items']);expect(reason).not.toHaveProperty('recordId');const logs=JSON.stringify(recentDiagnosticEvents());expect(logs).not.toContain('Private');expect(logs).not.toContain(id);expect(logs).not.toContain(nonce);expect(logs).not.toContain('deposit_basis_json');});
 it('old handler that ignores creationRequestId is never called when its pure receipt command is absent',async()=>{let writes=0;transport.invoke.mockImplementation(async(command:string)=>{if(command==='get_document_creation_receipt')throw 'Command get_document_creation_receipt not found';if(command==='save_document_with_items'){writes++;return {document:{id:'arbitrary-old-id'},items:[]};}throw Error('Unexpected command');});await expect(desktopApi.saveDocumentCreation(request(),scope,nonce)).rejects.toBeInstanceOf(DocumentCreationUnconfirmedError);expect(writes).toBe(0);expect(transport.invoke.mock.calls.map(call=>call[0])).toEqual(['get_document_creation_receipt']);});
 it('local provider assertion after the preflight refuses sending if its epoch changed',async()=>{transport.invoke.mockResolvedValue(missing());await expect(desktopApi.saveDocumentCreation(request(),scope,nonce,()=>{throw new WorkspaceMemberOriginChangedError();})).rejects.toBeInstanceOf(WorkspaceMemberOriginChangedError);expect(transport.invoke.mock.calls.map(call=>call[0])).toEqual(['get_document_creation_receipt']);});
 it.each(['physical','member'])('native %s guard retains terminal typed error',async(kind)=>{const source='Champ invalide : '+(kind==='physical'?'L’entreprise ouverte a changé. Rouvrez cette action dans le bon espace.':'Le compte connecté a changé. Rouvrez cette action avec le bon compte.');transport.invoke.mockRejectedValue(source);await expect(desktopApi.saveDocumentCreation(request(),scope,nonce)).rejects.toBeInstanceOf(kind==='physical'?WorkspaceOriginChangedError:WorkspaceMemberOriginChangedError);expect(transport.invoke).toHaveBeenCalledTimes(1);});
 it('request bound to another physical workspace is rejected before IPC',async()=>{await expect(desktopApi.getDocumentCreationReceipt(request(),'other',nonce)).rejects.toBeInstanceOf(WorkspaceOriginChangedError);expect(transport.invoke).not.toHaveBeenCalled();});
 it('absent nonce fails closed, with no historical unguarded probe fallback',async()=>{await expect(desktopApi.getDocumentCreationReceipt(request(),scope,undefined as never)).rejects.toBeInstanceOf(WorkspaceMemberOriginChangedError);expect(transport.invoke).not.toHaveBeenCalled();});
 it('malformed receipt and native error stay ordinary errors, not invented origin failure or missing proof',async()=>{transport.invoke.mockResolvedValue({...missing(),documentId:'other'});await expect(desktopApi.getDocumentCreationReceipt(request(),scope,nonce)).rejects.not.toBeInstanceOf(WorkspaceOriginChangedError);expect(transport.invoke).toHaveBeenCalledTimes(1);});
 it('historic saveDocument without origin/request keeps old native args and existing line IDs',async()=>{transport.invoke.mockImplementation(async(command:string)=>command==='get_app_state'?{onboarding_completed:false}:{});await desktopApi.saveDocument('quotes',{title:'Legacy',status:'draft'},[line],{id:'existing',lines:[line]} as never);const args=transport.invoke.mock.calls[0][1] as any;expect(Object.keys(args)).toEqual(['input']);expect(args.input.id).toBe('existing');expect(args.input.items[0].id).toBe('line');expect(args).not.toHaveProperty('creationRequestId');expect(transport.invoke.mock.calls[1]).toEqual(['get_app_state']);});
});
