export type GuideLesson = { chapter: string; actions: readonly string[]; tip: string };

export const guideLessons: Record<string, GuideLesson> = {
  agenda: { chapter: 'Organiser le travail', actions: ['Ouvrez l’agenda et choisissez la période à consulter.', 'Ajoutez un événement, sa date et les informations utiles.', 'Associez le projet concerné lorsque le rendez-vous fait partie de son planning.'], tip: 'Vérifiez les heures et les dates avant de prévoir plusieurs interventions le même jour.' },
  overview: { chapter: 'Bien démarrer', actions: ['Retrouvez vos chiffres et les actions à suivre sur l’accueil.', 'Utilisez le menu pour changer de module, ou la recherche « Aller à… ». Sur téléphone, touchez Menu.', 'Le bouton d’aide ouvre ce guide à tout moment. Choisissez un sujet ou continuez dans l’ordre.'], tip: 'Vous visitez vos écrans. Le guide ne crée ni ne modifie aucun document.' },
  clients: { chapter: 'Bien démarrer', actions: ['Fermez le guide, puis choisissez « Nouveau client ».', 'Renseignez son nom, son adresse complète et son e-mail, puis enregistrez.', 'Sélectionnez ensuite ce client dans vos projets et vos documents : ses coordonnées sont reprises.'], tip: 'Une adresse complète évite de revenir corriger le devis au moment de l’export.' },
  readiness: { chapter: 'Bien démarrer', actions: ['Renseignez l’identité de votre entreprise et son logo.', 'Vérifiez vos coordonnées bancaires et votre situation TVA avant de facturer.', 'Consultez les éléments encore à compléter dans le centre de préparation. Vous pouvez reprendre le guide complet depuis Aide.'], tip: 'Terminez ce parcours pour revenir travailler. Vous gardez accès à chaque rubrique du guide.' },
  catalog: { chapter: 'Organiser le travail', actions: ['Ajoutez vos prestations et vos articles habituels au catalogue.', 'Définissez l’unité, le prix et le taux TVA adapté à chaque ligne.', 'Retrouvez ces éléments pendant la préparation d’un devis pour éviter de les ressaisir.'], tip: 'Pour un article suivi en stock, enregistrez les mouvements qui expliquent les entrées et les sorties.' },
  projects: { chapter: 'Organiser le travail', actions: ['Créez un projet et associez-le au bon client.', 'Ouvrez son dossier pour ranger plans, photos et documents, puis organiser les tâches.', 'Rattachez vos devis, factures, heures et dépenses au projet pour retrouver son activité au même endroit.'], tip: 'Consultez l’état de synchronisation avant de changer d’appareil. Une pièce en attente d’envoi reste locale.' },
  quotes: { chapter: 'Devis et factures', actions: ['Créez un devis : choisissez le client et le projet, puis ajoutez vos prestations.', 'Rédigez vos conditions, vérifiez les totaux et la présentation dans l’aperçu.', 'Émettez le devis, notez son acceptation et utilisez la conversion pour créer la facture ou l’acompte.'], tip: 'Ouvrez le dossier lié pour retrouver l’acompte et la facture finale. Contrôlez la déduction avant l’émission.' },
  'recurring-documents': { chapter: 'Devis et factures', actions: ['Ouvrez une commande confirmée en CHF contenant des prestations directes.', 'Choisissez la fréquence et le délai de paiement de la facturation récurrente.', 'Contrôlez les brouillons préparés à l’échéance, puis émettez les documents souhaités.'], tip: 'La préparation fonctionne lorsque l’app est ouverte. Un brouillon n’est ni émis ni envoyé automatiquement.' },
  invoices: { chapter: 'Devis et factures', actions: ['Créez une facture ou ouvrez celle issue du devis accepté.', 'Vérifiez l’échéance, les coordonnées bancaires, la référence et les éventuels acomptes.', 'Après émission, exportez le document. Enregistrez les encaissements pour mettre à jour le solde.'], tip: 'Une QR-facture suisse nécessite des coordonnées bancaires et des adresses valides.' },
  reminders: { chapter: 'Devis et factures', actions: ['Consultez les factures arrivées à échéance.', 'Vérifiez les paiements déjà reçus et le solde restant.', 'Choisissez le niveau de relance, contrôlez le destinataire et préparez l’envoi.'], tip: 'Un paiement partiel réduit le montant à réclamer. Vérifiez-le avant de relancer.' },
  time: { chapter: 'Équipe et dépenses', actions: ['Choisissez le collaborateur et le projet concernés.', 'Lancez le minuteur ou saisissez directement une durée et sa date.', 'Indiquez si le temps est facturable, puis contrôlez les heures dans le suivi du projet.'], tip: 'Arrêtez le minuteur à la fin de l’activité pour garder un suivi précis.' },
  payroll: { chapter: 'Équipe et dépenses', actions: ['Créez le collaborateur, ou importez une fiche de salaire pour préparer ses informations.', 'Relisez l’identité, la période, le salaire et les retenues proposés avant de confirmer.', 'Préparez la paie, personnalisez sa présentation et retrouvez le certificat annuel dans les documents de salaire.'], tip: 'Les montants importés doivent être vérifiés. Le certificat annuel exige le contrôle de toutes les périodes concernées.' },
  purchases: { chapter: 'Équipe et dépenses', actions: ['Renseignez le fournisseur et le projet si l’achat lui est lié.', 'Ajoutez la facture ou le justificatif, puis vérifiez les montants et la TVA.', 'Suivez les réceptions, les écarts et les paiements dans le parcours d’achat.'], tip: 'Conservez le justificatif d’achat pour permettre le contrôle de l’impôt préalable.' },
  bank: { chapter: 'Suivre les finances', actions: ['Exportez un relevé XML CAMT depuis votre banque.', 'Importez-le et associez-le au compte concerné dans Zentra.', 'Vérifiez les rapprochements proposés, les références et les montants, puis confirmez les opérations.'], tip: 'Un rapprochement incertain demande votre choix : consultez la facture avant de confirmer.' },
  reports: { chapter: 'Suivre les finances', actions: ['Choisissez le rapport utile pour suivre l’activité.', 'Consultez les heures, dépenses et ventes rattachées à vos projets.', 'Vérifiez la période et les données disponibles avant d’interpréter une marge.'], tip: 'Des heures ou des achats manquants peuvent modifier le résultat affiché.' },
  accounting: { chapter: 'Suivre les finances', actions: ['Consultez les écritures du journal et le détail des comptes.', 'Contrôlez la TVA due et l’impôt préalable avec vos pièces justificatives.', 'En fin d’année, vérifiez les contrôles de clôture et exportez les états financiers pour votre fiduciaire.'], tip: 'Les réglages comptables et fiscaux doivent correspondre à votre entreprise.' },
  settings: { chapter: 'Personnaliser et protéger', actions: ['Dans les réglages de documents, choisissez les couleurs et la présentation des devis, factures et autres pièces.', 'Créez une sauvegarde et conservez une copie hors de cet appareil.', 'Consultez la maintenance pour vérifier les mises à jour disponibles et leur installation.'], tip: 'La synchronisation et la sauvegarde ont des rôles différents : conservez aussi une copie de secours.' },
};

export const GUIDE_PROGRESS_KEY = 'zentra-guide-progress-v1';
export function restoredGuideIndex(ids: readonly string[], saved: string | null): number {
  return Math.max(0, saved === null ? 0 : ids.indexOf(saved));
}
