import { getAppLanguage, type AppLanguage } from './language';

// Display translations of the existing NOGA 2025 catalogue. Codes and stored profiles never change.
export const nogaLabels: Record<string, readonly [string, string, string]> = {
  A: ['Land- und Forstwirtschaft, Fischerei','Agricoltura, silvicoltura e pesca','Agriculture, forestry and fishing'],
  B: ['Bergbau und Gewinnung von Steinen und Erden','Attività estrattive','Mining and quarrying'],
  C: ['Verarbeitendes Gewerbe / Herstellung von Waren','Attività manifatturiere','Manufacturing'],
  D: ['Energieversorgung','Fornitura di energia elettrica, gas, vapore e aria condizionata','Electricity, gas, steam and air conditioning supply'],
  E: ['Wasserversorgung; Abwasser- und Abfallentsorgung und Beseitigung von Umweltverschmutzungen','Fornitura di acqua; reti fognarie, gestione dei rifiuti e risanamento','Water supply; sewerage, waste management and remediation activities'],
  F: ['Baugewerbe','Costruzioni','Construction'],
  G: ['Handel','Commercio','Wholesale and retail trade'],
  H: ['Verkehr und Lagerei','Trasporto e magazzinaggio','Transportation and storage'],
  I: ['Gastgewerbe / Beherbergung und Gastronomie','Servizi di alloggio e ristorazione','Accommodation and food service activities'],
  J: ['Verlagswesen, Rundfunk sowie Produktion und Verbreitung von Inhalten','Editoria, trasmissione e produzione e distribuzione di contenuti','Publishing, broadcasting, and content production and distribution activities'],
  K: ['Telekommunikation, Programmierung, Beratung, IT-Infrastruktur und sonstige Informationsdienstleistungen','Telecomunicazioni, programmazione, consulenza e infrastrutture informatiche e altri servizi d’informazione','Telecommunications, computer programming, consulting, computing infrastructure and other information service activities'],
  L: ['Finanz- und Versicherungsdienstleistungen','Attività finanziarie e assicurative','Financial and insurance activities'],
  M: ['Grundstücks- und Wohnungswesen','Attività immobiliari','Real estate activities'],
  N: ['Freiberufliche, wissenschaftliche und technische Dienstleistungen','Attività professionali, scientifiche e tecniche','Professional, scientific and technical activities'],
  O: ['Administrative und unterstützende Dienstleistungen','Attività amministrative e servizi di supporto','Administrative and support service activities'],
  P: ['Öffentliche Verwaltung, Verteidigung; Sozialversicherung','Amministrazione pubblica e difesa; assicurazione sociale obbligatoria','Public administration and defence; compulsory social security'],
  Q: ['Erziehung und Unterricht','Istruzione','Education'],
  R: ['Gesundheits- und Sozialwesen','Sanità e assistenza sociale','Human health and social work activities'],
  S: ['Kunst, Sport und Erholung','Attività artistiche, sportive e ricreative','Arts, sports and recreation'],
  T: ['Sonstige Dienstleistungen','Altre attività di servizi','Other service activities'],
  U: ['Private Haushalte als Arbeitgeber; Herstellung von Waren und Erbringung von Dienstleistungen durch private Haushalte für den Eigenbedarf','Attività di famiglie e convivenze come datori di lavoro e produzione di beni e servizi per uso proprio','Activities of households as employers; undifferentiated goods- and services-producing activities of households for own use'],
  V: ['Exterritoriale Organisationen und Körperschaften','Organizzazioni e organismi extraterritoriali','Activities of extraterritorial organisations and bodies'],
  '01': ['Landwirtschaft, Jagd und damit verbundene Tätigkeiten','Produzioni vegetali e animali, caccia e servizi connessi','Crop and animal production, hunting and related service activities'],
  '02': ['Forstwirtschaft und Holzeinschlag','Silvicoltura e utilizzo di aree forestali','Forestry and logging'],
  '03': ['Fischerei und Aquakultur','Pesca e acquacoltura','Fishing and aquaculture'],
  '05': ['Kohlenbergbau','Estrazione di carbone e lignite','Mining of coal and lignite'],
  '06': ['Gewinnung von Erdöl und Erdgas','Estrazione di petrolio greggio e gas naturale','Extraction of crude petroleum and natural gas'],
  '07': ['Erzbergbau','Estrazione di minerali metalliferi','Mining of metal ores'],
  '08': ['Gewinnung von Steinen und Erden, sonstiger Bergbau','Altre attività estrattive','Other mining and quarrying'],
  '09': ['Dienstleistungen für den Bergbau und die Gewinnung von Steinen und Erden','Servizi di supporto alle attività estrattive','Mining support service activities'],
  '10': ['Herstellung von Nahrungs- und Futtermitteln','Industrie alimentari','Manufacture of food products'],
  '11': ['Getränkeherstellung','Produzione di bevande','Manufacture of beverages'],
  '12': ['Tabakverarbeitung','Produzione di prodotti a base di tabacco','Manufacture of tobacco products'],
  '13': ['Herstellung von Textilien','Industrie tessili','Manufacture of textiles'],
  '14': ['Herstellung von Bekleidung','Confezione di articoli di abbigliamento','Manufacture of wearing apparel'],
  '15': ['Herstellung von Leder, Lederwaren und ähnlichen Waren aus anderen Materialien','Fabbricazione di pelle, articoli in pelle e prodotti simili in altri materiali','Manufacture of leather, related products and similar products of other materials'],
  '16': ['Herstellung von Holz-, Flecht-, Korb- und Korkwaren, ohne Möbel','Lavorazione del legno e fabbricazione di prodotti in legno e sughero, esclusi i mobili; articoli in paglia e materiali da intreccio','Manufacture of wood and products of wood and cork, except furniture; articles of straw and plaiting materials'],
  '17': ['Herstellung von Papier, Pappe und Waren daraus','Fabbricazione di carta e di prodotti di carta','Manufacture of paper and paper products'],
  '18': ['Druckerzeugnisse und Vervielfältigung von bespielten Ton-, Bild- und Datenträgern','Stampa e riproduzione di supporti registrati','Printing and reproduction of recorded media'],
  '19': ['Kokerei und Mineralölverarbeitung','Fabbricazione di coke e prodotti della raffinazione del petrolio','Manufacture of coke and refined petroleum products'],
  '20': ['Herstellung von chemischen Erzeugnissen','Fabbricazione di prodotti chimici','Manufacture of chemicals and chemical products'],
  '21': ['Herstellung von pharmazeutischen Erzeugnissen','Fabbricazione di prodotti farmaceutici','Manufacture of pharmaceutical products'],
  '22': ['Herstellung von Gummi- und Kunststoffwaren','Fabbricazione di articoli in gomma e materie plastiche','Manufacture of rubber and plastic products'],
  '23': ['Herstellung von sonstigen Erzeugnissen aus nichtmetallischen Mineralien','Fabbricazione di altri prodotti della lavorazione di minerali non metalliferi','Manufacture of other non-metallic mineral products'],
  '24': ['Metallerzeugung und -bearbeitung','Metallurgia','Manufacture of basic metals'],
  '25': ['Herstellung von Metallerzeugnissen, ohne Maschinen und Ausrüstungen','Fabbricazione di prodotti in metallo, esclusi macchinari e attrezzature','Manufacture of fabricated metal products, except machinery and equipment'],
  '26': ['Herstellung von Datenverarbeitungsgeräten, elektronischen und optischen Erzeugnissen','Fabbricazione di computer e prodotti di elettronica e ottica','Manufacture of computer, electronic and optical products'],
  '27': ['Herstellung von elektrischen Ausrüstungen','Fabbricazione di apparecchiature elettriche','Manufacture of electrical equipment'],
  '28': ['Maschinenbau, anderweitig nicht genannt','Fabbricazione di macchinari e apparecchiature n.c.a.','Manufacture of machinery and equipment n.e.c.'],
  '29': ['Herstellung von Automobilen und Automobilteilen','Fabbricazione di autoveicoli','Manufacture of motor vehicles'],
  '30': ['Sonstiger Fahrzeugbau','Fabbricazione di altri mezzi di trasporto','Manufacture of other transport equipment'],
  '31': ['Herstellung von Möbeln','Fabbricazione di mobili','Manufacture of furniture'],
  '32': ['Herstellung von sonstigen Waren','Altre industrie manifatturiere','Other manufacturing'],
  '33': ['Reparatur, Instandhaltung und Installation von Maschinen und Ausrüstungen','Riparazione, manutenzione e installazione di macchinari e attrezzature','Repair, maintenance and installation of machinery and equipment'],
  '35': ['Energieversorgung','Fornitura di energia elettrica, gas, vapore e aria condizionata','Electricity, gas, steam and air conditioning supply'],
  '36': ['Wasserversorgung','Raccolta, trattamento e fornitura di acqua','Water collection, treatment and supply'],
  '37': ['Abwasserentsorgung','Gestione delle reti fognarie','Sewerage'],
  '38': ['Sammlung, Verwertung und Beseitigung von Abfällen','Raccolta, recupero e smaltimento dei rifiuti','Waste collection, recovery and disposal activities'],
  '39': ['Beseitigung von Umweltverschmutzungen und sonstige Entsorgung','Attività di risanamento e altri servizi di gestione dei rifiuti','Remediation and other waste management service activities'],
  '41': ['Bau von Wohn- und Nichtwohngebäuden','Costruzione di edifici residenziali e non residenziali','Construction of residential and non-residential buildings'],
  '42': ['Tiefbau','Ingegneria civile','Civil engineering'],
  '43': ['Vorbereitende Baustellenarbeiten, Bauinstallation und sonstiger Ausbau','Lavori di costruzione specializzati','Specialised construction activities'],
  '46': ['Grosshandel','Commercio all’ingrosso','Wholesale trade'],
  '47': ['Detailhandel','Commercio al dettaglio','Retail trade'],
  '49': ['Landverkehr und Transport in Rohrfernleitungen','Trasporto terrestre e mediante condotte','Land transport and transport via pipelines'],
  '50': ['Schifffahrt','Trasporto per vie d’acqua','Water transport'],
  '51': ['Luftfahrt','Trasporto aereo','Air transport'],
  '52': ['Lagerei und sonstige Dienstleistungen für den Verkehr','Magazzinaggio e attività di supporto ai trasporti','Warehousing and support activities for transportation'],
  '53': ['Post-, Kurier- und Expressdienste','Servizi postali e attività di corriere','Postal and courier activities'],
  '55': ['Beherbergung','Alloggio','Accommodation'],
  '56': ['Gastronomie','Attività dei servizi di ristorazione','Food and beverage service activities'],
  '58': ['Verlagswesen','Attività editoriali','Publishing activities'],
  '59': ['Herstellung von Filmen und Fernsehprogrammen; Tonstudios und Musikverlag','Produzione cinematografica, video e programmi televisivi; registrazioni sonore ed editoria musicale','Motion picture, video and television programme production; sound recording and music publishing'],
  '60': ['Programmgestaltung, Rundfunk, Nachrichtenagenturen und sonstige Verbreitung von Inhalten','Programmazione, trasmissione, agenzie di stampa e altre attività di distribuzione di contenuti','Programming, broadcasting, news agency and other content distribution activities'],
  '61': ['Telekommunikation','Telecomunicazioni','Telecommunications'],
  '62': ['Programmierung, Beratung und sonstige IT-Dienstleistungen','Programmazione, consulenza e altre attività informatiche','Computer programming, consultancy and related activities'],
  '63': ['IT-Infrastruktur, Datenverarbeitung und sonstige Informationsdienstleistungen','Infrastrutture informatiche, elaborazione dati e altri servizi d’informazione','Computing infrastructure, data processing and other information service activities'],
  '64': ['Finanzdienstleistungen, ohne Versicherungen und Pensionskassen','Servizi finanziari, escluse assicurazioni e fondi pensione','Financial service activities, except insurance and pension funding'],
  '65': ['Versicherungen, Rückversicherungen und Pensionskassen, ohne Sozialversicherung','Assicurazioni, riassicurazioni e fondi pensione, esclusa l’assicurazione sociale obbligatoria','Insurance, reinsurance and pension funding, except compulsory social security'],
  '66': ['Mit Finanz- und Versicherungsdienstleistungen verbundene Tätigkeiten','Attività ausiliarie dei servizi finanziari e assicurativi','Activities auxiliary to financial services and insurance activities'],
  '68': ['Grundstücks- und Wohnungswesen','Attività immobiliari','Real estate activities'],
  '69': ['Rechts- und Steuerberatung, Wirtschaftsprüfung','Attività legali e contabili','Legal and accounting activities'],
  '70': ['Unternehmensverwaltung und Unternehmensberatung','Attività di sedi centrali e consulenza gestionale','Activities of head offices and management consultancy'],
  '71': ['Architektur- und Ingenieurbüros; technische, physikalische und chemische Untersuchung','Attività di architettura e ingegneria; collaudi e analisi tecniche','Architectural and engineering activities; technical testing and analysis'],
  '72': ['Forschung und Entwicklung','Ricerca scientifica e sviluppo','Scientific research and development'],
  '73': ['Werbung, Marktforschung und Public Relations','Pubblicità, ricerche di mercato e pubbliche relazioni','Advertising, market research and public relations activities'],
  '74': ['Sonstige freiberufliche, wissenschaftliche und technische Tätigkeiten','Altre attività professionali, scientifiche e tecniche','Other professional, scientific and technical activities'],
  '75': ['Veterinärwesen','Servizi veterinari','Veterinary activities'],
  '77': ['Vermietung von beweglichen Sachen','Attività di noleggio e leasing operativo','Rental and leasing activities'],
  '78': ['Vermittlung und Überlassung von Arbeitskräften','Attività di ricerca, selezione e fornitura di personale','Employment activities'],
  '79': ['Reisebüros, Reiseveranstalter und sonstige Reservierungsdienstleistungen','Agenzie di viaggio, operatori turistici, servizi di prenotazione e attività connesse','Travel agency, tour operator, reservation service and related activities'],
  '80': ['Wach- und Sicherheitsdienste sowie Detekteien','Attività investigative e di sicurezza','Investigation and security activities'],
  '81': ['Gebäudebetreuung; Garten- und Landschaftsbau','Servizi per edifici e paesaggio','Services to buildings and landscape activities'],
  '82': ['Büro- und sonstige wirtschaftliche Dienstleistungen für Unternehmen','Servizi d’ufficio, supporto amministrativo e altri servizi alle imprese','Office administrative, office support and other business support activities'],
  '84': ['Öffentliche Verwaltung, Verteidigung; Sozialversicherung','Amministrazione pubblica e difesa; assicurazione sociale obbligatoria','Public administration and defence; compulsory social security'],
  '85': ['Erziehung und Unterricht','Istruzione','Education'],
  '86': ['Gesundheitswesen','Attività dei servizi sanitari','Human health activities'],
  '87': ['Heime und stationäre Pflege','Servizi di assistenza sociale residenziale','Residential care activities'],
  '88': ['Sozialwesen ohne Heime','Assistenza sociale non residenziale','Social work activities without accommodation'],
  '90': ['Kreative, künstlerische und darstellende Tätigkeiten','Attività creative, artistiche e di spettacolo','Creative, arts and entertainment activities'],
  '91': ['Bibliotheken, Archive, Museen und sonstige kulturelle Tätigkeiten','Biblioteche, archivi, musei e altre attività culturali','Libraries, archives, museums and other cultural activities'],
  '92': ['Spiel-, Wett- und Lotteriewesen','Attività di giochi d’azzardo e scommesse','Gambling and betting activities'],
  '93': ['Sport, Unterhaltung und Erholung','Attività sportive, di intrattenimento e divertimento','Sports activities and amusement and recreation activities'],
  '94': ['Interessenvertretungen sowie kirchliche und sonstige Vereinigungen','Attività di organizzazioni associative','Activities of membership organisations'],
  '95': ['Reparatur und Instandhaltung von Computern, Gebrauchsgütern, Automobilen und Motorrädern','Riparazione e manutenzione di computer, beni per uso personale e domestico, autoveicoli e motocicli','Repair and maintenance of computers, personal and household goods, motor vehicles and motorcycles'],
  '96': ['Persönliche Dienstleistungen','Attività di servizi alla persona','Personal service activities'],
  '97': ['Private Haushalte als Arbeitgeber von Hauspersonal','Attività di famiglie e convivenze come datori di lavoro per personale domestico','Activities of households as employers of domestic personnel'],
  '98': ['Herstellung von Waren und Dienstleistungen durch private Haushalte für den Eigenbedarf','Produzione di beni e servizi indifferenziati da parte di famiglie per uso proprio','Undifferentiated goods- and services-producing activities of households for own use'],
  '99': ['Exterritoriale Organisationen und Körperschaften','Organizzazioni e organismi extraterritoriali','Activities of extraterritorial organisations and bodies'],
};

export function nogaLabel(code: string, french: string, language: AppLanguage = getAppLanguage()): string {
  if (language === 'fr') return french;
  return nogaLabels[code]?.[language === 'de' ? 0 : language === 'it' ? 1 : 2] ?? french;
}
