import type { PayrollAiRuntimeDevice } from './payrollAiRuntimePolicy';

export type PayrollAiGenerationPlan = {
  maxNewTokens: number;
  phaseTokenBudgets?: { core: number; lines: number };
  passes: 1 | 2;
  pagesPerBatch: number;
  progressEveryTokens: number;
  splitImagesWhenTextAvailable: boolean;
};

const GENERATION_PLANS: Record<PayrollAiRuntimeDevice, PayrollAiGenerationPlan> = {
  webgpu: {
    // WebGPU keeps the independent second reading and the generous ceiling.
    // The JSON completion criterion normally stops well before this ceiling.
    maxNewTokens: 1_100,
    passes: 2,
    pagesPerBatch: 3,
    progressEveryTokens: 8,
    splitImagesWhenTextAvailable: true,
  },
  wasm: {
    // On ordinary CPUs, 1 100 tokens followed by a second pass can take well
    // over the UI watchdog. Keep every visible payroll line, but omit empty
    // output fields and stop after one deliberately weak, human-reviewed pass.
    maxNewTokens: 384,
    phaseTokenBudgets: { core: 96, lines: 288 },
    passes: 1,
    pagesPerBatch: 1,
    progressEveryTokens: 4,
    splitImagesWhenTextAvailable: false,
  },
};

export function payrollAiGenerationPlan(device: PayrollAiRuntimeDevice): PayrollAiGenerationPlan {
  return { ...GENERATION_PLANS[device] };
}

/**
 * A WebGPU request may fall back inside the same Worker call. The batch must
 * therefore fit both the initial runtime and every automatic fallback, not
 * just the runtime reported by the initial capability check.
 */
export function payrollAiSafePageBatchSize(initialDevice: PayrollAiRuntimeDevice) {
  if (initialDevice === 'wasm') return GENERATION_PLANS.wasm.pagesPerBatch;
  return Math.min(
    GENERATION_PLANS.webgpu.pagesPerBatch,
    GENERATION_PLANS.wasm.pagesPerBatch,
  );
}

export function payrollAiSafePageBatches<T>(
  pages: readonly T[],
  initialDevice: PayrollAiRuntimeDevice,
): T[][] {
  const batchSize = payrollAiSafePageBatchSize(initialDevice);
  const batches: T[][] = [];
  for (let offset = 0; offset < pages.length; offset += batchSize) {
    batches.push(pages.slice(offset, offset + batchSize));
  }
  return batches;
}

/**
 * Return the first complete top-level object generated by the model.
 * Braces inside JSON strings are ignored, including after an escaped quote.
 * The function is intentionally structural: the existing strict parser owns
 * schema validation and the small model's narrowly supported Python literals.
 */
export function firstCompleteGeneratedJson(text: string): string | null {
  let start = -1;
  let depth = 0;
  let quote: 'single' | 'double' | null = null;
  let escaped = false;
  let singleRawStart = -1;

  for (let index = 0; index < text.length; index += 1) {
    const character = text[index];
    if (quote) {
      let implicitlyClosedSingleAmount = false;
      if (escaped) {
        escaped = false;
      } else if (character === '\\') {
        escaped = true;
      } else if (quote === 'double' && character === '"') {
        quote = null;
      } else if (quote === 'single' && character === "'") {
        // SmolVLM sometimes emits a Python-like dict. Match the strict
        // normalizer's narrow rule so apostrophes in D'Amico and 6'500.00 do
        // not end the string or expose braces contained in the value.
        let lookahead = index + 1;
        while (/\s/.test(text[lookahead] ?? '')) lookahead += 1;
        const next = text[lookahead] ?? '';
        if (!next || ':,}]'.includes(next)) {
          quote = null;
          singleRawStart = -1;
        }
      } else if (
        quote === 'single'
        && singleRawStart >= 0
        && (character === ',' || character === '}')
      ) {
        const content = text.slice(singleRawStart, index);
        if (/^(?:CHF\s*)?\d{1,3}(?:['’\u00a0\u202f ]\d{3})+(?:[.,]\d{1,2})$/.test(content)) {
          // Match pythonLiteralToJson: the tiny model occasionally emits
          // `'6'500.00,` or `'6'284.00}` without the final quote. The comma or
          // brace closes that numeric string implicitly; a brace still needs
          // to be processed below as structural syntax.
          quote = null;
          singleRawStart = -1;
          implicitlyClosedSingleAmount = true;
        }
      }
      if (!implicitlyClosedSingleAmount) continue;
    }
    if (character === '"' && depth > 0) {
      quote = 'double';
      continue;
    }
    if (character === "'" && depth > 0) {
      quote = 'single';
      singleRawStart = index + 1;
      continue;
    }
    if (character === '{') {
      if (depth === 0) start = index;
      depth += 1;
      continue;
    }
    if (character === '}' && depth > 0) {
      depth -= 1;
      if (depth === 0 && start >= 0) return text.slice(start, index + 1);
    }
  }
  return null;
}

export function payrollAiGenerationPercent(input: {
  generatedTokens: number;
  maxNewTokens: number;
  startPercent: number;
  endPercent: number;
}) {
  const start = Math.max(0, Math.min(100, Math.round(input.startPercent)));
  const end = Math.max(start, Math.min(100, Math.round(input.endPercent)));
  if (input.maxNewTokens <= 0) return start;
  const ratio = Math.max(0, Math.min(1, input.generatedTokens / input.maxNewTokens));
  return Math.min(end, start + Math.floor((end - start) * ratio));
}
