// @vitest-environment jsdom
// @vitest-environment-options {"url":"http://localhost","pretendToBeVisual":true}
/** Actual candidate WorkspaceApp/DocumentEditor/quick-client/bridge/recovery/ReactDOM. Native IPC
 * is explicitly simulated, including the guard after a held local operation; no auth/network requests.
 * Unrelated preview services are stubbed; no production/network/server access. */
import {act as reactAct,useState} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {desktopApi} from './bridge';
import {WorkspaceApp} from './WorkspaceApp';
import {FormDraftIdentityProvider,draftText} from './useFormDraft';
import {ZentraAssistantProvider} from './ZentraAssistant';
import {initialOnboardingSettings} from './onboardingDraft';
import {FORM_DRAFT_PREFIX} from './formDrafts';
import type {Workspace} from './types';
import {setAppLanguage} from './language';
import {languageAssets} from 'virtual:zentra-language-assets';
import {quickClientCreationRecovery} from './documentQuickClientDraft';
import {documentTotals} from './utils';

const transport=vi.hoisted(()=>({invoke:vi.fn()}));
vi.mock('@tauri-apps/api/core',()=>({Channel:class{},invoke:transport.invoke,isTauri:()=>false}));
const scope='quick-client-durable-company',member='11111111-1111-4111-8111-111111111111',nonceA='a'.repeat(32),nonceB='b'.repeat(32);
const guardMessage='Champ invalide : Le compte connecté a changé. Rouvrez cette action avec le bon compte.';
function deferred<T=void>(){let resolve!:(value:T)=>void;const promise=new Promise<T>(yes=>resolve=yes);return {promise,resolve};}
let root:Root|undefined,container:HTMLDivElement,workspace:Workspace,exposed:any;
let nativeNonce=nonceA,mode='',blocked=false,writeHold:ReturnType<typeof deferred>|null=null,readHold:ReturnType<typeof deferred>|null=null;
let writeEntered=false,readEntered=false,writes=0,clients:any[]=[],quotes:any[]=[],projects:any[]=[],quoteItems:any[]=[],reads:any[]=[],publications:Workspace[]=[],externalRequests=0,writeAttempts:any[]=[],nativeScope=scope;
let beforeWrite:((args:any)=>void)|undefined;
const settings={...structuredClone(initialOnboardingSettings),organization:{...initialOnboardingSettings.organization,legalName:'Atelier témoin',contactName:'Compte témoin'}};
function rawWorkspace(){return {work_notes_scope:scope,settings:{company_name:'Atelier témoin',extra_settings_json:JSON.stringify(settings)},projects:structuredClone(projects),quotes:structuredClone(quotes),quote_items:structuredClone(quoteItems),clients:structuredClone(clients),time_entries:[]};}
function enforce(args:any){if(args?.expectedWorkspaceScope!==undefined&&args.expectedWorkspaceScope!==nativeScope)throw 'Champ invalide : L’entreprise ouverte a changé. Rouvrez cette action dans le bon espace.';if(args?.expectedMemberContextNonce!==undefined&&args.expectedMemberContextNonce!==nativeNonce)throw guardMessage;}
async function settle(){await reactAct(async()=>{for(let i=0;i<25;i++)await Promise.resolve();await new Promise<void>(resolve=>setTimeout(resolve,1));});}
async function until(check:()=>boolean){for(let i=0;i<40&&!check();i++)await settle();expect(check()).toBe(true);}
const buttons=(text:string)=>Array.from(document.querySelectorAll<HTMLButtonElement>('button')).filter(node=>node.textContent?.trim()===text);
async function click(text:string){const button=buttons(text)[0];expect(button,document.body.textContent??'').toBeDefined();await reactAct(async()=>button.click());await settle();}
function draftKeys(){return Array.from({length:localStorage.length},(_,i)=>localStorage.key(i)!).filter(key=>key.startsWith(FORM_DRAFT_PREFIX));}
async function change(name:string,value:string,events=true){const input=document.querySelector<HTMLInputElement|HTMLSelectElement|HTMLTextAreaElement>(`[role="dialog"] [name="${name}"]`)!;expect(input,name).not.toBeNull();await reactAct(async()=>{const prototype=input instanceof HTMLSelectElement?HTMLSelectElement.prototype:input instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(prototype,'value')!.set!.call(input,value);if(events){input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));}});await settle();}
async function openDocument(entity:'quotes'|'invoices'='quotes'){await click('Ventes');if(entity==='invoices')await click('Factures');await click(entity==='quotes'?'Nouveau devis':'Nouvelle facture');await until(()=>document.querySelector('[role="dialog"] [name="title"]')!==null);}
const quickNames=['contactPerson','company','email','phone','street','buildingNumber','postalCode','city','canton','country'];
async function quickChange(name:string,value:string,events=true){const section=document.querySelector('[role="dialog"] .document-inline-card')!;const input=Array.from(section.querySelectorAll<HTMLInputElement>('input'))[quickNames.indexOf(name)];expect(input,name).toBeDefined();await reactAct(async()=>{Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value')!.set!.call(input,value);if(events){input.dispatchEvent(new Event('input',{bubbles:true}));input.dispatchEvent(new Event('change',{bubbles:true}));}});await settle();}
async function prepareQuick(entity:'quotes'|'invoices'='quotes'){await openDocument(entity);await change('title','Travaux témoins');await click('Nouveau contact');for(const [name,value] of Object.entries({contactPerson:'Alice Témoin',company:'Client Témoin SA',email:'alice@example.test',phone:'+41220000000',street:'Rue témoin',buildingNumber:'7',postalCode:'1201',city:'Genève',canton:'GE',country:'CH'}))await quickChange(name,value);expect(draftKeys()).toHaveLength(1);}
async function closeDocument(){const button=document.querySelector<HTMLButtonElement>('[role="dialog"] button[aria-label^="Fermer «"]');expect(button).not.toBeNull();await reactAct(async()=>button!.click());await settle();}
async function restoreDocument(){await click('Nouveau devis');await until(()=>buttons(draftText('Reprendre ma saisie')).length>0);await click(draftText('Reprendre ma saisie'));}
function draftValue(){return JSON.parse(localStorage.getItem(draftKeys()[0])!).value as any;}
async function addQuick(){await click('Ajouter et sélectionner');}
function verifyRetained(){expect(draftKeys()).toHaveLength(1);expect(document.querySelector('[role="dialog"] form')).not.toBeNull();expect(document.body.textContent).not.toContain('a été ajouté et sélectionné.');}
function Host(){const [current,setCurrent]=useState(workspace);const [nonce,setNonce]=useState<string|undefined>(nonceA);exposed={setNonce,setCurrent};return <FormDraftIdentityProvider companyId={scope} organizationId="org-témoin" memberId={member} memberContextNonce={nonce} ready><ZentraAssistantProvider><WorkspaceApp workspace={current} setWorkspace={next=>{if(next&&typeof next!=='function'){publications.push(next);setCurrent(next);}}}/></ZentraAssistantProvider></FormDraftIdentityProvider>;}
async function restart(){await reactAct(async()=>root!.unmount());root=undefined;container.remove();blocked=false;mode='';workspace=await desktopApi.loadWorkspace();container=document.createElement('div');container.id='root';document.body.append(container);root=createRoot(container);await reactAct(async()=>root!.render(<Host/>));await settle();}

beforeEach(async()=>{
  nativeScope=scope;nativeNonce=nonceA;beforeWrite=undefined;writeAttempts=[];mode='';blocked=false;writeHold=null;readHold=null;writeEntered=false;readEntered=false;writes=0;clients=[];quotes=[];quoteItems=[];projects=[];reads=[];publications=[];externalRequests=0;localStorage.clear();sessionStorage.clear();
  vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);vi.stubGlobal('fetch',vi.fn(async()=>{externalRequests++;throw Error('External fetch is disabled in this closed fixture.');}));
  Object.defineProperty(window,'matchMedia',{value:vi.fn(()=>({matches:false,addEventListener:()=>{},removeEventListener:()=>{},addListener:()=>{},removeListener:()=>{}})),configurable:true});
  HTMLElement.prototype.scrollIntoView=()=>{};vi.stubGlobal('ResizeObserver',class{observe(){}unobserve(){}disconnect(){}});
  transport.invoke.mockReset();transport.invoke.mockImplementation(async(command:string,args:any)=>{
    if(command==='get_app_state'||command==='get_workspace'){
      reads.push({command,args:structuredClone(args??{}),nonce:nativeNonce});if(readHold){readEntered=true;await readHold.promise;}enforce(args);if(blocked)throw Error('Lecture locale momentanément indisponible.');
      return command==='get_app_state'?{onboarding_completed:true}:rawWorkspace();
    }
    if(command==='create_record'&&args.entity==='clients'){
      writeAttempts.push(structuredClone(args));beforeWrite?.(args);
      if(writeHold){writeEntered=true;await writeHold.promise;}enforce(args);
      if(mode==='before-commit')throw Error('Écriture locale indisponible avant commit simulé.');
      clients.push({...structuredClone(args.data),country:args.data.country||'CH',created_at:'2026-10-03T10:00:00Z'});writes++;
      if(mode==='ack-member')nativeNonce=nonceB;
      if(mode==='ack-read')blocked=true;
      if(mode==='lost'){blocked=true;throw Error('Réponse de création perdue après commit simulé.');}
      return structuredClone(args.data);
    }
    if(command==='update_record'&&args.entity==='clients'){enforce(args);const index=clients.findIndex(row=>row.id===args.id);expect(index).toBeGreaterThanOrEqual(0);clients[index]={...clients[index],...structuredClone(args.data)};writes++;return null;}
    throw Error('Native command outside this closed fixture: '+command);
  });
  // Read/write methods under test remain actual. Only unrelated background
  // preview services are stubbed, as in maintained mobile-harness defaults.
  vi.spyOn(desktopApi,'getCloudBackupState').mockResolvedValue({enabled:false,connected:false,backups:[]} as never);
  vi.spyOn(desktopApi,'getReminderSettings').mockResolvedValue({enabled:false,senderName:'',lastScanAt:''} as never);
  vi.spyOn(desktopApi,'listReminderTemplates').mockResolvedValue([]);vi.spyOn(desktopApi,'listReminders').mockResolvedValue([]);
  vi.spyOn(desktopApi,'getSecureUpdatePolicy').mockResolvedValue({enabled:false,reason:'Recette locale'} as never);
  vi.spyOn(desktopApi,'getProjectSyncStatus').mockResolvedValue({pending:0,syncing:false,connected:false,documents:[]} as never);
  vi.spyOn(desktopApi,'syncProjectDocuments').mockResolvedValue({pending:0,syncing:false,connected:false,documents:[]} as never);
  workspace=await desktopApi.loadWorkspace();reads=[];
  container=document.createElement('div');container.id='root';document.body.append(container);root=createRoot(container);
  await reactAct(async()=>root!.render(<Host/>));await settle();
});
afterEach(async()=>{writeHold?.resolve(undefined);readHold?.resolve(undefined);if(root)await reactAct(async()=>root!.unmount());root=undefined;container?.remove();await setAppLanguage('fr');expect(externalRequests).toBe(0);expect((globalThis as any).__quickClientImportRequests||0).toBe(0);vi.unstubAllGlobals();vi.restoreAllMocks();});

describe('actual quick-client durable creation with DocumentEditor, WorkspaceApp.act and bridge',()=>{
  it('does not resend a client after lost ACK and app restart with the retained document draft',async()=>{
    await prepareQuick();mode='lost';await addQuick();expect(writes).toBe(1);const first=writeAttempts[0].data.id;expect(draftValue().quickClient.company).toBe('Client Témoin SA');
    await restart();await click('Ventes');await restoreDocument();await addQuick();
    expect(writes).toBe(1);expect(writeAttempts).toHaveLength(1);expect(clients.map(row=>row.id)).toEqual([first]);expect(draftValue().quickClientCreationId).toBe(first);verifyRetained();
  });
  it('persists one strict UUID with all ten final quick-client DOM values before writing',async()=>{
    await prepareQuick();const id=draftValue().quickClientCreationId;expect(id).toMatch(/^[a-f\d]{8}-[a-f\d]{4}-[a-f\d]{4}-[a-f\d]{4}-[a-f\d]{12}$/i);
    await quickChange('company','Dernière frappe SA',false);await change('title','Titre final non rendu',false);
    beforeWrite=args=>{expect(draftValue().quickClient.company).toBe('Dernière frappe SA');expect(draftValue().documentTitle).toBe('Titre final non rendu');expect(args.data.id).toBe(id);expect(args.data.company).toBe('Dernière frappe SA');};
    await addQuick();expect(writes).toBe(1);expect(writeAttempts[0].expectedWorkspaceScope).toBe(scope);expect(writeAttempts[0].expectedMemberContextNonce).toBe(nonceA);expect(draftValue().selectedClientId).toBe(id);expect(draftValue().documentTitle).toBe('Titre final non rendu');expect(draftValue().quickClientCreationId).not.toBe(id);expect(draftValue().quickClientOpen).toBe(false);expect(draftValue().quickClient.company).toBe('');expect(draftKeys()).toHaveLength(1);expect(publications).toHaveLength(1);expect(reads.every(read=>read.args.expectedWorkspaceScope===scope&&read.args.expectedMemberContextNonce===nonceA)).toBe(true);
    expect(writeAttempts[0].data).toEqual({id,name:'Dernière frappe SA',contact_person:'Alice Témoin',company:'Dernière frappe SA',email:'alice@example.test',phone:'+41220000000',address_line1:'Rue témoin',address_line2:'7',postal_code:'1201',city:'Genève',canton:'GE',country:'CH',notes:''});
  });
  it('retains the original document, lines, amounts, dates, notes and footer after confirmed client creation',async()=>{
    await prepareQuick();await closeDocument();const key=draftKeys()[0],stored=JSON.parse(localStorage.getItem(key)!);Object.assign(stored.value,{lines:[{id:'11111111-aaaa-4aaa-8aaa-111111111111',catalogItemId:null,description:'Prestation témoin',quantity:2,unit:'h',unitPriceCents:15000,discountBp:500,vatRateBp:810}],documentNotes:'Notes du projet\nDeuxième ligne',footerText:'Conditions témoins',serviceDateFrom:'2026-10-01',serviceDateTo:'2026-10-03',invoiceType:'deposit',depositPercentage:'30',numberInputs:{quantity:'2'}});localStorage.setItem(key,JSON.stringify(stored));await restoreDocument();const before=draftValue();await addQuick();const after=draftValue();
    for(const field of Object.keys(before).filter(field=>!['selectedClientId','selectedProjectId','quickClientOpen','quickClient','quickClientCreationId'].includes(field)))expect(after[field],field).toEqual(before[field]);expect(documentTotals(after.lines)).toEqual(documentTotals(before.lines));expect(draftKeys()).toHaveLength(1);expect(document.querySelector('[role="dialog"] form')).not.toBeNull();
  });
  it('creates a distinct next quick client only after confirmed ACK and preserves the enclosing document',async()=>{
    await prepareQuick();const first=draftValue().quickClientCreationId;await addQuick();const next=draftValue().quickClientCreationId;expect(next).not.toBe(first);await click('Nouveau contact');for(const [name,value] of Object.entries({company:'Second client témoin',street:'Autre rue',postalCode:'1000',city:'Lausanne'}))await quickChange(name,value);await addQuick();expect(writeAttempts.map(row=>row.data.id)).toEqual([first,next]);expect(writes).toBe(2);expect(draftValue().documentTitle).toBe('Travaux témoins');expect(draftValue().selectedClientId).toBe(next);expect(draftValue().quickClientCreationId).not.toBe(next);expect(draftKeys()).toHaveLength(1);
  });
  it('uses the same durable quick-client path in a real new invoice editor',async()=>{
    await prepareQuick('invoices');const id=draftValue().quickClientCreationId;const before=draftValue();await addQuick();expect(writes).toBe(1);expect(writeAttempts[0].data.id).toBe(id);expect(draftValue().selectedClientId).toBe(id);expect(draftValue().invoiceType).toBe(before.invoiceType);expect(draftValue().lines).toEqual(before.lines);expect(draftValue().dueDate).toBe(before.dueDate);expect(draftKeys()[0]).toContain('invoices');expect(document.querySelector('[role="dialog"] form')).not.toBeNull();
  });
  it('keeps an invoice quick-client UUID after lost ACK and full app restart',async()=>{
    await prepareQuick('invoices');const id=draftValue().quickClientCreationId;mode='lost';await addQuick();expect(writes).toBe(1);await restart();await click('Ventes');await click('Factures');await click('Nouvelle facture');await until(()=>buttons(draftText('Reprendre ma saisie')).length>0);await click(draftText('Reprendre ma saisie'));await addQuick();expect(writes).toBe(1);expect(writeAttempts).toHaveLength(1);expect(draftValue().quickClientCreationId).toBe(id);verifyRetained();
  });
  it('preserves a real existing quote and its lines when adding a quick client and retains the project-clearing rule',async()=>{
    const old='22222222-aaaa-4aaa-8aaa-222222222222',quote='33333333-aaaa-4aaa-8aaa-333333333333',project='44444444-aaaa-4aaa-8aaa-444444444444';clients.push({id:old,name:'Ancien client',company:'Ancien client',contact_person:'',country:'CH'});projects.push({id:project,client_id:old,name:'Projet témoin',status:'planned'});quotes.push({id:quote,title:'Devis existant',client_id:old,project_id:project,status:'brouillon',issue_date:'2026-10-01',valid_until:'2026-10-31',currency:'CHF',notes:'Notes conservées',terms:'Conditions conservées'});quoteItems.push({id:'55555555-aaaa-4aaa-8aaa-555555555555',quote_id:quote,position:0,description:'Prestation conservée',quantity:2,unit:'h',unit_price_cents:15000,vat_rate_bp:810,discount_bp:500});const current=await desktopApi.loadWorkspace(scope,nonceA);await reactAct(async()=>exposed.setCurrent(current));await click('Ventes');const edit=document.querySelector<HTMLButtonElement>('[aria-label="Modifier le devis Devis existant"]')!;expect(edit).not.toBeNull();await reactAct(async()=>edit.click());await until(()=>document.querySelector('[name="title"]')!==null);await click('Nouveau contact');for(const [name,value] of Object.entries({company:'Nouveau client du devis',street:'Autre rue',postalCode:'1201',city:'Genève'}))await quickChange(name,value);const before=draftValue();expect(before.selectedProjectId).toBe(project);await addQuick();const after=draftValue();expect(writes).toBe(1);expect(after.selectedProjectId).toBe('');expect(after.documentTitle).toBe(before.documentTitle);expect(after.lines).toEqual(before.lines);expect(after.documentNotes).toBe(before.documentNotes);expect(after.footerText).toBe(before.footerText);expect(documentTotals(after.lines)).toEqual(documentTotals(before.lines));expect(quotes[0].client_id).toBe(old);expect(draftKeys()).toHaveLength(1);vi.spyOn(window,'confirm').mockReturnValue(true);await click('Abandonner le brouillon');await until(()=>document.querySelector('[role="dialog"] form')===null);expect(draftKeys()).toHaveLength(0);expect(writes).toBe(1);
  });
  it('reopens an ordinary retained document draft with the same quick-client UUID and submits that same ID',async()=>{
    await prepareQuick();const id=draftValue().quickClientCreationId;await closeDocument();await restoreDocument();expect(draftValue().quickClientCreationId).toBe(id);expect(draftValue().quickClient.company).toBe('Client Témoin SA');expect(writes).toBe(0);await addQuick();expect(clients[0].id).toBe(id);
  });
  it('does not claim ID-only success for edited fields after lost ACK, closing and resuming',async()=>{
    await prepareQuick();const id=draftValue().quickClientCreationId;mode='lost';await addQuick();expect(writes).toBe(1);expect(document.querySelector('[data-quick-client-creation-recovery]')).not.toBeNull();expect(buttons('Vérifier maintenant')).toHaveLength(0);expect(publications).toHaveLength(0);await quickChange('company','Nom changé après perte de réponse');await quickChange('email','changed@example.test');await closeDocument();blocked=false;mode='';await restoreDocument();await addQuick();expect(writes).toBe(1);expect(writeAttempts).toHaveLength(1);expect(draftValue().quickClientCreationId).toBe(id);expect(draftValue().quickClient.company).toBe('Nom changé après perte de réponse');expect(draftValue().quickClient.email).toBe('changed@example.test');expect(draftValue().selectedClientId).toBe('');expect(clients[0].company).toBe('Client Témoin SA');verifyRetained();expect(document.body.textContent).toContain('Cet élément existe déjà');
  });
  it('retries an explicit uncommitted attempt with the same UUID and no automatic replay',async()=>{
    await prepareQuick();const id=draftValue().quickClientCreationId;mode='before-commit';await addQuick();expect(writes).toBe(0);expect(writeAttempts).toHaveLength(1);expect(draftValue().quickClientCreationId).toBe(id);expect(document.querySelector('[data-quick-client-creation-recovery]')).not.toBeNull();mode='';await addQuick();expect(writes).toBe(1);expect(writeAttempts.map(row=>row.data.id)).toEqual([id,id]);
  });
  it('writes at most once when two client clicks occur during held native creation',async()=>{
    await prepareQuick();const id=draftValue().quickClientCreationId;writeHold=deferred();await addQuick();await until(()=>writeEntered);await addQuick();expect(writeAttempts).toHaveLength(1);await reactAct(async()=>writeHold!.resolve(undefined));await until(()=>draftValue().selectedClientId===id);expect(writes).toBe(1);expect(publications).toHaveLength(1);
  });
  it('blocks failed final local storage and performs only a local DOM capture on retry',async()=>{
    await prepareQuick();const id=draftValue().quickClientCreationId;await quickChange('company','Saisie finale non rendue',false);const original=Storage.prototype.setItem;const failed=vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,key,value){if(key.startsWith(FORM_DRAFT_PREFIX))throw new DOMException('Capture blocked','QuotaExceededError');original.call(this,key,value);});await addQuick();expect(writeAttempts).toHaveLength(0);expect(writes).toBe(0);expect(document.querySelector('[data-quick-client-storage-recovery]')).not.toBeNull();failed.mockRestore();expect(buttons('Ajouter et sélectionner')[0].disabled).toBe(true);await addQuick();expect(writeAttempts).toHaveLength(0);await click(draftText('Réessayer la sauvegarde locale'));expect(writeAttempts).toHaveLength(0);expect(draftValue().quickClientCreationId).toBe(id);expect(draftValue().quickClient.company).toBe('Saisie finale non rendue');expect(document.querySelector('[data-quick-client-storage-recovery]')).toBeNull();await addQuick();expect(clients[0].id).toBe(id);
  });
  it('blocks setItem that returns but immediate readback is unavailable before any IPC',async()=>{
    await prepareQuick();const id=draftValue().quickClientCreationId;const original=Storage.prototype.getItem;const failed=vi.spyOn(Storage.prototype,'getItem').mockImplementation(function(this:Storage,key){if(key.startsWith(FORM_DRAFT_PREFIX))throw new DOMException('Readback blocked','SecurityError');return original.call(this,key);});await addQuick();expect(writeAttempts).toHaveLength(0);expect(writes).toBe(0);expect(document.querySelector('[data-quick-client-storage-recovery]')).not.toBeNull();failed.mockRestore();await click(draftText('Réessayer la sauvegarde locale'));expect(writeAttempts).toHaveLength(0);expect(draftValue().quickClientCreationId).toBe(id);expect(document.querySelector('[data-quick-client-storage-recovery]')).toBeNull();
  });
  it('blocks setItem that silently keeps the older draft, then locally captures the exact final values',async()=>{
    await prepareQuick();const id=draftValue().quickClientCreationId;await quickChange('phone','+41221234567',false);const original=Storage.prototype.setItem;const failed=vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,key,value){if(key.startsWith(FORM_DRAFT_PREFIX))return;original.call(this,key,value);});await addQuick();expect(writeAttempts).toHaveLength(0);expect(document.querySelector('[data-quick-client-storage-recovery]')).not.toBeNull();failed.mockRestore();await click(draftText('Réessayer la sauvegarde locale'));expect(draftValue().quickClientCreationId).toBe(id);expect(draftValue().quickClient.phone).toBe('+41221234567');expect(writeAttempts).toHaveLength(0);
  });
  it('preserves an acknowledged client when storing the quick-client reset fails and retry remains local',async()=>{
    await prepareQuick();const id=draftValue().quickClientCreationId;const original=Storage.prototype.setItem;let failed:ReturnType<typeof vi.spyOn>|undefined;beforeWrite=()=>{failed=vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,key,value){if(key.startsWith(FORM_DRAFT_PREFIX))throw new DOMException('Reset capture blocked','QuotaExceededError');original.call(this,key,value);});};await addQuick();expect(writes).toBe(1);expect(clients[0].id).toBe(id);expect(publications).toHaveLength(1);expect(document.querySelector('[data-quick-client-storage-recovery]')).not.toBeNull();expect(document.querySelector<HTMLSelectElement>('[name="clientId"]')!.value).toBe(id);failed!.mockRestore();beforeWrite=undefined;await click(draftText('Réessayer la sauvegarde locale'));expect(writeAttempts).toHaveLength(1);expect(draftValue().selectedClientId).toBe(id);expect(draftValue().quickClientCreationId).not.toBe(id);expect(draftValue().quickClientOpen).toBe(false);expect(document.querySelector('[data-quick-client-storage-recovery]')).toBeNull();expect(draftValue().documentTitle).toBe('Travaux témoins');
  });
  it('rejects a malformed stored UUID without silently assigning another or sending client creation',async()=>{
    await prepareQuick();await closeDocument();const key=draftKeys()[0],stored=JSON.parse(localStorage.getItem(key)!);stored.value.quickClientCreationId='not-a-uuid';localStorage.setItem(key,JSON.stringify(stored));await click('Nouveau devis');await until(()=>document.querySelector('[role="dialog"] form')!==null);expect(document.body.textContent).toContain('brouillon');expect(JSON.parse(localStorage.getItem(key)!).value.quickClientCreationId).toBe('not-a-uuid');expect(writeAttempts).toHaveLength(0);expect(document.querySelector<HTMLButtonElement>('[role="dialog"] button[type="submit"]')!.disabled).toBe(true);
  });
  it('does not close or rotate UUID on failed discard and starts fresh only after verified deletion',async()=>{
    await prepareQuick();const id=draftValue().quickClientCreationId;vi.spyOn(window,'confirm').mockReturnValue(true);const original=Storage.prototype.removeItem;const failed=vi.spyOn(Storage.prototype,'removeItem').mockImplementation(function(this:Storage,key){if(key.startsWith(FORM_DRAFT_PREFIX))throw new DOMException('Deletion blocked','SecurityError');original.call(this,key);});await click('Abandonner le brouillon');expect(draftValue().quickClientCreationId).toBe(id);expect(document.querySelector('[role="dialog"] form')).not.toBeNull();expect(writeAttempts).toHaveLength(0);failed.mockRestore();await click('Abandonner le brouillon');await until(()=>document.querySelector('[role="dialog"] form')===null);expect(draftKeys()).toHaveLength(0);await click('Nouveau devis');await until(()=>document.querySelector('[name="title"]')!==null);await change('title','Autre document');expect(draftValue().quickClientCreationId).not.toBe(id);expect(writeAttempts).toHaveLength(0);
  });
  it('does not discard when removeItem returns but readback still finds the original draft',async()=>{
    await prepareQuick();const id=draftValue().quickClientCreationId;vi.spyOn(window,'confirm').mockReturnValue(true);const original=Storage.prototype.removeItem;const failed=vi.spyOn(Storage.prototype,'removeItem').mockImplementation(function(this:Storage,key){if(key.startsWith(FORM_DRAFT_PREFIX))return;original.call(this,key);});await click('Abandonner le brouillon');expect(draftValue().quickClientCreationId).toBe(id);expect(document.querySelector('[role="dialog"] form')).not.toBeNull();expect(writes).toBe(0);failed.mockRestore();await click('Abandonner le brouillon');await until(()=>document.querySelector('[role="dialog"] form')===null);
  });
  it('keeps existing required address and name validation and sends no invalid client',async()=>{
    await prepareQuick();const id=draftValue().quickClientCreationId;await quickChange('company','');await quickChange('contactPerson','');await quickChange('street','');await addQuick();expect(writeAttempts).toHaveLength(0);expect(writes).toBe(0);expect(document.body.textContent).toContain('renseignez au moins un nom de contact');expect(draftValue().quickClientCreationId).toBe(id);expect(draftValue().quickClientOpen).toBe(true);
  });
  it('guards the original physical workspace before held native creation without a recovery loop',async()=>{
    await prepareQuick();const id=draftValue().quickClientCreationId;writeHold=deferred();await addQuick();await until(()=>writeEntered);nativeScope='other-workspace';await reactAct(async()=>writeHold!.resolve(undefined));await until(()=>document.body.textContent?.includes('Rouvrez cette action dans la bonne entreprise')??false);expect(writes).toBe(0);expect(publications).toHaveLength(0);expect(draftValue().quickClientCreationId).toBe(id);expect(buttons('Vérifier maintenant')).toHaveLength(0);expect(buttons('Ajouter et sélectionner')[0].disabled).toBe(false);verifyRetained();
  });
  it('guards the original member before held native creation without publishing or resetting the client',async()=>{
    await prepareQuick();const id=draftValue().quickClientCreationId;writeHold=deferred();await addQuick();await until(()=>writeEntered);nativeNonce=nonceB;await reactAct(async()=>writeHold!.resolve(undefined));await until(()=>document.body.textContent?.includes('Ouvrez le bon compte')??false);expect(writes).toBe(0);expect(publications).toHaveLength(0);expect(draftValue().quickClientCreationId).toBe(id);expect(buttons('Vérifier maintenant')).toHaveLength(0);expect(buttons('Ajouter et sélectionner')[0].disabled).toBe(false);verifyRetained();
  });
  it('rejects a changed member after commit ACK while preserving the original quick-client draft',async()=>{
    await prepareQuick();const id=draftValue().quickClientCreationId;mode='ack-member';await addQuick();expect(writes).toBe(1);expect(publications).toHaveLength(0);expect(draftValue().quickClientCreationId).toBe(id);expect(draftValue().selectedClientId).toBe('');expect(document.body.textContent).toContain('Ouvrez le bon compte');expect(reads.every(read=>read.args.expectedMemberContextNonce===nonceA)).toBe(true);verifyRetained();
  });
  it('recovers only the original guarded reads after acknowledged creation without sending a second creation',async()=>{
    await prepareQuick();const id=draftValue().quickClientCreationId;mode='ack-read';await addQuick();await until(()=>buttons('Actualiser les données').length>0);expect(writes).toBe(1);expect(draftValue().quickClientCreationId).toBe(id);expect(publications).toHaveLength(0);blocked=false;await click('Actualiser les données');await until(()=>draftValue().selectedClientId===id);expect(writeAttempts).toHaveLength(1);expect(publications).toHaveLength(1);expect(reads.every(read=>read.args.expectedWorkspaceScope===scope&&read.args.expectedMemberContextNonce===nonceA)).toBe(true);expect(buttons('Actualiser les données')).toHaveLength(0);
  });
  it('terminates acknowledged read recovery on a foreign member instead of endlessly showing the retry modal',async()=>{
    await prepareQuick();const id=draftValue().quickClientCreationId;mode='ack-read';await addQuick();await until(()=>buttons('Actualiser les données').length>0);blocked=false;nativeNonce=nonceB;await click('Actualiser les données');await until(()=>document.body.textContent?.includes('Ouvrez le bon compte')??false);expect(writes).toBe(1);expect(writeAttempts).toHaveLength(1);expect(publications).toHaveLength(0);expect(draftValue().quickClientCreationId).toBe(id);expect(buttons('Actualiser les données')).toHaveLength(0);expect(buttons('Ajouter et sélectionner')[0].disabled).toBe(false);verifyRetained();
  });
  it.each(['fr','de','it','en'] as const)('does not overwrite an initially unreadable prior UUID and requires reopening in %s',async language=>{
    const allowed=new Set(Object.values(languageAssets));vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL)=>{if(!allowed.has(String(input))){externalRequests++;throw Error('External request forbidden.');}return {ok:true,json:async()=>({'QA local pack':'QA local pack'})} as Response;}));await prepareQuick();const key=draftKeys()[0],id=draftValue().quickClientCreationId,originalDraft=localStorage.getItem(key)!;await closeDocument();await reactAct(async()=>{await setAppLanguage(language);});const original=Storage.prototype.getItem;const failed=vi.spyOn(Storage.prototype,'getItem').mockImplementation(function(this:Storage,name){if(name.startsWith(FORM_DRAFT_PREFIX))throw new DOMException('Initial read blocked','SecurityError');return original.call(this,name);});await click('Nouveau devis');await until(()=>document.querySelector('[data-quick-client-read-recovery]')!==null);expect(document.querySelector('[data-quick-client-read-recovery]')?.textContent).toContain(quickClientCreationRecovery[language].read);expect(document.querySelector<HTMLFieldSetElement>('fieldset.document-form')!.disabled).toBe(true);await change('title','Should not overwrite');expect(writeAttempts).toHaveLength(0);failed.mockRestore();expect(localStorage.getItem(key)).toBe(originalDraft);await click(quickClientCreationRecovery[language].reopen);await until(()=>document.querySelector('[role="dialog"] form')===null);await restoreDocument();expect(draftValue().quickClientCreationId).toBe(id);expect(draftValue().documentTitle).toBe('Travaux témoins');expect(writeAttempts).toHaveLength(0);
  });
  it.each(['fr','de','it','en'] as const)('renders the real local-only capture guide in %s',async language=>{
    const allowed=new Set(Object.values(languageAssets));vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL)=>{if(!allowed.has(String(input))){externalRequests++;throw Error('External request forbidden.');}return {ok:true,json:async()=>({'QA local pack':'QA local pack'})} as Response;}));await prepareQuick();await reactAct(async()=>{await setAppLanguage(language);});const original=Storage.prototype.setItem;const failed=vi.spyOn(Storage.prototype,'setItem').mockImplementation(function(this:Storage,key,value){if(key.startsWith(FORM_DRAFT_PREFIX))throw new DOMException('Capture blocked','QuotaExceededError');original.call(this,key,value);});await addQuick();expect(document.querySelector('[data-quick-client-storage-recovery]')?.textContent).toContain(quickClientCreationRecovery[language].storage);expect(writeAttempts).toHaveLength(0);failed.mockRestore();await click(draftText('Réessayer la sauvegarde locale'));expect(document.querySelector('[data-quick-client-storage-recovery]')).toBeNull();expect(writeAttempts).toHaveLength(0);
  });
  it.each(['fr','de','it','en'] as const)('requires an explicit legacy decision in %s before assigning a new UUID or creating a client',async language=>{
    const allowed=new Set(Object.values(languageAssets));vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL)=>{if(!allowed.has(String(input))){externalRequests++;throw Error('External request forbidden.');}return {ok:true,json:async()=>({'QA local pack':'QA local pack'})} as Response;}));await prepareQuick();const first=draftValue().quickClientCreationId;await closeDocument();const key=draftKeys()[0],stored=JSON.parse(localStorage.getItem(key)!);delete stored.value.quickClientCreationId;localStorage.setItem(key,JSON.stringify(stored));await reactAct(async()=>{await setAppLanguage(language);});await restoreDocument();expect(document.querySelector('[data-quick-client-legacy-creation]')?.textContent).toContain(quickClientCreationRecovery[language].legacy);expect(draftValue().quickClientCreationId).toBeUndefined();expect(buttons('Ajouter et sélectionner')[0].disabled).toBe(true);expect(writeAttempts).toHaveLength(0);await click(quickClientCreationRecovery[language].prepare);expect(draftValue().quickClientCreationId).toMatch(/^[a-f\d-]{36}$/i);expect(draftValue().quickClientCreationId).not.toBe(first);expect(draftValue().quickClient.company).toBe('Client Témoin SA');expect(writeAttempts).toHaveLength(0);expect(document.querySelector('[data-quick-client-legacy-creation]')).toBeNull();
  });
  it.each(['fr','de','it','en'] as const)('renders the actual unknown-create manual verification guide in %s',async language=>{
    const allowed=new Set(Object.values(languageAssets));vi.stubGlobal('fetch',vi.fn(async(input:RequestInfo|URL)=>{if(!allowed.has(String(input))){externalRequests++;throw Error('External request forbidden.');}return {ok:true,json:async()=>({'QA local pack':'QA local pack'})} as Response;}));await prepareQuick();await reactAct(async()=>{await setAppLanguage(language);});mode='lost';await addQuick();expect(document.querySelector('[data-quick-client-creation-recovery]')?.textContent).toContain(quickClientCreationRecovery[language].instruction);expect(document.querySelector('[data-quick-client-creation-recovery]')?.textContent).toContain(quickClientCreationRecovery[language].title);expect(publications).toHaveLength(0);expect(draftKeys()).toHaveLength(1);expect(writes).toBe(1);expect(buttons('Vérifier maintenant')).toHaveLength(0);
  });

});
vi.hoisted(()=>{
  (globalThis as any).__quickClientImportRequests=0;
  Object.defineProperty(window,'matchMedia',{configurable:true,value:()=>({matches:false,addEventListener:()=>{},removeEventListener:()=>{},addListener:()=>{},removeListener:()=>{}})});
  HTMLElement.prototype.scrollIntoView=()=>{};window.scrollTo=()=>{};
  (globalThis as any).ResizeObserver=class{observe(){}unobserve(){}disconnect(){}};
  globalThis.fetch=async()=>{(globalThis as any).__quickClientImportRequests++;throw Error('External fetch forbidden during maintained quick-client test import.');};
});
