// @vitest-environment jsdom
// @vitest-environment-options {"url":"http://localhost","pretendToBeVisual":true}
/** Actual candidate WorkspaceApp ribbon, act, provider, guarded bridge and
 * recovery. Closed native IPC simulates boundary refusals only; no hooks,
 * actions, stopTimer or loadWorkspace functions are doubled. Native witnesses
 * are separate unexecuted Tauri/LocalStore tests, not proved by this suite. */
import {act as reactAct,useState} from 'react';
import {createRoot,type Root} from 'react-dom/client';
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {desktopApi} from './bridge';
import {WorkspaceApp} from './WorkspaceApp';
import {FormDraftIdentityProvider} from './useFormDraft';
import {ZentraAssistantProvider} from './ZentraAssistant';
import {initialOnboardingSettings} from './onboardingDraft';
import {setAppLanguage} from './language';
import {recentDiagnosticEvents} from './diagnostics';
import {WorkspaceRefreshAfterMutationError} from './workspaceMutation';
import {WorkspaceOriginChangedError,workspaceOriginFailure} from './workspaceOrigin';
import type {Workspace} from './types';
const transport=vi.hoisted(()=>({invoke:vi.fn()}));
vi.mock('@tauri-apps/api/core',()=>({Channel:class{},invoke:transport.invoke,isTauri:()=>false}));
const scopeA='stop-timer-company-a',scopeB='stop-timer-company-b',nonceA='a'.repeat(32),nonceB='b'.repeat(32);
const physicalMessage='Champ invalide : L’entreprise ouverte a changé. Rouvrez cette action dans le bon espace.';
const memberMessage='Champ invalide : Le compte connecté a changé. Rouvrez cette action avec le bon compte.';
function deferred(){let resolve!:()=>void;const promise=new Promise<void>(yes=>resolve=yes);return {promise,resolve};}
let root:Root|undefined,host:HTMLDivElement,workspace:Workspace,nativeScope=scopeA,nativeNonce=nonceA;
let held:ReturnType<typeof deferred>|null=null,entered=false,attempts:any[]=[],reads:any[]=[],writes=0,publications:Workspace[]=[],external=0,mode='',blocked=false,readFailures=0,timer=true;
const settings={...structuredClone(initialOnboardingSettings),organization:{...initialOnboardingSettings.organization,legalName:'Atelier chronomètre',contactName:'Compte témoin'}};
const raw=()=>({work_notes_scope:nativeScope,settings:{company_name:'Atelier chronomètre',extra_settings_json:JSON.stringify(settings)},projects:[{id:'project-timer',name:'Projet témoin',status:'en_cours'}],clients:[],employees:[],time_entries:timer?[]:[{id:'entry-one',project_id:'project-timer',date:'2026-10-03',minutes:60,break_minutes:5,billable:true,billing_rate_cents:12345,cost_rate_cents:6789,note:'Mesure conservée',status:'approuve'}],active_timer:timer?{id:1,project_id:'project-timer',started_at:'2026-10-03T10:00:00Z',note:'Mesure conservée',billable:true,billing_rate_cents:12345,cost_rate_cents:6789}:null});
function enforce(args:any){if(args?.expectedWorkspaceScope!==undefined&&args.expectedWorkspaceScope!==nativeScope)throw physicalMessage;if(args?.expectedMemberContextNonce!==undefined&&args.expectedMemberContextNonce!==nativeNonce)throw memberMessage;}
async function settle(){await reactAct(async()=>{for(let i=0;i<25;i++)await Promise.resolve();await new Promise<void>(yes=>setTimeout(yes,1));});}
async function until(check:()=>boolean){for(let i=0;i<50&&!check();i++)await settle();expect(check(),document.body.textContent??'').toBe(true);}
const stopButton=()=>document.querySelector<HTMLButtonElement>('.timer-ribbon button');
async function clickStop(){expect(stopButton()).not.toBeNull();await reactAct(async()=>stopButton()!.click());await settle();}
function assertOriginalCalls(){expect(attempts).toHaveLength(1);expect(attempts[0]).toEqual({expectedWorkspaceScope:scopeA,expectedMemberContextNonce:nonceA});for(const row of reads)expect(row.args).toEqual({expectedWorkspaceScope:scopeA,expectedMemberContextNonce:nonceA});}
function terminal(expected:string){expect(publications).toHaveLength(0);expect(document.body.textContent).toContain(expected);expect(document.body.textContent).not.toContain('Le pointage a été arrêté et enregistré.');expect(document.body.textContent).not.toContain('Actualiser les données');expect(stopButton()?.disabled).toBe(false);}
async function mount(){workspace=await desktopApi.loadWorkspace();reads=[];host=document.createElement('div');host.id='root';document.body.append(host);root=createRoot(host);function Host(){const [value,setValue]=useState(workspace);return <FormDraftIdentityProvider companyId={scopeA} organizationId="synthetic-timer-org" memberId="11111111-1111-4111-8111-111111111111" memberContextNonce={nonceA} ready><ZentraAssistantProvider><WorkspaceApp workspace={value} setWorkspace={next=>{if(next&&typeof next!=='function'){publications.push(next);setValue(next);}}}/></ZentraAssistantProvider></FormDraftIdentityProvider>;}await reactAct(async()=>root!.render(<Host/>));await settle();}
beforeEach(async()=>{
 nativeScope=scopeA;nativeNonce=nonceA;held=null;entered=false;attempts=[];reads=[];writes=0;publications=[];external=0;mode='';blocked=false;readFailures=0;timer=true;localStorage.clear();sessionStorage.clear();vi.stubGlobal('IS_REACT_ACT_ENVIRONMENT',true);vi.stubGlobal('fetch',vi.fn(async()=>{external++;throw Error('External request forbidden in closed timer test');}));
 transport.invoke.mockReset();transport.invoke.mockImplementation(async(command:string,args:any)=>{
  if(command==='append_diagnostic_events')return;
  if(command==='get_app_state'||command==='get_workspace'){reads.push({command,args:structuredClone(args??{})});enforce(args);if(blocked||readFailures-->0)throw Error('Lecture locale temporairement indisponible');return command==='get_app_state'?{onboarding_completed:true}:structuredClone(raw());}
  if(command==='stop_timer'){attempts.push(structuredClone(args??{}));if(held){entered=true;await held.promise;}enforce(args);if(!timer)throw Error('Aucun chronomètre actif');timer=false;writes++;if(mode==='ack-physical')nativeScope=scopeB;if(mode==='ack-member')nativeNonce=nonceB;if(mode==='lost-ack')throw Error('Réponse locale perdue après commit simulé');return {id:'entry-one',minutes:60};}
  throw Error('Native command outside closed timer fixture: '+command);
 });
 vi.spyOn(desktopApi,'getCloudBackupState').mockResolvedValue({enabled:false,connected:false,backups:[]} as never);vi.spyOn(desktopApi,'getReminderSettings').mockResolvedValue({enabled:false,senderName:'',lastScanAt:''} as never);vi.spyOn(desktopApi,'listReminderTemplates').mockResolvedValue([]);vi.spyOn(desktopApi,'listReminders').mockResolvedValue([]);vi.spyOn(desktopApi,'getSecureUpdatePolicy').mockResolvedValue({enabled:false,reason:'Recette locale'} as never);vi.spyOn(desktopApi,'getProjectSyncStatus').mockResolvedValue({pending:0,syncing:false,connected:false,documents:[]} as never);vi.spyOn(desktopApi,'syncProjectDocuments').mockResolvedValue({pending:0,syncing:false,connected:false,documents:[]} as never);
});
afterEach(async()=>{held?.resolve();if(root)await reactAct(async()=>root!.unmount());root=undefined;host?.remove();await setAppLanguage('fr');expect(external).toBe(0);expect((globalThis as any).__stopTimerImportRequests).toBe(0);vi.unstubAllGlobals();vi.restoreAllMocks();});
describe('actual ribbon stop action with captured origin and bounded recovery',()=>{
 it('passes the captured provider origin, keeps one receipt and refreshes only that workspace',async()=>{await mount();await clickStop();await until(()=>stopButton()===null);assertOriginalCalls();expect(writes).toBe(1);expect(publications).toHaveLength(1);expect(publications[0].workNotesScope).toBe(scopeA);expect(publications[0].timeEntries[0].minutes).toBe(60);expect(publications[0].timeEntries[0].breakMinutes).toBe(5);expect(document.body.textContent).toContain('Le pointage a été arrêté et enregistré.');const events=recentDiagnosticEvents().filter(event=>event.operation==='stop_timer');expect(events.some(event=>event.phase==='success')).toBe(true);expect(JSON.stringify(events)).not.toContain(nonceA);expect(JSON.stringify(events)).not.toContain(scopeA);});
 it.each(['physical','member'] as const)('rejects a %s transition while the actual ribbon action awaits native entry',async kind=>{await mount();held=deferred();await clickStop();await until(()=>entered);if(kind==='physical')nativeScope=scopeB;else nativeNonce=nonceB;await reactAct(async()=>held!.resolve());await settle();assertOriginalCalls();expect(writes).toBe(0);expect(reads).toHaveLength(0);terminal(kind==='physical'?'L’entreprise ouverte a changé':'Le compte connecté a changé');});
 it.each(['physical','member'] as const)('terminates after an ACK followed by a %s read refusal without publishing B or looping',async kind=>{await mount();mode=kind==='physical'?'ack-physical':'ack-member';await clickStop();assertOriginalCalls();expect(writes).toBe(1);expect(reads).toHaveLength(1);terminal(kind==='physical'?'L’entreprise ouverte a changé':'Le compte connecté a changé');});
 it.each(['physical','member'] as const)('retains nonce A through an ordinary failed refresh and an explicit retry after %s transition',async kind=>{await mount();blocked=true;await clickStop();await until(()=>document.body.textContent?.includes('Actualiser les données')===true);expect(writes).toBe(1);expect(publications).toHaveLength(0);const retry=[...document.querySelectorAll<HTMLButtonElement>('button')].find(node=>node.textContent?.trim()==='Actualiser les données')!;expect(retry).toBeDefined();blocked=false;if(kind==='physical')nativeScope=scopeB;else nativeNonce=nonceB;await reactAct(async()=>retry.click());await settle();assertOriginalCalls();expect(writes).toBe(1);expect(reads).toHaveLength(3);terminal(kind==='physical'?'L’entreprise ouverte a changé':'Le compte connecté a changé');});
 it('recovers an ordinary post-ACK read failure without replaying the timer stop',async()=>{await mount();readFailures=1;await clickStop();await until(()=>stopButton()===null);assertOriginalCalls();expect(writes).toBe(1);expect(reads.map(row=>row.command)).toEqual(['get_app_state','get_app_state','get_workspace']);expect(publications).toHaveLength(1);expect(document.body.textContent).toContain('Le pointage a été arrêté et enregistré.');});
 it('admits only one stop while two actual clicks race a held command',async()=>{await mount();held=deferred();await clickStop();await until(()=>entered);await clickStop();expect(attempts).toHaveLength(1);await reactAct(async()=>held!.resolve());await until(()=>stopButton()===null);assertOriginalCalls();expect(writes).toBe(1);expect(publications).toHaveLength(1);});
 it('never automatically replays a lost stop ACK or reports that unacknowledged mutation as confirmed',async()=>{await mount();mode='lost-ack';await clickStop();assertOriginalCalls();expect(writes).toBe(1);expect(publications).toHaveLength(1);expect(publications[0].activeTimer).toBeNull();expect(document.body.textContent).not.toContain('Le pointage a été arrêté et enregistré.');expect(document.body.textContent).toContain('Réponse locale perdue');});
});
describe('guarded stop bridge legacy and exact origin contracts',()=>{
 it('preserves the exact no-argument IPC shape for a legacy caller',async()=>{await desktopApi.stopTimer();expect(transport.invoke.mock.calls.filter(([name])=>['stop_timer','get_app_state','get_workspace'].includes(name)).map(([name,args])=>({name,args}))).toEqual([{name:'stop_timer',args:undefined},{name:'get_app_state',args:undefined},{name:'get_workspace',args:undefined}]);expect(writes).toBe(1);});
 it('rejects malformed nonce before issuing any mutation or read',async()=>{await expect(desktopApi.stopTimer(scopeA,'malformed')).rejects.toThrow('Le contexte local du compte');expect(attempts).toHaveLength(0);expect(reads).toHaveLength(0);expect(writes).toBe(0);});
 it('does not convert an ordinary pre-ACK refusal into a success or refresh',async()=>{timer=false;const error=await desktopApi.stopTimer(scopeA,nonceA).catch(reason=>reason);expect(error).not.toBeInstanceOf(WorkspaceRefreshAfterMutationError);expect(error.message).toBe('Aucun chronomètre actif');expect(reads).toHaveLength(0);expect(writes).toBe(0);});
 it('checks the returned physical scope even if a faulty read transport ignores native guard',async()=>{transport.invoke.mockImplementation(async(command:string)=>command==='get_app_state'?{onboarding_completed:true}:command==='get_workspace'?{...raw(),work_notes_scope:scopeB}:{});const error=await desktopApi.stopTimer(scopeA,nonceA).catch(reason=>reason);expect(error).toBeInstanceOf(WorkspaceRefreshAfterMutationError);expect(workspaceOriginFailure(error)).toBeInstanceOf(WorkspaceOriginChangedError);expect(transport.invoke.mock.calls.filter(([name])=>name==='stop_timer')).toHaveLength(1);});
});
vi.hoisted(()=>{(globalThis as any).__stopTimerImportRequests=0;Object.defineProperty(window,'matchMedia',{configurable:true,value:()=>({matches:false,addEventListener:()=>{},removeEventListener:()=>{},addListener:()=>{},removeListener:()=>{}})});HTMLElement.prototype.scrollIntoView=()=>{};window.scrollTo=()=>{};(globalThis as any).ResizeObserver=class{observe(){}unobserve(){}disconnect(){}};globalThis.fetch=async()=>{(globalThis as any).__stopTimerImportRequests++;throw Error('External import request forbidden');};});
